INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1700,'Patient Search',0,28,10)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1701,'Patient Search',0,28,11)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1702,'Patient Search',0,28,12)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1703,'Patient Registration',0,28,2)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1704,'Home',0,28,8)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1705,'Home',0,28,9)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1706,'Home',0,28,1)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1707,'Home',0,28,14)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1708,'Reports',0,28,43)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1709,'Set Reminders',0,28,16)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1710,'Define Schedule',7,28,17)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1711,'Home',0,28,13)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1712,'Change Password',0,28,20)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1713,'Home',0,28,25)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1714,'Investigation Report',0,28,55)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1715,'Home',0,28,27)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1716,'View Schedules',7,28,85)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1717,'Today s Out-Patients',0,28,40)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1718,'BillSearch',0,28,226)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1719,'Cash Closure',0,28,46)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1720,'Cash Closure',0,28,48)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1721,'Visit Search',0,28,18)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1722,'Manage Rates',2,28,59)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1723,'Add Investigation/Groups',2,28,60)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1724,'Reference Range Mgmt',2,28,61)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1725,'Manage User',2,28,64)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1726,'Patient Search',0,28,10)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1727,'Cash Payments',0,28,67)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1728,'Check Safety Code',0,28,69)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1729,'Add Corporate & Client',2,28,72)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1730,'Task ReAssign',0,28,75)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1731,'Dashboard',0,28,77)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1732,'Plan Vacation',7,28,83)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1733,'Purchase Order',3,28,93)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1734,'Stock Receive',3,28,94)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1735,'Stock Return',3,28,95)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1736,'Stock Damage',3,28,96)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1737,'Inventory Search',3,28,97)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1738,'Categories',3,28,102)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1739,'Products',3,28,103)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1740,'Suppliers',3,28,104)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1741,'Stock Issued',3,28,116)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1742,'Stock In Hand',3,28,107)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1743,'OP Billing',0,28,108)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1744,'IP Billing',0,28,113)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1745,'Bulkload',3,28,114)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1746,'Reorder Level',3,28,115)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1747,'Stock Report',3,28,117)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1748,'Home',0,28,123)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1749,'View Profile',0,28,124)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1750,'Change Password',0,28,125)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1751,'Summary Reports',0,28,36)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1752,'All Schedules',7,28,120)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1753,'Manage Test Kit',2,28,144)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1754,'Manage Test Method',2,28,145)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1755,'Manage Test Principle',2,28,237)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1756,'Manage Test Instrument',2,28,143)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1757,'Patient Registration',0,28,137)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1758,'Patient Search',0,28,32)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1759,'Bill Search',0,28,33)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1760,'Reports',0,28,35)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1761,'Change Password',0,28,20)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1762,'Home',0,28,13)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1763,'Set Reminders',0,28,16)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1764,'Home',0,28,13)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1765,'Change Password',0,28,20)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1766,'Summary Reports',0,28,36)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1767,'Add/Change Hospital',0,28,42)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1768,'Investigation Report',0,28,135)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1769,'Collect Sample',0,28,128)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1770,'Investigation Capture',0,28,130)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1771,'Samples Report',0,28,131)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1772,'Bill Search',0,28,132)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1773,'Due Search',0,28,134)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1774,'Collection Report',0,28,138)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1775,'Add/Change Physician',0,28,141)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1776,'Manage Reference Range',2,28,61)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1777,'Manage Test Instrument',2,28,143)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1778,'Manage Test Kit',2,28,144)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1779,'Manage Test Method',2,28,145)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1780,'Manage Investigation',2,28,60)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1781,'Manage Investigation Rate',2,28,59)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1782,'Dispatch Result',0,28,147)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1783,'Modality Schedule',0,28,183)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1784,'Home',0,28,1)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1785,'In Bound Referral',8,28,126)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1786,'Today s Patients',0,28,40)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1787,'Pharmacy Billing',0,28,108)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1788,'Dispensing Report',3,28,239)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1789,'Pending Recommendation',0,28,248)
INSERT INTO menumaster  (MenuID,DisplayText,Parentid,OrgId,PageID) VALUES (1790,'Patient Call List',0,28,249)