INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1700,'Physician','Doctor',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1701,'Nurse','Nurse',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1702,'LabTech','Lab Technician',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1703,'Patient','Patient',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1704,'Reception','Reception',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1705,'Admin','Admin',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1706,'DialysisTech','Dialysis Technician',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1707,'Billing','Billing',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1708,'Xray','Xray',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1709,'Accounts','Accounts',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1710,'Pharmacist','Pharmacist',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1711,'LabReception','Reception',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1712,'LabAdmin','Admin',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1713,'MRILabTech','MRILabTech',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1714,'CTLabTech','CTLabTech',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1715,'SrLabTech','SrLabTech',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1716,'XrayTech','XrayTech',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1717,'UltraSoundTech','UltraSoundTech',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1718,'HematologyLab','HematologyLab',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1719,'BioChemistryLab','BioChemistryLab',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1720,'ClinicalPathologyLab','ClinicalPathologyLab',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1721,'ImmunologyLab','ImmunologyLab',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1722,'MicroBiologyLab','MicroBiologyLab',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1723,'HistopathologyLab','HistopathologyLab',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1724,'MolecularBiologyLab','MolecularBiologyLab',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1725,'CytogeneticsLab','CytogeneticsLab',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1726,'Dispatch','Dispatch',0,28)
INSERT INTO Role (RoleID,RoleName,Description,ParentID,OrgID)VALUES(1727,'JrLabTech','JrLabTech',0,28)


DELETE invdeptmaster where OrgID=28
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1700,'Lab',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1701,'Hematology',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1702,'Biochemistry',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1703,'Clinical Pathology',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1704,'Immunology',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1705,'Microbiology',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1706,'Histopathology',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1707,'Molecular Biology',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1708,'Cytogenetics',28,'Y')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1709,'Imaging',28,'N')
insert into invdeptmaster (Deptid,deptname,orgid,display) values(1710,'CollectionDesk',28,'N')


/*	RoleDeptMap	*/
delete from RoleDeptMap
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1700)
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1701)
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1702)
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1703)
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1704)
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1705)
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1706)
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1707)
Insert into RoleDeptMap(RoleID,DeptID)  values(1727,1708)

insert into RoleDeptMap values(1727,1701) 
insert into RoleDeptMap values(1727,1702) 
insert into RoleDeptMap values(1727,1703) 
insert into RoleDeptMap values(1727,1704) 
insert into RoleDeptMap values(1727,1705) 
insert into RoleDeptMap values(1727,1706) 
insert into RoleDeptMap values(1727,1707) 
insert into RoleDeptMap values(1727,1708) 
insert into RoleDeptMap values(1727,1710) 


