using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace Attune.Solution.QMSBusinessEntities
{
	public class IDPatternMaster
	{
		#region Fields

		private long categoryID=0;
		private string pattern=String.Empty;
		private long orgID=0;
		private string isReset=String.Empty;
		private DateTime createdDate=DateTime.MaxValue;
		private long resetNumber=0;
		private string lastGeneratedNumber=String.Empty;
		private string resetOption=String.Empty;
		private string resetBy=String.Empty;
		private string isPatternAutoGenerated=String.Empty;
		private long orgAddressID=0;
		private long patternMasterID=0;
		private string isPading=String.Empty;
		private int padLength=0;
		private DateTime resetFinancialDate=DateTime.MaxValue;
		private DateTime resetFinancialYear=DateTime.MaxValue;
		private long createdBy=0;
		private DateTime createdAt=DateTime.MaxValue;
		private long modifiedBy=0;
		private DateTime modifiedAt=DateTime.MaxValue;
		private long locationID=0;

		#endregion

		#region Properties
		/// <summary>
		/// Gets or sets the CategoryID value.
		/// </summary>
		public long CategoryID
		{
			get { return categoryID; }
			set { categoryID = value; }
		}

		/// <summary>
		/// Gets or sets the Pattern value.
		/// </summary>
		public string Pattern
		{
			get { return pattern; }
			set { pattern = value; }
		}

		/// <summary>
		/// Gets or sets the OrgID value.
		/// </summary>
		public long OrgID
		{
			get { return orgID; }
			set { orgID = value; }
		}

		/// <summary>
		/// Gets or sets the IsReset value.
		/// </summary>
		public string IsReset
		{
			get { return isReset; }
			set { isReset = value; }
		}

		/// <summary>
		/// Gets or sets the CreatedDate value.
		/// </summary>
		public DateTime CreatedDate
		{
			get { return createdDate; }
			set { createdDate = value; }
		}

		/// <summary>
		/// Gets or sets the ResetNumber value.
		/// </summary>
		public long ResetNumber
		{
			get { return resetNumber; }
			set { resetNumber = value; }
		}

		/// <summary>
		/// Gets or sets the LastGeneratedNumber value.
		/// </summary>
		public string LastGeneratedNumber
		{
			get { return lastGeneratedNumber; }
			set { lastGeneratedNumber = value; }
		}

		/// <summary>
		/// Gets or sets the ResetOption value.
		/// </summary>
		public string ResetOption
		{
			get { return resetOption; }
			set { resetOption = value; }
		}

		/// <summary>
		/// Gets or sets the ResetBy value.
		/// </summary>
		public string ResetBy
		{
			get { return resetBy; }
			set { resetBy = value; }
		}

		/// <summary>
		/// Gets or sets the IsPatternAutoGenerated value.
		/// </summary>
		public string IsPatternAutoGenerated
		{
			get { return isPatternAutoGenerated; }
			set { isPatternAutoGenerated = value; }
		}

		/// <summary>
		/// Gets or sets the OrgAddressID value.
		/// </summary>
		public long OrgAddressID
		{
			get { return orgAddressID; }
			set { orgAddressID = value; }
		}

		/// <summary>
		/// Gets or sets the PatternMasterID value.
		/// </summary>
		public long PatternMasterID
		{
			get { return patternMasterID; }
			set { patternMasterID = value; }
		}

		/// <summary>
		/// Gets or sets the IsPading value.
		/// </summary>
		public string IsPading
		{
			get { return isPading; }
			set { isPading = value; }
		}

		/// <summary>
		/// Gets or sets the PadLength value.
		/// </summary>
		public int PadLength
		{
			get { return padLength; }
			set { padLength = value; }
		}

		/// <summary>
		/// Gets or sets the ResetFinancialDate value.
		/// </summary>
		public DateTime ResetFinancialDate
		{
			get { return resetFinancialDate; }
			set { resetFinancialDate = value; }
		}

		/// <summary>
		/// Gets or sets the ResetFinancialYear value.
		/// </summary>
		public DateTime ResetFinancialYear
		{
			get { return resetFinancialYear; }
			set { resetFinancialYear = value; }
		}

		/// <summary>
		/// Gets or sets the CreatedBy value.
		/// </summary>
		public long CreatedBy
		{
			get { return createdBy; }
			set { createdBy = value; }
		}

		/// <summary>
		/// Gets or sets the CreatedAt value.
		/// </summary>
		public DateTime CreatedAt
		{
			get { return createdAt; }
			set { createdAt = value; }
		}

		/// <summary>
		/// Gets or sets the ModifiedBy value.
		/// </summary>
		public long ModifiedBy
		{
			get { return modifiedBy; }
			set { modifiedBy = value; }
		}

		/// <summary>
		/// Gets or sets the ModifiedAt value.
		/// </summary>
		public DateTime ModifiedAt
		{
			get { return modifiedAt; }
			set { modifiedAt = value; }
		}

		/// <summary>
		/// Gets or sets the LocationID value.
		/// </summary>
		public long LocationID
		{
			get { return locationID; }
			set { locationID = value; }
		}


		#endregion
}
}
