//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsUpServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhatsUpTemplateMaster
    {
        public int TemplateMasterNo { get; set; }
        public string TemplateName { get; set; }
        public Nullable<int> NoofParameters { get; set; }
    }
}
