UPDATE Complaint SET ICDCode='' where ComplaintId= 1
UPDATE Complaint SET ICDCode='H10' where ComplaintId= 2
UPDATE Complaint SET ICDCode='H52.1' where ComplaintId= 3
UPDATE Complaint SET ICDCode='H52.0' where ComplaintId= 4
UPDATE Complaint SET ICDCode='H25' where ComplaintId= 5
UPDATE Complaint SET ICDCode='S05.4' where ComplaintId= 6
UPDATE Complaint SET ICDCode='H40' where ComplaintId= 7
UPDATE Complaint SET ICDCode='H11.0' where ComplaintId= 8
UPDATE Complaint SET ICDCode='H20.0' where ComplaintId= 9
UPDATE Complaint SET ICDCode='S05' where ComplaintId= 10
UPDATE Complaint SET ICDCode='H50.9' where ComplaintId= 11
UPDATE Complaint SET ICDCode='' where ComplaintId= 12
UPDATE Complaint SET ICDCode='K21' where ComplaintId= 13
UPDATE Complaint SET ICDCode='K20' where ComplaintId= 14
UPDATE Complaint SET ICDCode='R13' where ComplaintId= 15
UPDATE Complaint SET ICDCode='K22.0' where ComplaintId= 16
UPDATE Complaint SET ICDCode='C15' where ComplaintId= 17
UPDATE Complaint SET ICDCode='Q40.1' where ComplaintId= 18
UPDATE Complaint SET ICDCode='K22.1' where ComplaintId= 19
UPDATE Complaint SET ICDCode='T18.1' where ComplaintId= 20
UPDATE Complaint SET ICDCode='K22.6' where ComplaintId= 21
UPDATE Complaint SET ICDCode='' where ComplaintId= 22
UPDATE Complaint SET ICDCode='K12.1' where ComplaintId= 23
UPDATE Complaint SET ICDCode='K12' where ComplaintId= 24
UPDATE Complaint SET ICDCode='K14.0' where ComplaintId= 25
UPDATE Complaint SET ICDCode='B37.0' where ComplaintId= 26
UPDATE Complaint SET ICDCode='K02' where ComplaintId= 27
UPDATE Complaint SET ICDCode='S00.5' where ComplaintId= 28
UPDATE Complaint SET ICDCode='K09' where ComplaintId= 29
UPDATE Complaint SET ICDCode='T18.0' where ComplaintId= 30
UPDATE Complaint SET ICDCode='K13.5' where ComplaintId= 31
UPDATE Complaint SET ICDCode='' where ComplaintId= 32
UPDATE Complaint SET ICDCode='N08.3*' where ComplaintId= 33
UPDATE Complaint SET ICDCode='N20.0' where ComplaintId= 34
UPDATE Complaint SET ICDCode='N18' where ComplaintId= 35
UPDATE Complaint SET ICDCode='N17' where ComplaintId= 36
UPDATE Complaint SET ICDCode='N04' where ComplaintId= 37
UPDATE Complaint SET ICDCode='N11.0' where ComplaintId= 38
UPDATE Complaint SET ICDCode='Q61.3' where ComplaintId= 39
UPDATE Complaint SET ICDCode='Q60.0' where ComplaintId= 40
UPDATE Complaint SET ICDCode='N13.3' where ComplaintId= 41
UPDATE Complaint SET ICDCode='N00' where ComplaintId= 42
UPDATE Complaint SET ICDCode='C64' where ComplaintId= 43
UPDATE Complaint SET ICDCode='' where ComplaintId= 44
UPDATE Complaint SET ICDCode='N23' where ComplaintId= 45
UPDATE Complaint SET ICDCode='N20.1' where ComplaintId= 46
UPDATE Complaint SET ICDCode='N13.4' where ComplaintId= 47
UPDATE Complaint SET ICDCode='' where ComplaintId= 51
UPDATE Complaint SET ICDCode='N39.0' where ComplaintId= 52
UPDATE Complaint SET ICDCode='N41.0' where ComplaintId= 53
UPDATE Complaint SET ICDCode='N30' where ComplaintId= 54
UPDATE Complaint SET ICDCode='N40' where ComplaintId= 55
UPDATE Complaint SET ICDCode='N21.0' where ComplaintId= 56
UPDATE Complaint SET ICDCode='N31' where ComplaintId= 57
UPDATE Complaint SET ICDCode='N81.1' where ComplaintId= 58
UPDATE Complaint SET ICDCode='C68.9' where ComplaintId= 59
UPDATE Complaint SET ICDCode='' where ComplaintId= 60
UPDATE Complaint SET ICDCode='N34' where ComplaintId= 61
UPDATE Complaint SET ICDCode='S37.30' where ComplaintId= 62
UPDATE Complaint SET ICDCode='T83.0' where ComplaintId= 63
UPDATE Complaint SET ICDCode='N35' where ComplaintId= 64
UPDATE Complaint SET ICDCode='C68.0' where ComplaintId= 65
UPDATE Complaint SET ICDCode='N36.2' where ComplaintId= 66
UPDATE Complaint SET ICDCode='T19.0' where ComplaintId= 67
UPDATE Complaint SET ICDCode='' where ComplaintId= 69
UPDATE Complaint SET ICDCode='N34' where ComplaintId= 70
UPDATE Complaint SET ICDCode='N36.3' where ComplaintId= 71
UPDATE Complaint SET ICDCode='S37.30' where ComplaintId= 72
UPDATE Complaint SET ICDCode='T83.0' where ComplaintId= 73
UPDATE Complaint SET ICDCode='N35' where ComplaintId= 74
UPDATE Complaint SET ICDCode='C68.0' where ComplaintId= 76
UPDATE Complaint SET ICDCode='T19.0' where ComplaintId= 77
UPDATE Complaint SET ICDCode='' where ComplaintId= 78
UPDATE Complaint SET ICDCode='B19' where ComplaintId= 79
UPDATE Complaint SET ICDCode='B16' where ComplaintId= 80
UPDATE Complaint SET ICDCode='K70.3' where ComplaintId= 81
UPDATE Complaint SET ICDCode='S36.10' where ComplaintId= 82
UPDATE Complaint SET ICDCode='S36.10' where ComplaintId= 83
UPDATE Complaint SET ICDCode='K76.1' where ComplaintId= 84
UPDATE Complaint SET ICDCode='K75.0' where ComplaintId= 85
UPDATE Complaint SET ICDCode='Q44.6' where ComplaintId= 86
UPDATE Complaint SET ICDCode='C22.0' where ComplaintId= 87
UPDATE Complaint SET ICDCode='K71.0' where ComplaintId= 88
UPDATE Complaint SET ICDCode='' where ComplaintId= 89
UPDATE Complaint SET ICDCode='K80' where ComplaintId= 90
UPDATE Complaint SET ICDCode='K81.0' where ComplaintId= 91
UPDATE Complaint SET ICDCode='K81.1' where ComplaintId= 92
UPDATE Complaint SET ICDCode='K83' where ComplaintId= 93
UPDATE Complaint SET ICDCode='K74.4' where ComplaintId= 94
UPDATE Complaint SET ICDCode='K83.0' where ComplaintId= 95
UPDATE Complaint SET ICDCode='A01.0' where ComplaintId= 96
UPDATE Complaint SET ICDCode='K83.1' where ComplaintId= 97
UPDATE Complaint SET ICDCode='K82.2' where ComplaintId= 98
UPDATE Complaint SET ICDCode='' where ComplaintId= 99
UPDATE Complaint SET ICDCode='K30' where ComplaintId= 100
UPDATE Complaint SET ICDCode='K29.1' where ComplaintId= 101
UPDATE Complaint SET ICDCode='K29.5' where ComplaintId= 102
UPDATE Complaint SET ICDCode='K21' where ComplaintId= 103
UPDATE Complaint SET ICDCode='K29' where ComplaintId= 104
UPDATE Complaint SET ICDCode='K27' where ComplaintId= 105
UPDATE Complaint SET ICDCode='E10.6' where ComplaintId= 106
UPDATE Complaint SET ICDCode='K31.1' where ComplaintId= 107
UPDATE Complaint SET ICDCode='C16' where ComplaintId= 108
UPDATE Complaint SET ICDCode='' where ComplaintId= 109
UPDATE Complaint SET ICDCode='K85' where ComplaintId= 110
UPDATE Complaint SET ICDCode='K86.1' where ComplaintId= 111
UPDATE Complaint SET ICDCode='K86.3' where ComplaintId= 112
UPDATE Complaint SET ICDCode='C25' where ComplaintId= 113
UPDATE Complaint SET ICDCode='K86.8' where ComplaintId= 114
UPDATE Complaint SET ICDCode='E10' where ComplaintId= 115
UPDATE Complaint SET ICDCode='' where ComplaintId= 116
UPDATE Complaint SET ICDCode='A01.0' where ComplaintId= 117
UPDATE Complaint SET ICDCode='A08.3' where ComplaintId= 118
UPDATE Complaint SET ICDCode='K90' where ComplaintId= 119
UPDATE Complaint SET ICDCode='K56.0' where ComplaintId= 120
UPDATE Complaint SET ICDCode='K56.1' where ComplaintId= 121
UPDATE Complaint SET ICDCode='B76.9' where ComplaintId= 122
UPDATE Complaint SET ICDCode='I88.0' where ComplaintId= 123
UPDATE Complaint SET ICDCode='A07.1' where ComplaintId= 124
UPDATE Complaint SET ICDCode='' where ComplaintId= 125
UPDATE Complaint SET ICDCode='A06' where ComplaintId= 126
UPDATE Complaint SET ICDCode='A09' where ComplaintId= 127
UPDATE Complaint SET ICDCode='A06.0' where ComplaintId= 128
UPDATE Complaint SET ICDCode='K59.0' where ComplaintId= 129
UPDATE Complaint SET ICDCode='C18' where ComplaintId= 130
UPDATE Complaint SET ICDCode='K51.4' where ComplaintId= 131
UPDATE Complaint SET ICDCode='' where ComplaintId= 132
UPDATE Complaint SET ICDCode='I84' where ComplaintId= 133
UPDATE Complaint SET ICDCode='K60.3' where ComplaintId= 134
UPDATE Complaint SET ICDCode='K51.2' where ComplaintId= 135
UPDATE Complaint SET ICDCode='B76.9' where ComplaintId= 136
UPDATE Complaint SET ICDCode='A63.0' where ComplaintId= 137
UPDATE Complaint SET ICDCode='C20' where ComplaintId= 138
UPDATE Complaint SET ICDCode='N15.1' where ComplaintId= 139
UPDATE Complaint SET ICDCode='K56.4' where ComplaintId= 140
UPDATE Complaint SET ICDCode='K62.3' where ComplaintId= 141
UPDATE Complaint SET ICDCode='R15' where ComplaintId= 142
UPDATE Complaint SET ICDCode='' where ComplaintId= 143
UPDATE Complaint SET ICDCode='B54' where ComplaintId= 144
UPDATE Complaint SET ICDCode='D73.5' where ComplaintId= 145
UPDATE Complaint SET ICDCode='D73.3' where ComplaintId= 146
UPDATE Complaint SET ICDCode='D73.0' where ComplaintId= 147
UPDATE Complaint SET ICDCode='C94.7' where ComplaintId= 148
UPDATE Complaint SET ICDCode='C85.9' where ComplaintId= 149
UPDATE Complaint SET ICDCode='D46' where ComplaintId= 150
UPDATE Complaint SET ICDCode='D47.1' where ComplaintId= 151
UPDATE Complaint SET ICDCode='K70.3' where ComplaintId= 152
UPDATE Complaint SET ICDCode='I81' where ComplaintId= 153
UPDATE Complaint SET ICDCode='' where ComplaintId= 154
UPDATE Complaint SET ICDCode='K35' where ComplaintId= 155
UPDATE Complaint SET ICDCode='K36' where ComplaintId= 156
UPDATE Complaint SET ICDCode='K36' where ComplaintId= 157
UPDATE Complaint SET ICDCode='R10.4' where ComplaintId= 158
UPDATE Complaint SET ICDCode='K56.1' where ComplaintId= 159
UPDATE Complaint SET ICDCode='K35.1' where ComplaintId= 160
UPDATE Complaint SET ICDCode='K35.0' where ComplaintId= 161
UPDATE Complaint SET ICDCode='' where ComplaintId= 162
UPDATE Complaint SET ICDCode='D24' where ComplaintId= 163
UPDATE Complaint SET ICDCode='N60.2' where ComplaintId= 164
UPDATE Complaint SET ICDCode='D05.9' where ComplaintId= 165
UPDATE Complaint SET ICDCode='O91.1' where ComplaintId= 166
UPDATE Complaint SET ICDCode='O92.0' where ComplaintId= 167
UPDATE Complaint SET ICDCode='N60.8' where ComplaintId= 168
UPDATE Complaint SET ICDCode='N64.0' where ComplaintId= 169
UPDATE Complaint SET ICDCode='C50.3' where ComplaintId= 170
UPDATE Complaint SET ICDCode='O92.6' where ComplaintId= 171
UPDATE Complaint SET ICDCode='' where ComplaintId= 172
UPDATE Complaint SET ICDCode='E24' where ComplaintId= 173
UPDATE Complaint SET ICDCode='E27.2' where ComplaintId= 174
UPDATE Complaint SET ICDCode='E23.0' where ComplaintId= 175
UPDATE Complaint SET ICDCode='E05.8' where ComplaintId= 176
UPDATE Complaint SET ICDCode='D44.3' where ComplaintId= 177
UPDATE Complaint SET ICDCode='D35.2' where ComplaintId= 178
UPDATE Complaint SET ICDCode='C75.1' where ComplaintId= 179
UPDATE Complaint SET ICDCode='E23.2' where ComplaintId= 180
UPDATE Complaint SET ICDCode='' where ComplaintId= 181
UPDATE Complaint SET ICDCode='I83' where ComplaintId= 182
UPDATE Complaint SET ICDCode='I80.2' where ComplaintId= 183
UPDATE Complaint SET ICDCode='I73' where ComplaintId= 184
UPDATE Complaint SET ICDCode='I82' where ComplaintId= 185
UPDATE Complaint SET ICDCode='I73.8' where ComplaintId= 186
UPDATE Complaint SET ICDCode='R02' where ComplaintId= 187
UPDATE Complaint SET ICDCode='M31.1' where ComplaintId= 188
UPDATE Complaint SET ICDCode='L95.0' where ComplaintId= 189
UPDATE Complaint SET ICDCode='I73.1' where ComplaintId= 190
UPDATE Complaint SET ICDCode='I72.4' where ComplaintId= 191
UPDATE Complaint SET ICDCode='' where ComplaintId= 192
UPDATE Complaint SET ICDCode='D35.0' where ComplaintId= 194
UPDATE Complaint SET ICDCode='C75.1' where ComplaintId= 195
UPDATE Complaint SET ICDCode='E35.1*' where ComplaintId= 196
UPDATE Complaint SET ICDCode='D44.1' where ComplaintId= 197
UPDATE Complaint SET ICDCode='Q89.1' where ComplaintId= 198
UPDATE Complaint SET ICDCode='D35.0' where ComplaintId= 199
UPDATE Complaint SET ICDCode='' where ComplaintId= 200
UPDATE Complaint SET ICDCode='D15.0' where ComplaintId= 201
UPDATE Complaint SET ICDCode='E32.9' where ComplaintId= 202
UPDATE Complaint SET ICDCode='E32.8' where ComplaintId= 203
UPDATE Complaint SET ICDCode='C37' where ComplaintId= 204
UPDATE Complaint SET ICDCode='E32.0' where ComplaintId= 205
UPDATE Complaint SET ICDCode='' where ComplaintId= 207
UPDATE Complaint SET ICDCode='E03' where ComplaintId= 208
UPDATE Complaint SET ICDCode='E05' where ComplaintId= 209
UPDATE Complaint SET ICDCode='E20' where ComplaintId= 210
UPDATE Complaint SET ICDCode='E04' where ComplaintId= 212
UPDATE Complaint SET ICDCode='C73' where ComplaintId= 213
UPDATE Complaint SET ICDCode='E20.1' where ComplaintId= 215
UPDATE Complaint SET ICDCode='' where ComplaintId= 218
UPDATE Complaint SET ICDCode='E28.2' where ComplaintId= 219
UPDATE Complaint SET ICDCode='N83.0' where ComplaintId= 220
UPDATE Complaint SET ICDCode='N83.5' where ComplaintId= 221
UPDATE Complaint SET ICDCode='N97' where ComplaintId= 222
UPDATE Complaint SET ICDCode='N94.0' where ComplaintId= 223
UPDATE Complaint SET ICDCode='C56' where ComplaintId= 224
UPDATE Complaint SET ICDCode='A18.8+' where ComplaintId= 225
UPDATE Complaint SET ICDCode='' where ComplaintId= 226
UPDATE Complaint SET ICDCode='N43.0' where ComplaintId= 227
UPDATE Complaint SET ICDCode='N43.1' where ComplaintId= 228
UPDATE Complaint SET ICDCode='Q53' where ComplaintId= 229
UPDATE Complaint SET ICDCode='N45.0' where ComplaintId= 230
UPDATE Complaint SET ICDCode='S31.3' where ComplaintId= 231
UPDATE Complaint SET ICDCode='C62' where ComplaintId= 232
UPDATE Complaint SET ICDCode='N44' where ComplaintId= 233
UPDATE Complaint SET ICDCode='I86.1' where ComplaintId= 234
UPDATE Complaint SET ICDCode='A18.1+' where ComplaintId= 235
UPDATE Complaint SET ICDCode='' where ComplaintId= 236
UPDATE Complaint SET ICDCode='J04.0' where ComplaintId= 237
UPDATE Complaint SET ICDCode='J38.1' where ComplaintId= 238
UPDATE Complaint SET ICDCode='J38.2' where ComplaintId= 239
UPDATE Complaint SET ICDCode='J38.7' where ComplaintId= 240
UPDATE Complaint SET ICDCode='Q31.3' where ComplaintId= 241
UPDATE Complaint SET ICDCode='J38.0' where ComplaintId= 242
UPDATE Complaint SET ICDCode='J38.3' where ComplaintId= 243
UPDATE Complaint SET ICDCode='C32' where ComplaintId= 244
UPDATE Complaint SET ICDCode='' where ComplaintId= 245
UPDATE Complaint SET ICDCode='J45' where ComplaintId= 246
UPDATE Complaint SET ICDCode='J20' where ComplaintId= 247
UPDATE Complaint SET ICDCode='J41.0' where ComplaintId= 248
UPDATE Complaint SET ICDCode='J44.8' where ComplaintId= 249
UPDATE Complaint SET ICDCode='J47' where ComplaintId= 250
UPDATE Complaint SET ICDCode='J04.1' where ComplaintId= 251
UPDATE Complaint SET ICDCode='J18.0' where ComplaintId= 252
UPDATE Complaint SET ICDCode='D02.2' where ComplaintId= 253
UPDATE Complaint SET ICDCode='Q32.0' where ComplaintId= 254
UPDATE Complaint SET ICDCode='S27.50' where ComplaintId= 255
UPDATE Complaint SET ICDCode='J95.0' where ComplaintId= 256
UPDATE Complaint SET ICDCode='' where ComplaintId= 257
UPDATE Complaint SET ICDCode='J02' where ComplaintId= 259
UPDATE Complaint SET ICDCode='J31.2' where ComplaintId= 261
UPDATE Complaint SET ICDCode='J03' where ComplaintId= 262
UPDATE Complaint SET ICDCode='J35.0' where ComplaintId= 263
UPDATE Complaint SET ICDCode='J36' where ComplaintId= 264
UPDATE Complaint SET ICDCode='J35' where ComplaintId= 265
UPDATE Complaint SET ICDCode='J35.0' where ComplaintId= 266
UPDATE Complaint SET ICDCode='' where ComplaintId= 267
UPDATE Complaint SET ICDCode='J44' where ComplaintId= 268
UPDATE Complaint SET ICDCode='J18' where ComplaintId= 269
UPDATE Complaint SET ICDCode='A16.2' where ComplaintId= 270
UPDATE Complaint SET ICDCode='J90' where ComplaintId= 271
UPDATE Complaint SET ICDCode='J85.1' where ComplaintId= 272
UPDATE Complaint SET ICDCode='J47' where ComplaintId= 273
UPDATE Complaint SET ICDCode='I26' where ComplaintId= 274
UPDATE Complaint SET ICDCode='J93' where ComplaintId= 275
UPDATE Complaint SET ICDCode='I27.2' where ComplaintId= 276
UPDATE Complaint SET ICDCode='J60' where ComplaintId= 277
UPDATE Complaint SET ICDCode='' where ComplaintId= 278
UPDATE Complaint SET ICDCode='B00.0' where ComplaintId= 279
UPDATE Complaint SET ICDCode='L70' where ComplaintId= 280
UPDATE Complaint SET ICDCode='L01' where ComplaintId= 281
UPDATE Complaint SET ICDCode='B35.0' where ComplaintId= 282
UPDATE Complaint SET ICDCode='B37.2' where ComplaintId= 283
UPDATE Complaint SET ICDCode='A63.0' where ComplaintId= 284
UPDATE Complaint SET ICDCode='L40' where ComplaintId= 285
UPDATE Complaint SET ICDCode='L55' where ComplaintId= 286
UPDATE Complaint SET ICDCode='L80' where ComplaintId= 287
UPDATE Complaint SET ICDCode='L03' where ComplaintId= 288
UPDATE Complaint SET ICDCode='B37' where ComplaintId= 289
UPDATE Complaint SET ICDCode='B86' where ComplaintId= 290
UPDATE Complaint SET ICDCode='L81.8' where ComplaintId= 291
UPDATE Complaint SET ICDCode='' where ComplaintId= 292
UPDATE Complaint SET ICDCode='L63' where ComplaintId= 293
UPDATE Complaint SET ICDCode='L21' where ComplaintId= 294
UPDATE Complaint SET ICDCode='L68.0' where ComplaintId= 295
UPDATE Complaint SET ICDCode='B85.2' where ComplaintId= 296
UPDATE Complaint SET ICDCode='L21.0' where ComplaintId= 297
UPDATE Complaint SET ICDCode='' where ComplaintId= 298
UPDATE Complaint SET ICDCode='B37.2' where ComplaintId= 299
UPDATE Complaint SET ICDCode='B37.2' where ComplaintId= 300
UPDATE Complaint SET ICDCode='L60.8' where ComplaintId= 301
UPDATE Complaint SET ICDCode='L60.3' where ComplaintId= 302
UPDATE Complaint SET ICDCode='L60.8' where ComplaintId= 303
UPDATE Complaint SET ICDCode='L60.8' where ComplaintId= 304
UPDATE Complaint SET ICDCode='' where ComplaintId= 305
UPDATE Complaint SET ICDCode='I64' where ComplaintId= 306
UPDATE Complaint SET ICDCode='G90.0' where ComplaintId= 307
UPDATE Complaint SET ICDCode='G45.9' where ComplaintId= 308
UPDATE Complaint SET ICDCode='G40' where ComplaintId= 309
UPDATE Complaint SET ICDCode='F03' where ComplaintId= 310
UPDATE Complaint SET ICDCode='G20' where ComplaintId= 311
UPDATE Complaint SET ICDCode='' where ComplaintId= 312
UPDATE Complaint SET ICDCode='M54.5' where ComplaintId= 313
UPDATE Complaint SET ICDCode='M15.4*' where ComplaintId= 314
UPDATE Complaint SET ICDCode='M47.80' where ComplaintId= 315
UPDATE Complaint SET ICDCode='M47.80' where ComplaintId= 316
UPDATE Complaint SET ICDCode='M72.2' where ComplaintId= 317
UPDATE Complaint SET ICDCode='S23' where ComplaintId= 318
UPDATE Complaint SET ICDCode='M75.0' where ComplaintId= 319
UPDATE Complaint SET ICDCode='M81' where ComplaintId= 320
UPDATE Complaint SET ICDCode='M05' where ComplaintId= 321
UPDATE Complaint SET ICDCode='' where ComplaintId= 322
UPDATE Complaint SET ICDCode='R25.2' where ComplaintId= 323
UPDATE Complaint SET ICDCode='M62.9' where ComplaintId= 324
UPDATE Complaint SET ICDCode='M62.6' where ComplaintId= 325
UPDATE Complaint SET ICDCode='T09.5' where ComplaintId= 326
UPDATE Complaint SET ICDCode='M62.5' where ComplaintId= 327
UPDATE Complaint SET ICDCode='R53' where ComplaintId= 328
UPDATE Complaint SET ICDCode='M62.1' where ComplaintId= 329
UPDATE Complaint SET ICDCode='T14.5' where ComplaintId= 330
UPDATE Complaint SET ICDCode='M66.5' where ComplaintId= 331
UPDATE Complaint SET ICDCode='' where ComplaintId= 332
UPDATE Complaint SET ICDCode='I24.9' where ComplaintId= 333
UPDATE Complaint SET ICDCode='I01' where ComplaintId= 334
UPDATE Complaint SET ICDCode='I24.9' where ComplaintId= 335
UPDATE Complaint SET ICDCode='Q24.8' where ComplaintId= 336
UPDATE Complaint SET ICDCode='I31.3' where ComplaintId= 337
UPDATE Complaint SET ICDCode='I50.0' where ComplaintId= 338
UPDATE Complaint SET ICDCode='J81' where ComplaintId= 339
UPDATE Complaint SET ICDCode='I30' where ComplaintId= 340
UPDATE Complaint SET ICDCode='I42.0' where ComplaintId= 341
UPDATE Complaint SET ICDCode='I49' where ComplaintId= 342
UPDATE Complaint SET ICDCode='I38' where ComplaintId= 343
UPDATE Complaint SET ICDCode='Q21.1' where ComplaintId= 344
UPDATE Complaint SET ICDCode='Q21.0' where ComplaintId= 345
UPDATE Complaint SET ICDCode='Q21.3' where ComplaintId= 346
UPDATE Complaint SET ICDCode='I71' where ComplaintId= 347
UPDATE Complaint SET ICDCode='I33.0' where ComplaintId= 348
UPDATE Complaint SET ICDCode='' where ComplaintId= 349
UPDATE Complaint SET ICDCode='F33' where ComplaintId= 350
UPDATE Complaint SET ICDCode='F41.1' where ComplaintId= 351
UPDATE Complaint SET ICDCode='Z63.0' where ComplaintId= 352
UPDATE Complaint SET ICDCode='F20' where ComplaintId= 353
UPDATE Complaint SET ICDCode='F42' where ComplaintId= 354
UPDATE Complaint SET ICDCode='F29' where ComplaintId= 355
UPDATE Complaint SET ICDCode='F48' where ComplaintId= 356
UPDATE Complaint SET ICDCode='F50.0' where ComplaintId= 357
UPDATE Complaint SET ICDCode='F50.2' where ComplaintId= 358
UPDATE Complaint SET ICDCode='' where ComplaintId= 359
UPDATE Complaint SET ICDCode='B54' where ComplaintId= 360
UPDATE Complaint SET ICDCode='A01.0' where ComplaintId= 361
UPDATE Complaint SET ICDCode='J18' where ComplaintId= 362
UPDATE Complaint SET ICDCode='A92.0' where ComplaintId= 363
UPDATE Complaint SET ICDCode='B17.8' where ComplaintId= 364
UPDATE Complaint SET ICDCode='A16.2' where ComplaintId= 365
UPDATE Complaint SET ICDCode='A90' where ComplaintId= 366
UPDATE Complaint SET ICDCode='B05' where ComplaintId= 367
UPDATE Complaint SET ICDCode='B01' where ComplaintId= 368
UPDATE Complaint SET ICDCode='B00' where ComplaintId= 369
UPDATE Complaint SET ICDCode='I00' where ComplaintId= 370
UPDATE Complaint SET ICDCode='I33.0' where ComplaintId= 371
UPDATE Complaint SET ICDCode='' where ComplaintId= 372
UPDATE Complaint SET ICDCode='C50' where ComplaintId= 373
UPDATE Complaint SET ICDCode='C34' where ComplaintId= 374
UPDATE Complaint SET ICDCode='C20' where ComplaintId= 375
UPDATE Complaint SET ICDCode='C18' where ComplaintId= 376
UPDATE Complaint SET ICDCode='C73' where ComplaintId= 377
UPDATE Complaint SET ICDCode='C94.7' where ComplaintId= 378
UPDATE Complaint SET ICDCode='D03' where ComplaintId= 379
UPDATE Complaint SET ICDCode='C83' where ComplaintId= 380
UPDATE Complaint SET ICDCode='C25' where ComplaintId= 381
UPDATE Complaint SET ICDCode='C61' where ComplaintId= 382
UPDATE Complaint SET ICDCode='' where ComplaintId= 383
UPDATE Complaint SET ICDCode='G70.0' where ComplaintId= 384
UPDATE Complaint SET ICDCode='G35' where ComplaintId= 385
UPDATE Complaint SET ICDCode='G12' where ComplaintId= 386
UPDATE Complaint SET ICDCode='G71.0' where ComplaintId= 387
UPDATE Complaint SET ICDCode='G12.2' where ComplaintId= 388
UPDATE Complaint SET ICDCode='' where ComplaintId= 389
UPDATE Complaint SET ICDCode='E16.0' where ComplaintId= 390
UPDATE Complaint SET ICDCode='E11' where ComplaintId= 391
UPDATE Complaint SET ICDCode='E10' where ComplaintId= 392
UPDATE Complaint SET ICDCode='R73.0' where ComplaintId= 393
UPDATE Complaint SET ICDCode='O24' where ComplaintId= 394
UPDATE Complaint SET ICDCode='H36.0*' where ComplaintId= 395
UPDATE Complaint SET ICDCode='N08.3*' where ComplaintId= 396
UPDATE Complaint SET ICDCode='G63.2*' where ComplaintId= 397
UPDATE Complaint SET ICDCode='E10.5' where ComplaintId= 398
UPDATE Complaint SET ICDCode='E11.1' where ComplaintId= 399
UPDATE Complaint SET ICDCode='E10.0' where ComplaintId= 400
UPDATE Complaint SET ICDCode='E14.0' where ComplaintId= 401
UPDATE Complaint SET ICDCode='' where ComplaintId= 402
UPDATE Complaint SET ICDCode='I10' where ComplaintId= 403
UPDATE Complaint SET ICDCode='O13' where ComplaintId= 404
UPDATE Complaint SET ICDCode='R03.0' where ComplaintId= 405
UPDATE Complaint SET ICDCode='I67.4' where ComplaintId= 406
UPDATE Complaint SET ICDCode='I15.9' where ComplaintId= 407
UPDATE Complaint SET ICDCode='I15.0' where ComplaintId= 408
UPDATE Complaint SET ICDCode='' where ComplaintId= 409
UPDATE Complaint SET ICDCode='E78.0' where ComplaintId= 410
UPDATE Complaint SET ICDCode='E78.2' where ComplaintId= 411
UPDATE Complaint SET ICDCode='E78.1' where ComplaintId= 412
UPDATE Complaint SET ICDCode='E78.4' where ComplaintId= 413
UPDATE Complaint SET ICDCode='' where ComplaintId= 414
UPDATE Complaint SET ICDCode='A60.0' where ComplaintId= 415
UPDATE Complaint SET ICDCode='N47' where ComplaintId= 416
UPDATE Complaint SET ICDCode='B37.9' where ComplaintId= 417
UPDATE Complaint SET ICDCode='N48.1' where ComplaintId= 418
UPDATE Complaint SET ICDCode='A57' where ComplaintId= 419
UPDATE Complaint SET ICDCode='S38.0' where ComplaintId= 420
UPDATE Complaint SET ICDCode='F52.2' where ComplaintId= 421
UPDATE Complaint SET ICDCode='C60' where ComplaintId= 422
UPDATE Complaint SET ICDCode='N48.3' where ComplaintId= 423
UPDATE Complaint SET ICDCode='' where ComplaintId= 425
UPDATE Complaint SET ICDCode='B37.3+' where ComplaintId= 426
UPDATE Complaint SET ICDCode='A60.0' where ComplaintId= 427
UPDATE Complaint SET ICDCode='N89.8' where ComplaintId= 428
UPDATE Complaint SET ICDCode='S38.0' where ComplaintId= 429
UPDATE Complaint SET ICDCode='A57' where ComplaintId= 430
UPDATE Complaint SET ICDCode='F52.6' where ComplaintId= 431
UPDATE Complaint SET ICDCode='' where ComplaintId= 432
UPDATE Complaint SET ICDCode='T14.9' where ComplaintId= 433
UPDATE Complaint SET ICDCode='X29' where ComplaintId= 434
UPDATE Complaint SET ICDCode='X48' where ComplaintId= 435
UPDATE Complaint SET ICDCode='T29' where ComplaintId= 436
UPDATE Complaint SET ICDCode='F07.2' where ComplaintId= 437
UPDATE Complaint SET ICDCode='I64' where ComplaintId= 438
UPDATE Complaint SET ICDCode='' where ComplaintId= 439
UPDATE Complaint SET ICDCode='E66' where ComplaintId= 440
UPDATE Complaint SET ICDCode='E53' where ComplaintId= 442
UPDATE Complaint SET ICDCode='E61.8' where ComplaintId= 443
UPDATE Complaint SET ICDCode='F50' where ComplaintId= 444
UPDATE Complaint SET ICDCode='E44' where ComplaintId= 445
UPDATE Complaint SET ICDCode='' where ComplaintId= 446
UPDATE Complaint SET ICDCode='N94.5' where ComplaintId= 447
UPDATE Complaint SET ICDCode='N89.8' where ComplaintId= 448
UPDATE Complaint SET ICDCode='N95.0' where ComplaintId= 449
UPDATE Complaint SET ICDCode='N92.1' where ComplaintId= 450
UPDATE Complaint SET ICDCode='B37.3+' where ComplaintId= 451
UPDATE Complaint SET ICDCode='F52.6' where ComplaintId= 452
UPDATE Complaint SET ICDCode='N97' where ComplaintId= 453
UPDATE Complaint SET ICDCode='' where ComplaintId= 454
UPDATE Complaint SET ICDCode='N43' where ComplaintId= 455
UPDATE Complaint SET ICDCode='F52.2' where ComplaintId= 456
UPDATE Complaint SET ICDCode='I86.1' where ComplaintId= 457
UPDATE Complaint SET ICDCode='N46' where ComplaintId= 458
UPDATE Complaint SET ICDCode='N46' where ComplaintId= 459
UPDATE Complaint SET ICDCode='C62' where ComplaintId= 460
UPDATE Complaint SET ICDCode='C60' where ComplaintId= 461
UPDATE Complaint SET ICDCode='Q53' where ComplaintId= 462
UPDATE Complaint SET ICDCode='N50.1' where ComplaintId= 463
UPDATE Complaint SET ICDCode='' where ComplaintId= 464
UPDATE Complaint SET ICDCode='D64.8' where ComplaintId= 465
UPDATE Complaint SET ICDCode='D69.5' where ComplaintId= 466
UPDATE Complaint SET ICDCode='D61.0' where ComplaintId= 467
UPDATE Complaint SET ICDCode='C94.7' where ComplaintId= 468
UPDATE Complaint SET ICDCode='D45' where ComplaintId= 469
UPDATE Complaint SET ICDCode='' where ComplaintId= 470
UPDATE Complaint SET ICDCode='J06.9' where ComplaintId= 471
UPDATE Complaint SET ICDCode='J01.0' where ComplaintId= 472
UPDATE Complaint SET ICDCode='J01.2' where ComplaintId= 473
UPDATE Complaint SET ICDCode='L70.8' where ComplaintId= 474
UPDATE Complaint SET ICDCode='R04.0' where ComplaintId= 475
UPDATE Complaint SET ICDCode='J34' where ComplaintId= 476
UPDATE Complaint SET ICDCode='J30.2' where ComplaintId= 477
UPDATE Complaint SET ICDCode='T17.1' where ComplaintId= 478
UPDATE Complaint SET ICDCode='J33.0' where ComplaintId= 479
UPDATE Complaint SET ICDCode='J33.0' where ComplaintId= 480
UPDATE Complaint SET ICDCode='J34.2' where ComplaintId= 481
UPDATE Complaint SET ICDCode='J34.3' where ComplaintId= 482
UPDATE Complaint SET ICDCode='L71.1' where ComplaintId= 483
UPDATE Complaint SET ICDCode='S00.3' where ComplaintId= 484
UPDATE Complaint SET ICDCode='S01.2' where ComplaintId= 485
UPDATE Complaint SET ICDCode='S01.2' where ComplaintId= 486
UPDATE Complaint SET ICDCode='' where ComplaintId= 487
UPDATE Complaint SET ICDCode='H61.2' where ComplaintId= 488
UPDATE Complaint SET ICDCode='H60' where ComplaintId= 489
UPDATE Complaint SET ICDCode='H65' where ComplaintId= 490
UPDATE Complaint SET ICDCode='H91.9' where ComplaintId= 491
UPDATE Complaint SET ICDCode='H81' where ComplaintId= 492
UPDATE Complaint SET ICDCode='H60.3' where ComplaintId= 493
UPDATE Complaint SET ICDCode='S00.4' where ComplaintId= 494
UPDATE Complaint SET ICDCode='S09.9' where ComplaintId= 495
UPDATE Complaint SET ICDCode='S09.9' where ComplaintId= 496
UPDATE Complaint SET ICDCode='S09.9' where ComplaintId= 497
UPDATE Complaint SET ICDCode='T16' where ComplaintId= 498
UPDATE Complaint SET ICDCode='X23' where ComplaintId= 499
UPDATE Complaint SET ICDCode='X23' where ComplaintId= 500
UPDATE Complaint SET ICDCode='' where ComplaintId= 501
UPDATE Complaint SET ICDCode='K12' where ComplaintId= 502
UPDATE Complaint SET ICDCode='K12' where ComplaintId= 503
UPDATE Complaint SET ICDCode='Q36' where ComplaintId= 504
UPDATE Complaint SET ICDCode='S00.5' where ComplaintId= 505
UPDATE Complaint SET ICDCode='S00.5' where ComplaintId= 506
UPDATE Complaint SET ICDCode='' where ComplaintId= 507
UPDATE Complaint SET ICDCode='K11.2' where ComplaintId= 508
UPDATE Complaint SET ICDCode='K11.2' where ComplaintId= 509
UPDATE Complaint SET ICDCode='K11.5' where ComplaintId= 510
UPDATE Complaint SET ICDCode='' where ComplaintId= 511
UPDATE Complaint SET ICDCode='K05.0' where ComplaintId= 512
UPDATE Complaint SET ICDCode='B00.2' where ComplaintId= 513
UPDATE Complaint SET ICDCode='' where ComplaintId= 514
UPDATE Complaint SET ICDCode='G50.1' where ComplaintId= 515
UPDATE Complaint SET ICDCode='K07.6' where ComplaintId= 516
UPDATE Complaint SET ICDCode='' where ComplaintId= 517
UPDATE Complaint SET ICDCode='K14.0' where ComplaintId= 518
UPDATE Complaint SET ICDCode='Q38.3' where ComplaintId= 519
UPDATE Complaint SET ICDCode='Q38.2' where ComplaintId= 520
UPDATE Complaint SET ICDCode='Q38.1' where ComplaintId= 521
UPDATE Complaint SET ICDCode='K13.2' where ComplaintId= 522
UPDATE Complaint SET ICDCode='R43' where ComplaintId= 523
UPDATE Complaint SET ICDCode='S05.0' where ComplaintId= 524
UPDATE Complaint SET ICDCode='K09.8' where ComplaintId= 525
UPDATE Complaint SET ICDCode='A18.1+' where ComplaintId= 526
UPDATE Complaint SET ICDCode='N34.0' where ComplaintId= 527
UPDATE Complaint SET ICDCode='N93' where ComplaintId= 528
UPDATE Complaint SET ICDCode='I21' where ComplaintId= 530
UPDATE Complaint SET ICDCode='J96.0' where ComplaintId= 531
UPDATE Complaint SET ICDCode='W74' where ComplaintId= 532
UPDATE Complaint SET ICDCode='R79.8' where ComplaintId= 533
UPDATE Complaint SET ICDCode='Z32.1' where ComplaintId= 534
UPDATE Complaint SET ICDCode='A94' where ComplaintId= 535

