//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attune.Document.Scanner.ServiceDocumentScanner {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDocumentScanner.DocumentScannerSoap")]
    public interface DocumentScannerSoap {
        
        // CODEGEN: Parameter 'bytes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Attune.Document.Scanner.ServiceDocumentScanner.UploadFileResponse UploadFile(Attune.Document.Scanner.ServiceDocumentScanner.UploadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bytes;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(string fileName, byte[] bytes) {
            this.fileName = fileName;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentScannerSoapChannel : Attune.Document.Scanner.ServiceDocumentScanner.DocumentScannerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentScannerSoapClient : System.ServiceModel.ClientBase<Attune.Document.Scanner.ServiceDocumentScanner.DocumentScannerSoap>, Attune.Document.Scanner.ServiceDocumentScanner.DocumentScannerSoap {
        
        public DocumentScannerSoapClient() {
        }
        
        public DocumentScannerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentScannerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentScannerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentScannerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Attune.Document.Scanner.ServiceDocumentScanner.UploadFileResponse Attune.Document.Scanner.ServiceDocumentScanner.DocumentScannerSoap.UploadFile(Attune.Document.Scanner.ServiceDocumentScanner.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string fileName, byte[] bytes) {
            Attune.Document.Scanner.ServiceDocumentScanner.UploadFileRequest inValue = new Attune.Document.Scanner.ServiceDocumentScanner.UploadFileRequest();
            inValue.fileName = fileName;
            inValue.bytes = bytes;
            Attune.Document.Scanner.ServiceDocumentScanner.UploadFileResponse retVal = ((Attune.Document.Scanner.ServiceDocumentScanner.DocumentScannerSoap)(this)).UploadFile(inValue);
        }
    }
}
