delete from InvestigationOrgMapping where OrgID =15
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4426,15,Null,Null,'Normal 10 to 25; Children (1-8 Years) 0 to 3')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4720,15,Null,Null,'Females Follicular: 0.1 - 0.8, Luteal: 0.6 - 2.3, Ovulation: 0.3 - 1.4, Third trimester: 2.0 - 12, Post menopausal: 0.13 - 0.51, Pre pubertal: 0 - 0.6, 1 month - 1 year : 1.06 - 40.41, 1 Year - 13 Year: 0.07 - 1.7, Male: 0.5 – 2.21')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4878,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4039,15,Null,Null,'100 To 240 mg/24 h')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4879,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4428,15,Null,Null,'50 - 200 mcg')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4144,15,301,Null,'90 - 139 ml/minute')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4425,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4015,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4880,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4015,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4881,15,Null,Null,'10 to 40 mg/24 h')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4038,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4145,15,Null,Null,'10 to 100 mg/24 h')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4037,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4882,15,Null,Null,'250 to 750 mg/24 h')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4041,15,Null,Null,'< 15 mg/24 h')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4438,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4721,15,Null,Null,'400 - 1300 mg/24 h')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4883,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4152,15,Null,Null,'SUSPECT: 30 U/L to 40 U/L, STRONG SUSPECT: > 40 U/L to 60 U/L, POSITIVE: > 60 U/L, Normal: < 30 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4884,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4885,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2011,15,Null,Null,'40 to 440 Cells/cumm')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4723,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4887,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4728,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4733,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4169,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3116,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4172,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4889,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4324,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4191,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4173,15,Null,Null,'Negative < 23')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4174,15,Null,Null,'Negative < 15')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4175,15,Null,Null,'UPTO 6.25 U/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4890,15,Null,Null,'NEGATIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4265,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4891,15,Null,Null,'NEGATIVE : < 9, GREY ZONE : 9 - 11, POSITIVE : > 11')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4892,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4772,15,Null,Null,'HIGH POSITIVE: > 200 IU/ML, NEGATIVE: < 25 IU/ML, LOW POSITIVE: 30 - 60 IU/ML, BORDER LINE POSITIVE: 25 - 30 IU/ML, POSITIVE: 60 - 200 IU/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4177,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4790,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4322,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4323,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4128,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4896,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4897,15,Null,Null,'NON REACTIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4898,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5567,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4363,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4087,15,Null,Null,'< 5 NEGATIVE; 5 - 9 EQUIVOCAL; > 9 POSITIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4088,15,Null,Null,'< 9 Negative 10 - 11 Equivocal > 11 Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4363,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4192,15,Null,Null,'< 40 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4097,15,Null,Null,'POSITIVE: > 1.4 ANA INDEX 0.2 . NEGATIVE: < 1.0 . BORDERLINE: 1.0 to 1.4')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4899,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4185,15,Null,Null,'Eleveted > 10 Normal < 8')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4186,15,Null,Null,'Eleveted > 10 Normal < 9')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4900,15,Null,Null,'NEGATIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4190,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4091,15,Null,Null,'< 200 IU/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4840,15,Null,Null,'NEGATIVE: < 200 U/ML, BORDERLINE: NEGATIVE 201 - 300 U/ML, POSITIVE: 301 - 350 U/ML, POSITIVE: > 350 U/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4841,15,Null,Null,'NEGATIVE: < 400 U/ML, LOW POSITIVE: 400 U/ML TO 900 U/ML, POSITIVE: > 900 U/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4842,15,Null,Null,'NEGATIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4071,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2048,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4191,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4901,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4197,15,Null,Null,'80.0 to 155.0 Mg/dl')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4902,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4903,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4903,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4904,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4905,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4232,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4906,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4907,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4908,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4204,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4909,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4910,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4080,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2043,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4167,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4911,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4208,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4272,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4252,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4912,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4352,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4913,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4914,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4814,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4412,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4916,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4917,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4093,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2031,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4781,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3013,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4783,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3018,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4753,15,Null,Null,'5 to 25 Mgm%')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4080,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)

--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4220,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4920,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4921,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4624,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4232,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4922,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4923,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4622,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4924,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4080,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3073,15,Null,Null,'< 35 U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4757,15,Null,Null,'99% of healthy subjects < 5 99% of smokers up to 10 93% 0 to 3')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4229,15,Null,Null,'Total Leukocyte count Cells/c.mm Normal Range : 4000 to 10,000 Cells/ c. Normal Range 1,500 to 4,000 Cells /c.mm Normal Range 2,000 to 7,500 Cells / c.m Normal Range 30 to 60 Normal Range 500 to 1800 Cells /c.mm Lymphocyte percentge % Noramal Range 20 to 45 % Granulocyte percent % Normal Range 40 to 75 %')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4925,15,Null,Null,'Normal: 600 to 2000 cells/microl, Normal: 1.0 to 3.6, Normal: 40 to 75% CD8 percentage % Normal: 20 to 45 % Absolute CD8 count Cells/Cumm, Normal: 1.5 to 2.6 % CD 8 Cells/microl Normal: 300 to 1150 cells /microl CD4% Absolute Lymphocyte Count Cells/Cumm, Normal: 250 to 900 Cells/cumm')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4230,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3074,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4232,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4232,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4392,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4232,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4926,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4927,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4241,15,Null,Null,'Normal (within 1 hour), More than 1 hour')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2045,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4928,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4246,15,Null,Null,'90 to 180 Mg/dl (Related to age, Geographical & Methodological differences)')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4247,15,Null,Null,'10 to 40 Mg/dl (Related to age,Geographical & Methodological differences)')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4929,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4930,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3095,15,Null,Null,'Male - 5.0 to 22.0 Micro g/dl, Female - 5.2 to 21.7 Micro g/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4931,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4932,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2046,15,Null,Null,'NEGATIVE < 250 Ng/ml, POSITIVE > 250 Ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3114,15,Null,Null,'WOMEN Micro g/ml, MEN Micro g/ml, New borns 0.9 - 1.8 0.9 - 1.8, Before puberty 0.25 - 1.0 0.25 - 1.0, Adults 0.9 - 3.6 0.9 - 3.6, After menopause < 0.25 - 1.0, Pregnancy 0.25 – 1.8')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4461,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4150,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3031,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4468,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4934,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4935,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4936,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2013,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4464,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(4277,15,Null,Null,'N')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4277,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(4500,15,Null,Null,'N')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4277,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4937,15,Null,Null,'< 200 – NEGATIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4938,15,Null,Null)

--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4342,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3119,15,Null,Null,'Adult: <60 pg/ml, Post menopausal : <18 pg/ml, Ovulating, early follicular:30 - 100 pg/ml, Late follicular:100 - 400 Pg/ml, Pregnant normal :upto 35,000 pg/ml, Luteal phase :60-150 Pg /ml, Prepubertal children normal:>10 pg/ml, ADULT MALE : < 60 pg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4939,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4284,15,Null,Null,'0.9 to 2.0 g/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4289,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4775,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3122,15,Null,Null,'Adult Males: 0.7 to 11.1 mIU/mL b)Adult Females, i. Ovulatory Cycles Follicular Phase(2-3days): 3.0 to 14.4 mIU/mL, Mid Cycle: 5.8 to 21.0 mIU/mL, Luteal Phase: 1.2 to 9.0 mIU/mL ii. Post Menopausal: 21.7 to 153 mIU/mL iii. Oral Contraceptives: Not Detectable to 4.9 mIU/mL')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3062,15,Null,Null,'3 to 17 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4777,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4778,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4844,15,Null,Null,'Male: 31.0 - 94.0 pmol/L, Female: 3.0 - 13.0 pmol/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4941,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3016,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3061,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4942,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3011,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3014,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3090,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4787,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2041,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4130,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4133,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4130,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3014,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4086,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4334,15,Null,Null,'Normal Range : < 40 Negative : > 40 Positive')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4335,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3117,15,Null,Null,'MALE : 0.1 - 1.0 ng/ml, FEMALE FOLLICULAR PHASE : 0.2 - 1.4 ng/ml, LUTEAL PHASE : 4.0 - 25 ng/ml, MIDCYCLE: 25 - 50 ng/ml, MENOPAUSE : 0.1 - 1.0 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4282,15,Null,Null,'Males : < 0.4 ng/ml, Non Pregnant Females : < 0.05 ng/ml, Pregnant Females : 18 - 21 weeks : 0.87 - 2.97 ng/ml 22 - 27 weeks : 1.01 - 3.87 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4943,15,Null,Null,'NEGATIVE: < 0.9, EQUIOVOCAL: 0.91 to 1.10, POSITIVE; > 1.10')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4944,15,Null,Null,'NEGATIVE: < 25 EIU/ML, POSITIVE: > 35 EIU/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4945,15,Null,Null,'EQUVOCAL: 0.91 to 1.10, NEGATIVE: < 0.9, POSITIVE: > 1.10')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4946,15,Null,Null,'NEGATIVE: < 25 EIU/ML, POSITIVE: > 35 EIU/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4947,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4067,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4343,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4344,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4948,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4349,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4339,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4949,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4950,15,Null,Null)


--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4360,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4360,15,Null,Null,'NORMAL 32 to 44 SECONDS')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3123,15,Null,Null,'a) Adult Males: 0.8 to 7.6 mIU/mL b) Adult Females (i) Ovulatory Cycles Follicular Phase : 1.1 to 11.6 mIU/mL, Mid Cycle: 17 to 77 mIU/mL, Luteal Phase: Not Detectable to 14.7 mIU/mL Perimenstrual: Not Detectable to 12.0 mIU/mL (ii) Post Menopausal: 11.3 to 39.8 mIU/mL (iii) Oral Contraceptives: Not Detectable to 8.0 mIU/mL')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3009,15,Null,Null,'1.60 to 2.6 Mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4951,15,Null,Null,'NEGATIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4952,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2055,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4361,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4953,15,Null,Null,'Negative: < 9 U/ML, Equivocal: 10 - 11 U/ML, Positive: > 11 U/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4954,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4955,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4365,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4956,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4957,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4958,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4959,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4464,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4960,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4380,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2014,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4389,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4961,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4962,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4963,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4964,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4965,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4290,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4872,15,Null,Null,'INR THERAPEUTIC LEVEL Myocardial infarction: 2.0 to 3.0 INR, Deep vein thrombosis: 2.0 to 3.0 INR, Pulmonary embolism: 2.0 to 3.0, Artificial cardiac valve: 3.0 to 4.5, Recur.systamic embolism: 3.0 to 4.5')

--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4966,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4967,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4730,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4968,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4080,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4969,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4970,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3117,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4821,15,Null,Null,'Adult Males: 2.5 to 17 ng/mL, Adult Females: 1.9 to 25 ng/mL')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3072,15,Null,Null,'Men 40-49 - <2.5 ng/ml, Men 50-59 - <3.5 ng/ml, Men 60-69 - <4.5 ng/ml, Men 70-79 -<6.5 ng/ml, Based on a previously normal PSA OF<4.0')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4402,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4972,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
----Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4080,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4973,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4974,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4975,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2012,15,Null,Null,'0.5 - 2.0 %')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2040,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4829,15,Null,Null,'< 20.0 IU/ml (WHO)')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4976,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4831,15,Null,Null,'Negative: < 30 EIU/ml, Positive: > 40 EIU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4832,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4977,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4978,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4979,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4980,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4408,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4298,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4981,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4982,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4342,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4726,15,Null,Null,'Reference Value: 0 - 46 pg/ml; Normal 6 to 56.7 pg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3039,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4983,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4725,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4984,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4732,15,Null,Null,'Adult: 60 to 170 U/L, Children: 151 to 471 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4734,15,Null,Null,'< 10 IU/Ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4735,15,Null,Null,'< 90 Units/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4172,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4128,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4750,15,Null,Null,'Normal Range: < 5.0 mIU/ml, Pregnancy Range: 1st week - 5.0 to 50 mIU/ml, 2nd weeks - 40 to 200 mIU/ml, 3rd weeks - 100 to 500 mIU/ml, 4th weeks - 700 to 1,000 mIU/ml, 2-3 months - 12000 to 2,00000 mIU/ml, 2nd trimester - 24000 to 55,000 mIU/ml, 3rd trimester - 6000 to 48,000 mIU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4752,15,Null,Null,'NORMAL(VENOUS BLOOD) ADULT: 22 - 26 Meq/L, INFANT: 19 - 24 Meq/L')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3020,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4223,15,Null,Null,'5.5 Mg/dl Normal range, Adult: up to 0.6 Mg/dl, Newborn: up to 3 weeks < .41 Mg/dl, Infant and children :<.28 Mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4985,15,Null,Null,'1.0 to 3.0 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4986,15,Null,Null,'5.0 - 12.0 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3007,15,Null,Null,'8.5 to 10.5 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4233,15,Null,Null,'15 - 60 Mgms %')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4758,15,Null,Null,'95 to 106 Meq/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4759,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4239,15,Null,Null,'4659 TO 14443 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4987,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4249,15,Null,Null,'Male :80 - 140 Micro g/dL, Childrens up to 10Yrs Serum Copper 134.0 Micro g/dl, Female: 80 - 155 Micro g/dL, New borns: 12 - 67 Micro g/dL :30 - 150 Micro g/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4765,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3048,15,Null,Null,'MEN: 24 to 195 U/L, WOMEN: 24 to 170 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3049,15,Null,Null,'UPTO 24 U/L')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3019,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4254,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4409,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3066,15,Null,Null,'15 - 240 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4989,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4990,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4388,15,Null,Null,'Normal : 11.1 to 79.5 pg /ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4780,15,Null,Null,'WOMEN: 7 - 32 U/L, MEN: 11 - 50 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4796,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4991,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4313,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4992,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4335,15,Null,Null,'NORMAL : 5 TO 15 micro mol/L, Mild HYPER HOMOCYSTENIMIA: 15 to 25 micro mol/L, Moderate HYPER HOMOCYSTENIMIA: 25 to 50 micro mol/L, Severe HYPER HOMOCYSTENIMIA: More than 50 micro mol/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4993,15,Null,Null,'Children: < 12 yrs: < 10 mIu/ml, ADULT(NOMAL): 0.7 to 9.0 mIu/ml, DIABETIC (TYPE II): 0.7 to 25.0 mIu/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3069,15,Null,Null,'MALE : 60 TO 160 Micro g/dl, FEMALE : 35 TO 145 Micro g/dl, NEONATES : 150 TO 220 Micro g/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4845,15,Null,Null,'250 - 400 ug/l')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4804,15,Null,Null,'200 - 400 Units/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4805,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3070,15,Null,Null,'< 60 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4994,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4467,15,Null,Null,'< 30 Mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4357,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4410,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4394,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3008,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4820,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4826,15,Null,Null,'FEMALE: 55 TO 125 %, MALE: 77 TO 143 %')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4825,15,Null,Null,'70 TO 140%')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3040,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3041,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4836,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3057,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3032,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3067,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4282,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3064,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4995,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4996,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4997,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4998,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4999,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5000,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4022,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3024,15,Null,Null,'20 TO 60 Meq/l')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4401,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4024,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5001,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4415,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4416,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4417,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5002,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5003,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5004,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5005,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4419,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4368,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4816,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3130,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5006,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4813,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4312,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5007,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4782,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5008,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5009,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4080,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4843,15,Null,Null,'MALE: Prepubertal (Late)0.1 - 0.2 ng/ml, ADULT: 3.0 - 10.0 ng/ml, FEMALE: Prepubertal (Late) 0.1 - 0.2 ng/ml, Follicular Phase 0.2 -0.8 ng/ml, Luteal Phase 0.2 - 0.8 ng/ml, Post Menopausal 0.08 -0.35 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5010,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4423,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4784,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4855,15,Null,Null,'Expected Values for Adults: 0.4 - 4 Micro IU/mL')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3082,15,Null,Null,'0.6 to 2.3 ng/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5012,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5013,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4876,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(1009,15,Null,Null,'<0.90 - NEGATIVE 0.91 to 1.10 - EQUIVOCAL >1.1 – POSITIVE')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4080,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4424,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3080,15,Null,Null,'1.4 to 4.2 Pg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5014,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4853,15,Null,Null,'< 1.0 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(14,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5015,15,Null,Null)

--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4156,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4017,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4014,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5016,15,Null,Null,'< 95 Units/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4432,15,Null,Null,'NEGATIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5017,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5018,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5019,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3026,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4435,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4430,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4080,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5021,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5022,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4427,15,Null,Null,'Normal Range : <5.0 IU/ml, Pregnancy Range: 1st week - 5.0 to 50 IU/ml, 2nd weeks - 40 to 200 IU/ml, 3rd weeks - 100 to 500 IU/ml, 4th weeks - 700 to 1,000 IU/ml, 2-3 months - 12000 to 2,00000 IU/ml, 2nd trimester - 24000 to 55,000 IU/ml, 3rd trimester - 6000 to 48,000 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5023,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5024,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5025,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4436,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5026,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5027,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4441,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5028,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5029,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5030,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4625,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5031,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4015,15,301,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4442,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4442,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4445,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4449,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5032,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5033,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5034,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4452,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4007,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3027,15,Null,Null,'250 to 900 Mosm/Kg')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3025,15,Null,Null,'10 TO 30 Meq/l')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5035,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3024,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4005,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4016,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4016,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4453,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5036,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5037,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5038,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5039,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5040,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4458,15,Null,Null,'Normal Range: 180 to 900, Indeterminate: 130 to 180, Deficiency: 0 to 130')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4461,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4333,15,Null,Null,'NEGATIVE')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3113,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4464,15,Null,Null)


--Newly added after pattern 
 Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2018,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2019,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2024,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2025,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2026,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2028,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2029,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2030,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3035,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3037,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3038,15,Null,Null)


Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4727,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2051,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4460,15,Null,Null)


Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4110,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4116,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4118,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4119,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4120,15,Null,Null)


Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5043,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5044,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5045,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5046,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5047,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5048,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5049,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5050,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5051,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5052,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5053,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5054,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5055,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5056,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5057,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5058,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5059,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5060,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4801,15,Null,Null,'100 - 530 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4344,15,Null,Null,'NORMAL: 55 - 300 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4342,15,Null,Null,'NORMAL: Children :1 to 10 Yrs 0 to 28 I ADULTS: UP TO 14 IU/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5064,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4343,15,Null,Null,'NORMAL: 800 - 1815 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5066,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5067,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5068,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5069,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4740,15,Null,Null,'NORMAL RANGE: < 15 NEGATIVE > 15 POSITIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4739,15,Null,Null,'NORMAL RANGE: < 15 NEGATIVE > 15 POSITIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5072,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4766,15,Null,Null,'Negative : < 40 EIU/ml, Positive : > 50 EIU/ml')

--After doubt
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5074,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5075,15,Null,Null)

--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5076,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5077,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2005,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2007,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2008,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2006,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4055,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2009,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4193,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4194,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5080,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4819,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4196,15,Null,Null,'110.0 to 190.0 Mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4018,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4019,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4004,15,Null,Null)
--BUG FIXING
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5041,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5081,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5082,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5083,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3132,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3133,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3134,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3135,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4132,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4742,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4129,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4135,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5085,15,Null,Null)
--Biopsy
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5092,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5093,15,Null,Null)

--New inves
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5157,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5158,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5159,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5160,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5161,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5162,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5163,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5164,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5165,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5166,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5167,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5168,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5169,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5171,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5172,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5173,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5174,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5175,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5177,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5178,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5179,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5180,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5181,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5182,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5183,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5184,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5185,15,Null,Null,'UP TO 4.7 IU/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5186,15,Null,Null,'UP TO 1.6 IU/L')

--Bug Tracking 5
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4178,15,Null,Null,'NON REACTIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4863,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4450,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4336,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5187,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5188,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5189,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3136,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(1008,15,Null,Null,'NEGATIVE : <30 EIU/ML, POSITIVE : <40 EIU/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4797,15,Null,Null,'HSV I – Negative: < 25 EIU/ml Positive: > 35 EIU/ml HSV II – Negative: < 25 EIU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4798,15,Null,Null)
--Imaging
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5190,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(4513,15,Null,Null,'N')

--newly added after readiness
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5192,15,Null,Null)
--Culture for ear
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5193,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5194,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5195,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4789,15,Null,Null,'4.8 to 6.0 %')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5196,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4830,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4859,15,Null,Null)

---Imaging
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5197,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(4523,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5199,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5200,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5201,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5202,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5203,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5204,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5205,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5206,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5207,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5208,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5209,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5210,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5211,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5212,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5213,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5214,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5215,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5216,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5217,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5218,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5219,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5220,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5221,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5222,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5223,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5224,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5225,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5226,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5227,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5228,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5229,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5230,15,Null,Null,'N')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5230,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5231,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5232,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5233,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5234,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5235,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5236,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5237,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5238,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5239,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5240,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5241,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5242,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5243,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5244,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5245,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5246,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5247,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5248,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5249,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5250,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5251,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5252,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5253,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5254,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5255,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5256,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5257,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5258,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5259,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5260,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5261,15,Null,Null,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(5262,15,Null,Null,'N')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5263,15,Null,Null)
--Bugtracker 6
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5288,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5289,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4089,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2033,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4810,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4811,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4031,15,Null,Null)
--Mrg
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5290,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5291,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5292,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4391,15,Null,Null)

--Bugtrracker 7
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5299,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5300,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5302,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5303,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5304,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5305,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5306,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5307,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5308,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5309,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5310,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5311,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5312,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5313,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5314,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5315,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5316,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4084,15,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4085,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4918,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4919,15,Null,Null)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4626,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5568,15,Null,Null,'Negative: < 0.9, Indeterminate: 0.9 - 1.1, Positive:  > 1.1')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5569,15,Null,Null,'NON REACTIVE')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5570,15,Null,Null,'EQUIVOCAL: 14 to 20 U/ml, NEGATIVE: < 14 U/ml, POSITIVE: > 20 U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5571,15,Null,Null,'Positive: > 40 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4226,15,Null,Null,'Male: < 5.0 pg/ml, Female: < 8.4 pg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4358,15,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4861,15,Null,Null,'0 to 20 mg/l')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5572,15,Null,Null,'Expected Values for Adults: 81 - 178 ng/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5573,15,Null,Null,'Expected Values for Adults: 4.5 - 12.5 microg/dL')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5574,15,Null,Null,'< 30 Mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4767,15,Null,Null,'NEGATIVE: < 80 EU/ML, EQUIVOCAL: 80 TO 100 EU/ML, POSITIVE: > 100 EU/ML')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(5575,15,Null,Null,'Premature infant: 1 to 5 mg/l, Child(1 - 12 years): 3 to 9 mg/l, Adolescents(13 - 19 years): 6 to 10 mg/l, Adults: 5 to 18 mg/l')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4768,15,Null,Null,'Neutrophils 40-70%; Lymphocytes 22-44%; Eosinophils 00-06%, Basophils; Monocytes 00-05%; Bands 00-03%')
