using System;
using System.Collections.Generic;
using System.Xml.Serialization;
// ---------------------------------------------------------------------------------------------------------
// <autogenerated>
// File          : Patient.cs
// Date          : 2013/12/31 06:02:41
// XSD Filepath  : http://www.bware.biz/DotNet/Tools/CodeXS/WebClient/temp/CodeXS/o34k4ce2g41bpqznjxnr0x3r/Patient.xsd
// XSD Namespace : N/A
// CodeXS        : Version 0.57 Beta - 13 Jul 2006
// .NET Runtime  : Version 2.0.50727.3649
// Generation No.: 0001
//   -------------------------------------------------------------------------------------------------------
//   Code Modifiers:
//   Generator:
//     Assembly  : CodeXS.Schema
//     Namespace : CodeXS.Schema.CodeModifier.HeadComment
//     Version   : 0.57.0.0
// 
// Notes:
// * Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
// </autogenerated>
// ---------------------------------------------------------------------------------------------------------
namespace Attune.HL7Integration
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Director", "0.0.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class data
    {
        /// <remarks/>
        public dataLabDetails LabDetails = new dataLabDetails();
        /// <remarks/>
        public dataPatientDetails PatientDetails = new dataPatientDetails();
        /// <remarks/>
        public dataPatientAddress PatientAddress = new dataPatientAddress();
        /// <remarks/>
        public dataVisitDetails VisitDetails = new dataVisitDetails();
        /// <remarks/>
        //public dataRecordsRecordNK1 NK1;
        /// <remarks/>
        //public dataInvestigationDetails InvestigationDetails = new dataInvestigationDetails();
        /// <remarks/>          
        ///
        public List<Investigation> InvestigationDetails = new List<Investigation>();

    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Director", "0.0.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class dataLabDetails
    {
        /// <remarks/>
        private string orgName = string.Empty;
        public string OrgName
        {
            get { return orgName; }
            set { orgName = value; }
        }
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool Message_IDSpecified;
        /// <remarks/>
        private string orgaddressName = string.Empty;
        public string OrgAddressName
        {
            get { return orgaddressName; }
            set { orgaddressName = value; }
        }

    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Director", "0.0.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class dataPatientDetails
    {
        private string patientnumber = string.Empty;
        public string PatientNumber
        {
            get { return patientnumber; }
            set { patientnumber = value; }
        }

        private string age = string.Empty;
        public string Age
        {
            get { return age; }
            set { age = value; }
        }

        private string sex = string.Empty;
        public string Sex
        {
            get { return sex; }
            set { sex = value; }
        }

        private string name = string.Empty;
        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        private string title = string.Empty;
        public string Title
        {
            get { return title; }
            set { title = value; }
        }

        private string dOB = string.Empty;
        public string DOB
        {
            get { return dOB; }
            set { dOB = value; }
        }
        private string _patient_id_int = string.Empty;
        public string Patient_Id_Int
        {
            get { return _patient_id_int; }
            set { _patient_id_int = value; }
        }

        private string _Patient_Id_Type = string.Empty;
        public string Patient_Id_Type
        {
            get { return _Patient_Id_Type; }
            set { _Patient_Id_Type = value; }
        }

        private string _patient_id_number = string.Empty;
        public string Patient_Id_Number
        {
            get { return _patient_id_number; }
            set { _patient_id_number = value; }
        }
        //private string _dateofbirth = string.Empty;
        //public string DateOfBirth
        //{
        //    get { return _dateofbirth; }
        //    set { _dateofbirth = value; }
        //}
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Director", "0.0.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class dataPatientAddress
    {
        /// <remarks/>
        private string addresstype = string.Empty;
        public string AddressType
        {
            get { return addresstype; }
            set { addresstype = value; }
        }

        /// <remarks/>
        private string addressline1 = string.Empty;
        public string AddressLine1
        {
            get { return addressline1; }
            set { addressline1 = value; }
        }

        private string addressline2 = string.Empty;
        public string AddressLine2
        {
            get { return addressline2; }
            set { addressline2 = value; }
        }

        private string addressline3 = string.Empty;
        public string AddressLine3
        {
            get { return addressline3; }
            set { addressline3 = value; }
        }

        private string mobileNo = string.Empty;
        public string MobileNo
        {
            get { return mobileNo; }
            set { mobileNo = value; }
        }

        private string landlineno = string.Empty;
        public string LandLineNo
        {
            get { return landlineno; }
            set { landlineno = value; }
        }

        private string city = string.Empty;
        public string City
        {
            get { return city; }
            set { city = value; }
        }
        private string stateID = string.Empty;
        public string StateID
        {
            get { return stateID; }
            set { stateID = value; }
        }
        private string statename = string.Empty;
        public string StateName
        {
            get { return statename; }
            set { statename = value; }
        }



        private string countryiD = string.Empty;
        public string CountryID
        {
            get { return countryiD; }
            set { countryiD = value; }
        }

        private string countryname = string.Empty;
        public string CountryName
        {
            get { return countryname; }
            set { countryname = value; }
        }



    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Director", "0.0.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class dataVisitDetails
    {
        /// <remarks/>
        private string externalvisitID = string.Empty;
        public string ExternalVisitID
        {
            get { return externalvisitID; }
            set { externalvisitID = value; }
        }
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool Patient_MobilePhoneSpecified;
        /// <remarks/>

        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool Patient_SalutationSpecified;
        /// <remarks/>
        private string collectioncentreid = string.Empty;
        public string CollectionCentreID
        {
            get { return collectioncentreid; }
            set { collectioncentreid = value; }
        }

        /// <remarks/>
        private string referingphysicianname = string.Empty;
        public string ReferingPhysicianName
        {
            get { return referingphysicianname; }
            set { referingphysicianname = value; }
        }
        /// <remarks/>
        private string clientcode = string.Empty;
        public string ClientCode
        {
            get { return clientcode; }
            set { clientcode = value; }
        }

    }
    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("Director", "0.0.57.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    //public   class dataRecordsRecordNK1
    //{
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("PatientAddress_Type")]
    //    public string[] PatientAddress_Type;
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("PatientAddress_AddressLine1")]
    //    public string[] PatientAddress_AddressLine1;
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("PatientAddress_AddressLine2")]
    //    public string[] PatientAddress_AddressLine2;
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("PatientAddress_City")]
    //    public string[] PatientAddress_City;
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("PatientAddress_Zipcode")]
    //    public int[] PatientAddress_Zipcode;
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("PatientAddress_Country")]
    //    public string[] PatientAddress_Country;
    //}
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Director", "0.0.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class dataInvestigationDetails
    {
        public List<Investigation> InvestigationList = new List<Investigation>();

        // public dataInvestigation InvestigationList = new dataInvestigation();
    }

    public class Investigation
    {
        private long investigationid = -1;
        public long InvestigationID
        {
            get { return investigationid; }
            set { investigationid = value; }
        }

        private string name = string.Empty;
        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        private string type = string.Empty;
        public string Type
        {
            get { return type; }
            set { type = value; }
        }

        private string _oBR_Placer_Order_Number = string.Empty;
        public string OBR_Placer_Order_Number
        {
            get { return _oBR_Placer_Order_Number; }
            set { _oBR_Placer_Order_Number = value; }
        }
    }




}
