Truncate Table DrugFormulation
GO
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (1,'TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (2,'SYRUP','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (3,'SUSPENSION','SUSP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (4,'OINTMENT','OINTMENT','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (5,'FILM COATED-TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (6,'MODIFIED RELEASE TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (7,'NASAL SOLUTION','NOSE DROPS','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (8,'NASAL SPRAY','NASAL SPRAY','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (9,'EMULSION GEL','OINTMENT','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (10,'CAPSULE','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (11,'AQUEOUS GEL','GEL','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (12,'DISPERSIBLE TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (13,'DROPS','DROPS','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (14,'ENTERIC COATED TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (15,'H-PYLORI KIT','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (16,'INJECTION','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (17,'VIAL','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (18,'MET-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (19,'SUSTAINED RELEASE-CAPSULE','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (20,'PEDIATRIC DROPS','DROPS','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (21,'SUPPOSITORY','SUPPOSITORY','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (22,'MM-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (23,'PEDIATRIC SUSPENSION','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (24,'SUSTAINED RELEASE TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (25,'CHEWABLE TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (26,'AMPULE','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (27,'MEL-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (28,'HARD GELATINE CAPSULE','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (29,'DR-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (30,'SUSCAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (31,'KIT','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (32,'INTRA VENOUS-VIAL','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (33,'INTRAVENOUS/INTRA MUSCULAR-INJ','','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (34,'EFC-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (35,'EC-CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (36,'EFF-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (37,'LIQUID','LIQUID','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (38,'DS-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (39,'DUPLEX TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (40,'SOLUTION','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (41,'POWDER','POWDER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (42,'SACHET','SACHET','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (43,'ENEMA','ENEMA','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (44,'DRY SYRUP','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (45,'F-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (46,'SOFTCAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (47,'EXTENDED RELEASE CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (48,'CD-CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (49,'ROTA CAP','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (50,'CONTROLLED RELEASE TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (51,'ER-FC-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (52,'XR-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (53,'EXT-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (54,'RETARD TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (55,'TIMED RELEASE CAPSULE','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (56,'SPRAY','SPRAY','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (57,'PATCH','PATCH','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (58,'SL-CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (59,'ONCE DAILY-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (60,'PRE-FILLED-SYRINGE','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (61,'INFUSION','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (62,'PEADIATRIC ELIXIR','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (63,'EXTENDED RELEASE TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (64,'MD-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (65,'RAPI-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (66,'DEP-INT','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (67,'R-APPLI','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (68,'SUBLINGUAL TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (69,'F-CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (70,'XL-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (71,'XR-CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (72,'BUC-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (73,'ELIXIR','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (74,'KID-SYN','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (75,'FILCOTAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (76,'TD-PATCH','PATCH','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (77,'KID TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (78,'DS-SUSP','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (79,'CAPLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (80,'JR-DT TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (81,'SR-FC-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (82,'CONTROLLED RELEASE CAPSULE','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (83,'TIMED RELEASE TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (84,'TEMBID','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (85,'KI','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (86,'GEL-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (87,'CAP-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (88,'GEL','GEL','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (89,'CT-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (90,'KID-DT-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (91,'CREAM','CREAM','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (92,'SC-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (93,'SOFT GELATINE-CAPSULE','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (94,'PESSARY','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (95,'FLEXPAN','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (96,'PENFIL','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (97,'HM-PENFIL','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (98,'CART','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (99,'OPTIPEN','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (100,'SEMI-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (101,'PILL','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (102,'MODIFED RELEASE-CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (103,'VAGINAL-TABLET','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (104,'VAGINAL-CREAM','CREAM','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (105,'VAGINAL-SUPPOSITORY','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (106,'VAGINAL GEL','GEL','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (107,'P-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (108,'INTRAVENOUS-BAG','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (109,'OVULE','OVULE','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (110,'VAGINAL PESSARY','PESSARY','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (111,'SYRINGE','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (112,'DS-CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (113,'REDI MIX SYRUP','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (114,'REDIUSE SYRUP','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (115,'BID-D-SYR','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (116,'F-INJ','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (117,'P-INJ','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (118,'KT-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (119,'DS-SYR','SYP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (120,'LA-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (121,'RM-DPS','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (122,'DP-INJ','INJ.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (123,'DRAG-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (124,'GRANULE','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (125,'DR-CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (126,'SS-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (127,'DT-DT-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (128,'DS-FC-TAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (129,'RESPULE -SOLN','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (130,'CAPTAB','TAB.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (131,'COMBI-PACK','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (132,'METERED DOSE INHALER','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (133,'ROTACAP','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (134,'RESPULE','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (135,'F-RESP','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (136,'AC-HALER','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (137,'INHALENT','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (138,'NEBULE','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (139,'DURULE','INHALER','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (140,'P-SOLN','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (141,'MINI-DROPS','DROPS','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (142,'BOTTLE','BOTTLE','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (143,'NASAL DROPS','NOSE DROPS','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (144,'P-N-DPS','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (145,'KIB-N-DPS','','3')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (146,'MOUTH WASH','MOUTH WASH','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (147,'EAR/EYE DROPS','DROPS','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (148,'APPL CAP','CAP.','1')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (149,'EYE-DROPS','EYE DROPS','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (150,'EYE LOTION','LOTION','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (151,'LOTION','LOTION','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (152,'WASH','WASH','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (153,'FOAM','FOAM','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (154,'F-SOLN','SOLUTION','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (155,'F-OINT','OINTMENT','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (156,'T-SOLN','SOLUTION','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (157,'F-CRM','CREAM','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (158,'JELLY','JELLY','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (159,'CHEWING GUM','CHEWING GUM','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (160,'PASTE','PASTE','2')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (161,'PAINT','PAINT','0')
INSERT INTO DrugFormulation (FMID, FMName, DisplayText, DisplayPlace) Values (162,'LOZENGE','TAB.','0')