Truncate Table DrugGeneric
GO
INSERT INTO DrugGeneric (GenericID, GenericName) Values (1,'BISMUTH SUBCITRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (2,'CIMETIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (3,'CISAPRIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (4,'DOMPERIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (5,'ESOMEPRAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (6,'FAMOTIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (7,'H.PYLORI COMPLIANCE KIT')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (8,'LANSOPRAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (9,'METOCLOPRAMIDE HYDROCHLORIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (10,'MOSAPRIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (11,'OMEPRAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (12,'OMEPRAZOLE + DOMPERIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (13,'PANTOPRAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (14,'PANTOPRAZOLE + DOMPERIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (15,'RABEPRAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (16,'RABEPRAZOLE + ITOPRIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (17,'RANITIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (18,'ROXATIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (19,'SUCRALFATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (20,'CAMYLOFIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (21,'CHLORDIAZEPOXIDE + CLIDINIUM BROMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (23,'DICYCLOVERINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (24,'DROTAVERINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (25,'FENOVERINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (26,'HYOSCINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (27,'ITOPRIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (28,'MEBEVERINE HYDROCHLORIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (29,'OXYOHENONIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (30,'PROPANTHELINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (31,'BISACODYL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (32,'LACTULOSE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (33,'BALSALAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (34,'MESALAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (35,'SULFASALAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (36,'TEGASEROD')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (37,'CIPROFLOXACIN + TINIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (38,'COLISTINE SULPHATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (39,'FURAZOLIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (40,'LOPERAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (41,'METRONIDAZOLE + FURAZOLIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (42,'METRONIDAZOLE + NORFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (43,'NITAZOXANIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (44,'NORFLOXACIN + TINIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (45,'RACECADOTRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (46,'SILYMARIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (47,'URSODEOXYCHOLIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (48,'AMILORIDE + HYDRO CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (49,'AMLODIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (50,'AMLODIPINE + ATENOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (51,'AMLODIPINE + BENAZEPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (52,'AMLODIPINE + ENALAPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (53,'AMLODIPINE + LISINOPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (54,'AMLODIPINE + LOSARTAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (55,'ATENOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (56,'ATENOLOL + CHLORTHALIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (57,'ATENOLOL + NIFEDIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (58,'BENAZERPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (59,'BENIDIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (60,'BISOPROLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (61,'CANDESARTAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (62,'CAPTOPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (63,'CAPTOPRIL + HYDRO-CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (64,'CARVEDILOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (65,'CELIPROLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (66,'CHLORTALIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (67,'CLONIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (68,'CLONIDINE + HYDRO-CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (69,'CLOPAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (70,'DILTIAZEM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (71,'DOXAZOSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (72,'ENALAPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (73,'ENALAPRIL + HYDRO-CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (74,'FELODIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (75,'FOSINOPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (76,'FUROSEMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (77,'FUROSEMIDE + AMILORIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (78,'HYDRO-CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (79,'IMIDAPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (80,'INDAPAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (81,'IRBESARTAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (82,'LABETALOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (82,'LACIDIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (84,'LERCANIDIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (85,'LISINOPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (86,'LISINOPRIL + HYDRO-CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (87,'LOSARTAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (88,'LOSARTAN + HYDRO-CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (89,'LOSARTAN + RAMIPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (90,'METHYLDOPA')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (91,'METOLAZONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (92,'METOPROLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (93,'METOPROLOL + HYDRO-CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (94,'NEBIVOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (95,'NEBIVOLOL + HYDRO CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (96,'NIFEDIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (97,'PERINDOPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (98,'PERINDOPRIL + INDAPAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (99,'PRAZOSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (100,'PROPRANOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (101,'PROPRANOLOL + HYDRO CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (102,'RAMIPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (103,'RAMIPRIL + HYDRO-CHLOROTHIAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (104,'RESERPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (105,'S-AMLODIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (106,'S-AMLODIPINE + NEBIVOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (107,'S-ATENOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (108,'TELMISARTAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (109,'TERAZOSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (110,'TORASEMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (111,'TRANDOLAPRIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (112,'TRIAMTERENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (113,'VALSARTAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (114,'VERAPAMIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (119,'DIPYRIDAMOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (120,'GLYCERYL TRINITRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (121,'ISOSORBIDE DINITRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (122,'ISOSORBIDE MONONITRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (123,'ISOSORBIDE MONONITRATE + ASPIRIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (125,'NICORANDIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (126,'OXYFEDRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (127,'PENTAERYTHRITYL TETRANITRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (129,'TRIMETAZIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (130,'ADENOSINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (131,'AMIODARONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (133,'DISOPYRAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (134,'ESMOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (135,'LIDOCAINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (137,'MEXILETINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (138,'PROPAFENONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (140,'QUINIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (141,'SOTALOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (142,'CILOSTAZOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (143,'CINNARIZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (144,'CYCLANDELATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (145,'ISOXSUPRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (146,'PENTOXIFYLLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (147,'XANTINOL NICOTINATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (148,'EPHEDRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (149,'MEPHENTERMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (150,'ABCIXIMAB')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (151,'ACENOCOUMAROL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (152,'ALTEPLASE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (153,'ASPIRIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (154,'ASPIRIN + CLOPIDOGREL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (155,'ASPIRIN + DIPYRIDAMOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (156,'CLOPIDOGREL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (157,'DALTEPARIN SODIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (159,'ENOXAPARIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (160,'HEPARIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (161,'NADROPARIN CALCIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (162,'REVIPARIN SODIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (163,'STREPTOKINASE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (164,'TICLOPIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (165,'TIROFIBAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (166,'UROKINASE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (167,'WARFARIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (168,'AMINOCAPROIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (169,'APROTININ')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (170,'ETHAMSYLATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (171,'HEMOCOAGULASE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (172,'SOMATOSTATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (173,'TRANEXAMIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (174,'AMRINONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (175,'DIGOXIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (176,'DOUBUTAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (177,'DOPAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (178,'ACETAZOLAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (181,'ATORVASTATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (182,'ATORVASTATIN + EZETIMIBE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (183,'ATORVASTATIN + FENOFIBRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (184,'BEZAFIBRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (185,'CERIVASTATIN SODIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (186,'EZETIMIBE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (187,'FENOFIBRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (188,'GEMFIBROZIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (189,'LOVASTATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (190,'NICOTINIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (191,'PRAVASTATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (192,'ROSUVASTATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (193,'SIMVASTATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (194,'SIMVASTATIN + EZETIMIBE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (195,'ATROPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (196,'CALCIUM DOBESILATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (197,'DIOSMIN/FLAVONOIDS')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (198,'MILRINONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (199,'NIMODIPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (200,'NITRAZEPAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (201,'ZALEPLON')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (202,'ZOPICLONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (203,'ARIPIPRAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (204,'CHLORPROMAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (205,'CLOZAPIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (206,'DIVALPROEX SODIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (207,'FLUPENTHIXOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (208,'FLUPENTHIXOL +MELITRACEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (209,'FLUPHENAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (210,'HALOPERIDOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (211,'LOXAPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (212,'OLANZAPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (213,'PENFLURIDOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (214,'PIMOZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (215,'QUETIAPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (216,'RISPERIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (217,'THIORIDAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (218,'TRIFLUOPERAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (219,'ZIPRASIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (220,'ZUCLOPENTHIXOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (221,'ALPRAZOLAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (222,'BUSPIRONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (223,'CHLORDIAZEPOXIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (224,'CHLORDIAZEPOXIDE + AMITRIPTYLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (225,'CLOBAZAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (226,'DIAZEPAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (227,'FLURAZEPAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (228,'HYDROXYZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (229,'LORAZEPAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (230,'MELATONIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (231,'MIDAZOLAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (232,'OXAZEPAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (233,'ZOLPIDEM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (234,'AMITRIPTYLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (235,'AMOXAPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (236,'CITALOPRAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (237,'CLOMIPRAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (238,'DIAZEPAM + IMIPRAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (239,'DOSULEPIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (240,'DOXEPIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (241,'DULOXETINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (242,'ESCITALOPRAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (243,'FLUOXETINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (244,'FLUVOXAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (245,'IMIPRAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (246,'LITHIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (247,'MIANSERIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (248,'MIRTAZAPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (249,'MOCLOBEMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (250,'NORTRIPTYLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (251,'PAROXETINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (252,'REBOXETINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (253,'SERTRALINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (254,'TIANEPTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (255,'TRAZODONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (256,'TRIMIPRAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (257,'VENLAFAXINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (258,'BETAHISTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (259,'CINNARIZINE + DOMPERIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (260,'DIMENHYDRINATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (261,'DOXYLAMINE + PYRIDOXINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (262,'GRANISETRON')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (263,'MECLOZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (264,'ONDANSETRON')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (265,'PROCHLORPERAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (266,'PROMETHAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (267,'CARBAMAZEPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (268,'CLONAZEPAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (269,'FOSPHENYTOIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (270,'GABAPENTIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (271,'LAMOTRIGINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (272,'OXCARBAZEPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (273,'PHENOBARBITONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (274,'PHENOBARBITONE + PHENYTOIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (275,'PHENYTOIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (276,'PRIMIDONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (277,'TOPIRAMATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (278,'VALPROIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (279,'AMANTADINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (280,'BENZHEXOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (281,'BROMOCRIPTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (282,'CABERGOLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (283,'CARBIDOPA + LEVODOPA')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (284,'CITICOLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (285,'LEVODOPA')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (286,'ORPHENADRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (287,'PIRIBEDIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (288,'PROCYCLIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (289,'ROPINIROLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (290,'SELEGILINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (291,'TETRABENAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (292,'CO-DERGOCRINE MESYLATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (293,'MODAFINIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (294,'NICERGOLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (295,'PIRACETAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (296,'PYRITINOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (297,'VINPOCETINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (298,'ANALGIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (299,'BUPRENORPHINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (300,'BUTORPHANOL TARTRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (301,'DEXTRO-PROPOXYPHENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (302,'ETHYLMORPHINE HCL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (303,'FENTANYL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (304,'KETOROLAC TROMETAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (305,'MEFENAMIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (306,'MORPHINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (307,'PARACETAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (308,'PARACETAMOL +DEXTRO-PROPOXYPHENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (309,'PARACETAMOL + PENTAZOCINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (310,'PENTAZOCINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (311,'PETHIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (312,'TRAMADOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (313,'DOMEPERIDONE + PARACETAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (314,'ERGOTAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (315,'FLUNARIZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (316,'PARACETAMOL + METOCLOPRAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (317,'RIZATRIPTAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (318,'SUMATRITAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (319,'PREGABALIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (320,'ACECLOFENAC')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (321,'ACECLOFENAC + PARACETAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (322,'AURANOFIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (323,'CELECOXIB')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (324,'CHLOROQUINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (325,'CHYMOTRYPSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (326,'DEXIBUPROFEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (327,'DIACEREIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (328,'DICLOFENAC')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (329,'DICLOFENAC + PARACETAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (330,'ETORICOXIB')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (331,'FLURBIPROFEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (332,'GLUCOSAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (333,'IBUPROFEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (334,'IBUPROFEN + PARACETAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (335,'INDOMETACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (336,'KETOPROFEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (337,'LEFLUNOMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (338,'MELOXICAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (339,'NABUMETONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (340,'NAPROXEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (341,'NIMESULIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (342,'NIMESULIDE + RACEMETHIONINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (343,'PARECOXIB')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (344,'PENICILLAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (345,'PIROXICAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (346,'PIROXICAM BETA-CYCLODEXTRIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (347,'SERRAPEPTASE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (348,'TENOXICAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (349,'VALDECOXIB')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (350,'ACECLOFENAC + CHLORZOXAZONE + PARACETAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (351,'BACLOFEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (352,'CARISOPRODOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (353,'CHLORMEZANONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (354,'CHLORZOXANONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (355,'METHOCARBAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (356,'TIZANIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (357,'ALLUPURINOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (358,'COLCHICINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (359,'BENZYDAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (360,'DONEPEZIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (361,'NEOSTIGMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (362,'PYRIDOSTIGMINE BROMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (363,'RIVASTIGIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (364,'ALLYLESTRENOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (365,'DANAZOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (366,'DYDROGESTERONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (367,'ESTROGENS')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (368,'ETHINYL ESTRADIOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (369,'HUMAN MENOPAUSAL GONADOTROPHINS')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (370,'HYDROXY-PROGESTERONE CAPROATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (371,'MEDROXY-PROGESTERONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (372,'MESTEROLONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (373,'NAFARELIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (374,'NORETHISTERONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (375,'PROGESTERONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (376,'TESTOSTERONE DERIVATIVES')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (377,'TIBOLONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (378,'TRIPTORELIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (379,'UROFOLLITROPIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (380,'BETAMETHASONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (381,'DEXAMETHASONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (382,'HYDROCORTISONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (383,'PREDNISOLONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (384,'TRIAMCINOLONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (385,'CHORIONIC GONADOTROPHIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (386,'CARBIMAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (387,'LEVOTHYROXINE SODIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (388,'OCTREOTIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (389,'SOMATROPIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (390,'DESMOPRESSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (391,'TERLIPRESSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (392,'VASOPRESSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (393,'INSULINS')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (394,'ACARBOSE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (395,'CHLORPROPAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (396,'CHROMIUM PICOLINATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (397,'GLIBENCLAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (398,'GLIBENCLAMIDE + METFORMIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (399,'GLICLAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (400,'GLICLAZIDE + METFORMIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (401,'GLIMEPIRIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (402,'GLIMEPIRIDE + METFORMIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (403,'GLIPIZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (404,'GLUCOMANNAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (405,'METFORMIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (406,'MIGLITOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (407,'NATEGLINIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (408,'PIOGLITAZONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (409,'PIOGLITAZONE + GLIMEPIRIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (410,'PIOGLITAZONE + METFORMIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (411,'REPAGLIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (412,'ROSIGLITAZONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (413,'ROSIGLITAZONE + GLICLAZIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (414,'ROSIGLITAZONE + METFORMIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (415,'TOLBUTAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (416,'VOGLIBOSE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (417,'GLUCAGON')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (418,'CLOMIFENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (419,'LEVONORGESTREL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (420,'LEVONORGESTREL + ETHINYL ESTRADIOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (421,'NONOXINOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (422,'FUROSEMIDE + SPIRONOLACTONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (423,'SPIRONOLACTONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (424,'XIPAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (425,'DISODIUM HYDROGEN CITRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (426,'SEVELAMER HYDROCHLORIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (427,'ALFUZOSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (428,'BETHANECHOL CHLORIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (429,'DUTASTERIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (430,'FINASTERIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (431,'FINASTERIDE + TAMSULOSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (432,'FLAVOXATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (433,'OXYBUTYNIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (434,'PHENAZOPYRIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (435,'TAMSULOSIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (436,'TAMSULOSIN + DUTASTERIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (437,'TOLTERODINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (438,'TRABEXAMIC ACID + MEFENAMIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (439,'AZITHROMYCIN + FLUCONAZOLE + SECNIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (440,'CICLOPIROX')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (441,'CLOTRIMAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (442,'METRIONIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (443,'MICONAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (444,'NATAMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (445,'POVIDONE IODINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (446,'TINIDAZOLE + FLUCONAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (447,'CARBOPROST')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (448,'DINOPROSTONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (449,'ERGOMETRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (450,'ETHACRIDINE LACTATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (451,'METHYL ERGOMETRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (452,'MIFERISTONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (453,'MISOPROSTOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (454,'ORMELOXIFENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (455,'OXYTOCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (456,'RITODRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (457,'SILDENAFIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (458,'TADALAFIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (459,'AMIKACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (460,'AMOXICILLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (461,'AMOXICILLIN + BROMHEXINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (462,'AMOXICILLIN + CARBOCISTEINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (463,'AMOXICILLIN + CLAVULANIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (464,'AMOXICILLIN + CLOXACILLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (465,'AMOXICILLIN + PROBENECID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (466,'AMPICILLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (467,'AMPICILLIN + CLOXACILLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (468,'AMPICILLIN + PROBENECID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (469,'AMPICILLIN + SULBACTAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (470,'AZITHROMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (471,'AZTREONAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (472,'BACAMPICILLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (473,'CEFACLOR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (474,'CEFADROXIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (475,'CEFALEXIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (476,'CEFELORIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (477,'CEFAZOLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (478,'CEFDINIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (479,'CEFEPIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (480,'CEFETAMET')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (481,'CEFIXIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (482,'CEFOPERAZONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (483,'CEFOPERAZONE + SULBACTAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (484,'CEFOTAXIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (485,'CEFOTAXIME + SULBACTAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (486,'CEFPRIOME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (487,'CEFPODOXIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (488,'CEFPROZIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (489,'CEFTAZIDIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (490,'CEFTIZOXIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (491,'CEFTRIAXONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (492,'CEFTRIAXONE + SULBACTAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (493,'CEFTRIAXONE + TAZOBACTAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (494,'CEFUROXIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (495,'CHLORAMPHENICOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (496,'CIPROFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (497,'CLARITHROMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (498,'CLINIDAMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (499,'CLOXACILLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (500,'CO-TRIMOXAZOLE (SULFAMETHOXAZOLE & TRIMETHOPRIM)')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (501,'DEMECLOCYCLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (502,'DOXYCYCLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (503,'ERYTHROMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (504,'GATIFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (505,'GEMIFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (506,'GENTAMICIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (507,'KANAMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (508,'LEVOFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (509,'LINCOMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (510,'LINEZOLID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (511,'LOMEFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (512,'MEROPENEM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (513,'MINOCYCLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (514,'MOXIFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (515,'NALIDIXIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (516,'NETILMICIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (517,'NITROFURANTOIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (518,'NORFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (519,'OFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (520,'OFLOXACIN + TINIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (521,'ORNIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (522,'OXYTETRACYCLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (523,'PEFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (524,'PIPERACILLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (525,'PIPERACILLIN + TAZOBACTAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (526,'POLYMYXIN B')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (527,'ROXITHROMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (528,'SATRANIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (529,'SISOMICIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (530,'SPARFLOXACIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (531,'SPIRAMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (532,'STREPTOMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (533,'SULFAMOXOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (534,'SULFAMOXOLE + TRIMETHOPRIM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (535,'SULPHADIAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (536,'SULPHADIAZINE + TRIMETHOPRIM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (537,'TETRACYCLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (538,'TINIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (539,'TOBRAMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (540,'VANCOMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (541,'CYCLOSERINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (542,'ETHAMBUTOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (543,'ETHIONAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (544,'ISONIAZID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (545,'ISONIAZID + ETHAMBUTOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (546,'PROTIONAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (547,'PYRAZINAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (548,'RIFAMPICIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (549,'RIFAMPICIN + ISONIAZID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (550,'RIFAMPICIN + ISONIAZID + ETHAMBUTOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (551,'RIFMAPICIN + ISONIAZID + PYRAZINAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (552,'RIFMAPICIN + ISONIAZID + PYRAZINAMIDE + ETHAMBUTOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (553,'CLOFAZIMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (554,'DAPSONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (555,'AMPHOTERICIN B')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (556,'FLUCONAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (557,'GRISEOFULVIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (558,'ITRACONAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (559,'KETOCONAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (560,'TERBINAFINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (561,'METRIONIDAZOLE + DILOXANIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (562,'SECNIDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (563,'TINIDAZOLE + DILOXANIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (564,'ARTEETHER')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (565,'ARTEMTHER')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (566,'ARTESUNATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (567,'BULAQUINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (568,'CHLOROQUINE COMPLIANCE KIT/PACK')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (569,'HYDROXY CHLOROQUINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (570,'MEFLOQUINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (571,'PRIMAQUINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (572,'QUININE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (573,'SULPHADOXINE + PYRIMETHAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (574,'ALBENDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (575,'DIETHYL-CARBAMAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (576,'IVERMECTIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (577,'IVERMECTIN + ALBENDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (578,'LEVAMISOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (579,'MEBENDAZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (580,'NICLOSAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (581,'PIPERAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (582,'PRAZIQUANTEL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (583,'PYRANTEL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (584,'ABACAVIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (585,'ACICLOVIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (586,'DIDANOSINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (587,'EFAVIRENZ')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (588,'FAMCICLOVIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (589,'GANCICLOVIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (590,'INDINAVIR SULFATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (591,'INTERFERON ALFA-2A')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (592,'INTERFERON ALFA-2B')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (593,'LAMIVUDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (594,'LAMIVUDINE + ZIDOVUDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (595,'LOPINAVIR + RITONAVIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (596,'NELFINAVIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (597,'NEVIRAPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (598,'RIBAVIRIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (599,'STAVUDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (600,'VALACICLOVIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (601,'ZIDOVUDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (602,'RITONAVIR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (603,'DOXAPRAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (604,'AMINOPHYLLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (605,'BAMBUTEROL HYDROCHLORIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (606,'BECLOMETASONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (607,'BUDESONIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (608,'CROMOGLYCIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (609,'DOXOFYLLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (610,'ERDOSTEINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (611,'FLUTICASONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (612,'FORMOTEROL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (613,'IPRATROPIUM BROMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (614,'ISOPRENALINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (615,'KETOTIFEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (616,'MONTELUKAST SODIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (617,'ORCIPRENALINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (618,'SALBUTAMOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (619,'SALBUTAMOL + THEOPHYLLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (620,'SALMETEROL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (621,'TERBUTALINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (622,'THEOPHYLLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (623,'TIOTROPIUM BROMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (624,'ACETYLCYSTEINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (625,'TERFENADINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (626,'BUCLIZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (627,'CYPROHEPTADINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (628,'ERYTHROPOIETIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (629,'ALENDRONIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (630,'ALPHA-LIPOIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (631,'CALCITONIN, SALMON')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (632,'ETIDRONATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (633,'PAMIDRONATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (634,'RALOXIFENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (635,'RISEDRONIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (636,'STRONTIUM RANELATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (637,'ZOLEDRONIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (638,'ALFACALCIDOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (639,'BENFOTIAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (640,'CALCITRIOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (641,'MECOBALAMIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (642,'METADOXINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (643,'PHYTOMENADIONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (644,'VITAMINE E')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (645,'ORLISTAT')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (646,'SIBUTRAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (647,'NANDROLONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (648,'STANOZOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (649,'ASTEMIZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (650,'AZATADINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (651,'CETRIZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (652,'CHLORPHENAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (653,'CLEMASTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (654,'DESLORATADINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (655,'DIMETHINDENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (656,'DIPHENHYDRAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (657,'EBASTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (658,'EMBRAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (659,'FEXOFENADINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (660,'LEVOCETIRIZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (661,'LORATADINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (662,'LUVISTIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (663,'METHDILAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (664,'MIZOLASTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (665,'PHENIRAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (666,'RUPATAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (667,'AZELASTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (668,'OXYMETAZOLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (669,'XYLOMETAZOLINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (670,'CHLORHEXIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (671,'FLUNISOLIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (672,'FRAMYCETIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (673,'SILVER SULFADIAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (674,'SULFACETAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (675,'FLUOROMETHOLONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (676,'LOTEPREDNOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (677,'BETAXOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (678,'BRIMONIDINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (679,'DIPIVEFRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (680,'DORZOLAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (681,'LATANOPROST')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (682,'LEVOBUNOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (683,'PILOCARPINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (684,'TIMOLOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (685,'CYCLOPENTOLATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (686,'TROPICAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (687,'BUTENAFINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (688,'FUSIDIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (689,'MUPIROCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (690,'NITROFURAL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (691,'QUINIDOCHLOR')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (692,'TOLNAFTATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (693,'BENZYL BENZOATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (694,'CROTAMITON')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (695,'LINDANE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (696,'PERMETHRIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (697,'ACITRETIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (698,'CALCIPOTRIOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (699,'METHOXSALEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (700,'ADAPALENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (701,'BENZOYL PEROXIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (702,'ISOTRETINOIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (703,'TRETINOIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (704,'CLOBETASOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (705,'DESONIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (706,'FLUOCINOLONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (707,'HALCINONIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (708,'MOMETASONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (709,'PREDNICARBATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (710,'TACROLIMUS')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (711,'HYDROQUINONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (712,'AMINOBENZOIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (713,'MINOXIDIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (714,'TAZAROTENE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (715,'AMIFOSTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (716,'ANASTROZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (717,'ASPARAGINASE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (718,'BICALUTAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (719,'BLEOMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (720,'BUSULFAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (721,'CALCIUM FOLINATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (722,'CAPECITABINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (723,'CARBOPLATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (724,'CHLORAMBUCIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (725,'CISPLATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (726,'CYCLOPHOSPHAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (727,'CYTARABINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (728,'DACARBAZINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (729,'DACTINOMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (730,'DAUNORUBICIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (731,'DOCETAXEL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (732,'DOXORRUBICIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (733,'EPIRUBICIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (734,'ETOPOSIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (735,'FILGRASTIM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (736,'FLUROURACIL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (737,'FLUTAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (738,'FOSFESTROL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (739,'GEMCITABINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (740,'GOSERELIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (741,'HYDROXYCARBAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (742,'IFOSFAMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (743,'LETROZOLE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (744,'LEUPRORELIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (745,'LOMUSTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (746,'MELPHALAN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (747,'MERCAPTOPURINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (748,'MESNA')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (749,'METHOTREXATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (750,'MITOMYCIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (751,'MITOXANTRONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (752,'OXALIPLATIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (753,'PACLITAXEL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (754,'TAMOXIFEN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (755,'TIOGUANINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (756,'VINBLASTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (757,'VINCRISTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (758,'AZATHIOPRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (759,'CICLOSPORIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (760,'MYCOPHENOLIC ACID')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (761,'BUPROPION HYDROCHLORIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (762,'DEFERIPRONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (763,'DESFERRIOXAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (764,'DISULFIRAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (765,'NALOXONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (766,'NALTREXONE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (767,'NICOTINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (768,'PRALIDOXIME')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (769,'BUPIVACAINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (770,'HALOTHANE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (771,'KETAMINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (773,'LIDOCAINE + EPINEPHRINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (774,'MIZAZOLAM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (775,'PROPOFOL')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (776,'THIOPENTAL SODIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (777,'ATRACURIUM BESILATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (778,'GLYCOPYRRONIUM BROMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (779,'PANCURONIUM')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (780,'SUXAMETHONIUM CHLORIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (781,'VECURONIUM BROMIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (782,'HUMAN ALBUMIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (783,'ENBUCRILATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (784,'HYALURONIDASE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (786,'PENICILLIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (787,'SODIUM CHLORIDE/SODIUM HYALURONATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (788,'EPTIFIBATIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (789,'DIPYRIDAMOLE + ASPIRIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (790,'DEXTROSE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (791,'CODEINE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (792,'ALUMINIUM HYDROXIDE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (793,'ALBENDAZOLE + IVERMECTIN')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (794,'POTASSIUM NITRATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (795,'SODIUM FLUORIDE/SODIUM BENZOATE')
INSERT INTO DrugGeneric (GenericID, GenericName) Values (796,'OROPHARYNGEAL COMBINATIONS')

--Insert DrugGeneric Table
INSERT INTO DrugGeneric (GenericID,GenericName) VALUES (797,'OFLOXACIN + ORNIDAZOLE')
INSERT INTO DrugGeneric (GenericID,GenericName) VALUES (798,'NIMESULIDE + PARACETAMOL')
INSERT INTO DrugGeneric (GenericID,GenericName) VALUES (799,'ACECLOFENAC + PARACETAMOL + SERRATIOPEPTRIDARE')