INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (538,'Brodies Abscess','Brodies Abscess',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (539,'Psoas  Abscess','Psoas  Abscess',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (540,'Subcutaneous Abscess','Subcutaneous Abscess',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (541,'Acute Pyogenic Abscess ','Acute Pyogenic Abscess ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (542,'Cold Abscess','Cold Abscess',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (543,'Infected Haematoma','Infected Haematoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (544,'Osteoarthritis Both Knee Joint','Osteoarthritis Both Knee Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (545,'Osteoarthritis Right Knee Joint','Osteoarthritis Right Knee Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (546,'Osteoarthritis Left Knee Joint','Osteoarthritis Left Knee Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (547,'Osteoarthritis Hip Joint','Osteoarthritis Hip Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (548,'Osteoarthritis Elbow  Joint','Osteoarthritis Elbow  Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (549,'Osteoarthritis  Ankle Joint','Osteoarthritis  Ankle Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (550,'Osteoarthritis Shoulder  Joint','Osteoarthritis Shoulder  Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (551,'Osteoarthritis Wrist Joint','Osteoarthritis Wrist Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (552,'Osteoarthritis MCP Joint','Osteoarthritis MCP Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (553,'Osteoarthritis MTP Joint','Osteoarthritis MTP Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (554,'Osteoarthritis Subtalar  Joint','Osteoarthritis Subtalar  Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (555,'Osteoarthritis Sacro-Iliac Joint','Osteoarthritis Sacro-Iliac Joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (556,'Acromio-clavicular joint arthritis ','Acromio-clavicular joint arthritis ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (557,'Acromio-clavicular joint distruption','Acromio-clavicular joint distruption',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (558,'Shoulder joint Dislocation','Shoulder joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (559,'Elbow joint Dislocation','Elbow joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (560,'MCP joint Dislocation','MCP joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (561,'MTP joint Dislocation','MTP joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (562,'PIP joint Dislocation','PIP joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (563,'DIP joint Dislocation','DIP joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (564,'Wrist joint Dislocation','Wrist joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (565,'Subtalar joint Dislocation','Subtalar joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (566,'Ankle joint Dislocation','Ankle joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (567,'Knee joint Dislocation','Knee joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (568,'Hip joint Dislocation','Hip joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (569,'Patella  Dislocation','Patella  Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (570,'Tempro-mandibular joint Dislocation','Tempro-mandibular joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (571,'Atlanto-axial joint Dislocatio','Atlanto-axial joint Dislocatio',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (572,'Atlanto-occeputal joint Dislocation','Atlanto-occeputal joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (573,'Recurrent  Dislocation Shoulder','Recurrent  Dislocation Shoulder',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (574,'Recurrent  Dislocation Patella','Recurrent  Dislocation Patella',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (575,'Fracture Neck of Femur','Fracture Neck of Femur',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (576,'Fracture intertrochanteric region','Fracture intertrochanteric region',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (577,'Fracture shaft of femur ','Fracture shaft of femur ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (578,'Fracture supracondylar region of femur','Fracture supracondylar region of femur',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (579,'Fracture supracondylar region of humerus','Fracture supracondylar region of humerus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (580,'Fracture shaft of Tibia','Fracture shaft of Tibia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (581,'Fracture shaft of Humerus','Fracture shaft of Humerus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (582,'Fracture shaft of Radius','Fracture shaft of Radius',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (583,'Fracture shaft of Ulna','Fracture shaft of Ulna',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (584,'Fracture shaft of Fibula','Fracture shaft of Fibula',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (585,'Fracture Lateral Malleolus','Fracture Lateral Malleolus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (586,'Fracture Medial Malleolus','Fracture Medial Malleolus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (587,'Bimalleolar  Fracture Ankle','Bimalleolar  Fracture Ankle',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (588,'Fracture Talus','Fracture Talus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (589,'Fracture  Calcaneam','Fracture  Calcaneam',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (590,'Fracture Medial Cuniform','Fracture Medial Cuniform',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (591,'Fracture Lateral Cuniform','Fracture Lateral Cuniform',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (592,'Metatarsal Fracture in Foot','Metatarsal Fracture in Foot',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (593,'Jones Fracture','Jones Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (594,'Proximal Phalanges Fracture','Proximal Phalanges Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (595,'Middle Phalanges Fracture','Middle Phalanges Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (596,'Distal Phalanges Fracture','Distal Phalanges Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (597,'Medial Condyle  Fracture Tibia','Medial Condyle  Fracture Tibia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (598,'Lateral Condyle  Fracture Tibia ','Lateral Condyle  Fracture Tibia ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (599,'Tibial Plateau Fracture ','Tibial Plateau Fracture ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (600,'Medial Condyle  Fracture Femur','Medial Condyle  Fracture Femur',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (601,'Lateral Condyle  Fracture Femur ','Lateral Condyle  Fracture Femur ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (602,'Fracture  Sub-trochanteric region','Fracture  Sub-trochanteric region',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (603,'Acetabulam Fracture','Acetabulam Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (604,'Pelvic Fracture/Injurey','Pelvic Fracture/Injurey',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (605,'Inferior Pubic Ramus Fracture','Inferior Pubic Ramus Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (606,'Superior Pubic Ramus Fracture','Superior Pubic Ramus Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (607,'Fracture Iliac Blade ','Fracture Iliac Blade ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (608,'Sacram Fracture','Sacram Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (609,'Fracture coccyx','Fracture coccyx',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (610,'Fracture Transverse Process','Fracture Transverse Process',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (611,'Anterior wedge compression Fracture','Anterior wedge compression Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (612,'Burs Fracture','Burs Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (613,'Rib Fracture','Rib Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (614,'Clavicle Fracture','Clavicle Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (615,'Scapula Fracture','Scapula Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (616,'Fracture Neck of Scapula','Fracture Neck of Scapula',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (617,'Fracture Glenoid Fossa','Fracture Glenoid Fossa',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (618,'Fracture Greater tuberosity of Humerus','Fracture Greater tuberosity of Humerus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (619,'Fractures coracoid Process','Fractures coracoid Process',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (620,'Fractures proximal humeral shaft ','Fractures proximal humeral shaft ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (621,'Medial Condyle  Fracture Humerus','Medial Condyle  Fracture Humerus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (622,'Lateral Condyle  Fracture Humeurs','Lateral Condyle  Fracture Humeurs',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (623,'Fracture Olecranaon','Fracture Olecranaon',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (624,'Fracture Radial head','Fracture Radial head',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (625,'Fracture Radial neck','Fracture Radial neck',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (626,'Fracture Coronoid Process','Fracture Coronoid Process',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (627,'Monteggia Fracture Dislocation','Monteggia Fracture Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (628,'Galeazzi Fracture Dislocation','Galeazzi Fracture Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (629,'Fracture Distal radius','Fracture Distal radius',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (630,'Fracture Radial Styloid','Fracture Radial Styloid',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (631,'Fracture Ulnar styloid','Fracture Ulnar styloid',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (632,'Distal radio-ulna joint dislocation','Distal radio-ulna joint dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (633,'Fracture Scaphoid','Fracture Scaphoid',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (634,'Fracture Carpel bone','Fracture Carpel bone',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (635,'Fracture Lunate','Fracture Lunate',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (636,'Bennett’s Fracture dislocation','Bennett’s Fracture dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (637,'Battered Baby Syndrome ','Battered Baby Syndrome ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (638,'Biceps tendon rupture','Biceps tendon rupture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (639,'Fibrous dysplasia','Fibrous dysplasia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (640,'Bow Leg ','Bow Leg ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (641,'Brachial Plexus Injurey','Brachial Plexus Injurey',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (642,'Medial Meniscal Injurey','Medial Meniscal Injurey',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (643,'Lateral Meniscal Injurey','Lateral Meniscal Injurey',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (644,'Semimembranous Bursitas','Semimembranous Bursitas',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (645,'Sub-deltoid Bursitas','Sub-deltoid Bursitas',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (646,'Calcaneus tendon rupture','Calcaneus tendon rupture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (647,'Calcaneal spur','Calcaneal spur',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (648,'Capitullum of Humerus fracture','Capitullum of Humerus fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (649,'Dislcoation of lunate','Dislcoation of lunate',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (650,'Carpel tunnel syndrome','Carpel tunnel syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (651,'Cauda equina syndrome','Cauda equina syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (652,'Cauda equine injury','Cauda equine injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (653,'Cerebral palsy','Cerebral palsy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (654,'Cervical Rib','Cervical Rib',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (655,'Cervical Strain','Cervical Strain',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (656,'Cervical Sprain','Cervical Sprain',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (657,'Cervical Spondylosis','Cervical Spondylosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (658,'Cervical Tuberculosis','Cervical Tuberculosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (659,'Cervical Disc prolapse','Cervical Disc prolapse',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (660,'Charcot’s Arthropathy','Charcot’s Arthropathy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (661,'Chondroblastoma','Chondroblastoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (662,'Chondroma','Chondroma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (663,'Chondromalacia Patella','Chondromalacia Patella',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (664,'Chondromatosis','Chondromatosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (665,'Chondrosarcoma','Chondrosarcoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (666,'Chondroma','Chondroma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (667,'Christmas disease','Christmas disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (668,'Claw hand','Claw hand',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (669,'Cleido cranial dysostosis','Cleido cranial dysostosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (670,'Congenital Clubfoot','Congenital Clubfoot',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (671,'Cultton’s joints','Cultton’s joints',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (672,'Colles’ fracture','Colles’ fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (673,'Volkmann’s ischameic contracture','Volkmann’s ischameic contracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (674,'Dupuytrens contracture','Dupuytrens contracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (675,'Perther’s disease','Perther’s disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (676,'Coxa vara Congenita','Coxa vara Congenita',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (677,'Coxa vara Adolescent ','Coxa vara Adolescent ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (678,'Cretinism ','Cretinism ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (679,'Anterior Cruciate ligaments tears','Anterior Cruciate ligaments tears',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (680,'Posterior Cruciate ligaments tears','Posterior Cruciate ligaments tears',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (681,'Cubitus varus Deformity','Cubitus varus Deformity',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (682,'Sample bone cyst','Sample bone cyst',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (683,'Aneurysmal bone cyst','Aneurysmal bone cyst',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (684,'Solitary bone cyst','Solitary bone cyst',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (685,'De Quervain’s syndrome','De Quervain’s syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (686,'Diaphyseal aclasis','Diaphyseal aclasis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (687,'Diastasis of inferior tibio fibular joint','Diastasis of inferior tibio fibular joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (688,'Lumber Disc prolapse','Lumber Disc prolapse',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (689,'Lumber Intervertebral Disc prolapse','Lumber Intervertebral Disc prolapse',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (690,'Cervical Intervertebral Disc prolapse','Cervical Intervertebral Disc prolapse',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (691,'Dorsal Intervertebral Disc prolapse','Dorsal Intervertebral Disc prolapse',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (692,'Colgenital Dislocation of hip joint ','Colgenital Dislocation of hip joint ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (693,'Pathological Dislocation of hip joint','Pathological Dislocation of hip joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (694,'Centeral  Dislocation of hip joint','Centeral  Dislocation of hip joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (695,'Posterior Dislocation of hip joint','Posterior Dislocation of hip joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (696,'Unreduced Dislocation of hip joint','Unreducid Dislocation of hip joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (697,'Unreduced Dislocation of Elbow  joint','Unreducid Dislocation of Elbow  joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (698,'Unreduced Dislocation of Shoulder joint','Unreducid Dislocation of Shoulder joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (699,'Unreduced Dislocation of Ankle  joint','Unreducid Dislocation of Ankle  joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (700,'Unreduced Dislocation of MCP joint ','Unreducid Dislocation of MCP joint ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (701,'Unreduced Dislocation of PIP  joint','Unreducid Dislocation of PIP  joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (702,'Unreduced Dislocation of Dip  joint','Unreducid Dislocation of Dip  joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (703,'Unreduced Dislocation of Subtalar  joint','Unreducid Dislocation of Subtalar  joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (704,'Down’s Syndrome','Down’s Syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (705,'Enchondromatosis (ollier’s Disease) ','Enchondromatosis (ollier’s Disease) ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (706,'Monostotic Displasia ','Monostotic Displasia ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (707,'Polystotic Displasia','Polystotic Displasia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (708,'Enchondroma ','Enchondroma ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (709,'Enchondromatosis','Enchondromatosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (710,'Entrapment syndrome','Entrapment syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (711,'Entrapment Neuropathy','Entrapment Neuropathy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (712,'Medial epicondyle Fracture of Humerus','Medial epicondyle Fracture of Humerus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (713,'Lateral epicondyle Fracture of Humerus','Lateral epicondyle Fracture of Humerus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (714,'Medial epicondylitis of Elbow','Medial epicondylitis of Elbow',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (715,'Lateral epicondylitis of Elbow','Lateral epicondylitis of Elbow',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (716,'Epiphysis Injuries','Epiphysis Injuries',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (717,'Epiphysis Separation','Epiphysis Separation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (718,'Epiphysis Growth Arrest','Epiphysis Growth Arrest',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (719,'Slipped Capital Femoral Epiphysis','Slipped Capital Femoral Epiphysis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (720,'Erb’s Palsy','Erb’s Palsy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (721,'Ewing’s Sarcome','Ewing’s Sarcome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (722,'Multiple Exostoses','Multiple Exostoses',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (723,'Exostosis ','Exostosis ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (724,'Fanconi Syndrome','Fanconi Syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (725,'Planter Fascitis','Planter Fascitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (726,'Fat embolism','Fat embolism',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (727,'Non ossifying Fibroma','Non ossifying Fibroma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (728,'Fibrosarcoma','Fibrosarcoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (729,'Fibrous dysplasia','Fibrous dysplasia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (730,'Mallet Finger','Mallet Finger',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (731,'Nail Bed injuries','Nail Bed injuries',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (732,'Crush Injuries Hand','Crush Injuries Hand',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (733,'Crush Injuries Toe','Crush Injuries Toe',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (734,'Lisfranc Ligament Strain','Lisfranc Ligament Strain',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (735,'Bimalleolar Strain','Bimalleolar Strain',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (736,'Ankle Strain','Ankle Strain',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (737,'Flat Foot (Pes planus)','Flat Foot (Pes planus)',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (738,'Greenstick Fracture','Greenstick Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (739,'Pathological Fracture','Pathological Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (740,'Smith’s Fracture','Smith’s Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (741,'Stress Fracture','Stress Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (742,'Frozen Shoulder','Frozen Shoulder',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (743,'Periarthritis Shoulder','Periarthritis Shoulder',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (744,'Pott’s spine ','Pott’s spine ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (745,'Ganglion ','Ganglion ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (746,'Gas gangrene','Gas gangrene',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (747,'Genu recurvatum Deformity','Genu recurvatum Deformity',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (748,'Genu varum Deformity','Genu varum Deformity',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (749,'Genu valgus Deformity','Genu valgus Deformity',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (750,'Osteoclastoma (GCT)','Osteoclastoma (GCT)',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (751,'Gigantism ','Gigantism ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (752,'Gouty Arthritis','Gouty Arthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (753,'Pseudo Gout','Pseudo Gout',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (754,'Heamarthrosis of Knee joint','Heamarthrosis of Knee joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (755,'Hemothilic arthritis','Hemothilic arthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (756,'Hall valgus Deformity','Hall valgus Deformity',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (757,'Hand Schuller Christian Disease','Hand Schuller Christian Disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (758,'Hangman’s fracture','Hangman’s fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (759,'Hemimelia','Hemimelia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (760,'Hill sach’s lesion','Hill sach’s lesion',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (761,'Rheumatoid arthritis Hip joint','Rheumatoid arthritis Hip joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (762,'Rheumatoid arthritis Knee joint','Rheumatoid arthritis Knee joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (763,'Rheumatoid Hand','Rheumatoid Hand',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (764,'Idiopathic Scoliosis','Idiopathic Scoliosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (765,'Infantile Cortical Hyperostosis','Infantile Cortical Hyperostosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (766,'Poliomyelitis (PPRP)','Poliomyelitis (PPRP)',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (767,'Internal Derangement of Knee joint','Internal Derangement of Knee joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (768,'Ivory osteoma','Ivory osteoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (769,'Loose Bodies in Knee joint','Loose Bodies in Knee joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (770,'Sacro- iliac Arthritis','Sacro- iliac Arthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (771,'Sacro- iliac Strain','Sacro- iliac Strain',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (772,'Juvenile Rheumatoid arthritis','Juvenile Rheumatoid arthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (773,'Kipple- Feil Syndrome','Kipple- Feil Syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (774,'Klumpke’s paralysis','Klumpke’s paralysis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (775,'Tuberculous arthritis Hip joint','Tuberculous arthritis Hip joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (776,'Tuberculous arthritis Knee joint','Tuberculous arthritis Knee joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (777,'Charcot’s Disease','Charcot’s Disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (778,'Osteochondritis Dissecans','Osteochondritis Dissecans',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (779,'Knock Knee','Knock Knee',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (780,'Kyphosis','Kyphosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (781,'Adolescent Kyphosis','Adolescent Kyphosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (782,'Senile Kyphosis','Senile Kyphosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (783,'Tuberculous Kyphosis','Tuberculous Kyphosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (784,'Legg-Perthes Disease','Legg-Perthes Disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (785,'Letterer –Siwe Disease','Letterer –Siwe Disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (786,'Madelung’s Deformity','Madelung’s Deformity',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (787,'Mal- Union','Mal- Union',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (788,'Marbel Bone Disease','Marbel Bone Disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (789,'March Fracture','March Fracture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (790,'Median never injury','Median never injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (791,'Median never injury at Elbow','Median never injury at Elbow',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (792,'Median never injury at Wrist','Median never injury at Wrist',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (793,'Metastasis with Skeletal Secondary','Metastasis with Skeletal Secondary',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (794,'Metetersalgia','Metetersalgia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (795,'Monostotic fibrous dysplasia','Monostotic fibrous dysplasia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (796,'Morquio –Brailford Disease','Morquio –Brailford Disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (797,'Multiple myeloma','Multiple myeloma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (798,'Muscular dystrophy','Muscular dystrophy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (799,'Myositis ossificans','Myositis ossificans',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (800,'Axillary Nerve injury','Axillary Nerve injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (801,'Common peroneal nerve injury','Common peroneal nerve injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (802,'Lateral popliteal nerve injury','Lateral popliteal nerve injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (803,'Median nerve injury','Median nerve injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (804,'Radial nerve injury','Radial nerve injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (805,'Sciatic nerve injury','Sciatic nerve injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (806,'Ulnar nerve injury','Ulnar nerve injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (807,'Neuropraxia','Neuropraxia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (808,'Neuritis','Neuritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (809,'Neurofibromatosis','Neurofibromatosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (810,'Neuropathic joint','Neuropathic joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (811,'Non osteogenic fibroma','Non osteogenic fibroma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (812,'Non Union ','Non Union ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (813,'Non Union Femoral neck','Non Union Femoral neck',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (814,'Non Union Scaphoid','Non Union Scaphoid',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (815,'Nutritional rickets  ','Nutritional rickets  ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (816,'Ochronosis','Ochronosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (817,'Osteochondroma','Osteochondroma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (818,'Osteodystrophy','Osteodystrophy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (819,'Osteogenesis imperfecta','Osteogenesis imperfecta',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (820,'Osteonecrosis of femoral head','Osteonecrosis of femoral head',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (821,'Osteoid osteoma','Osteoid osteoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (822,'Osteomalacia','Osteomalacia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (823,'Acute haematogenous Osteomyelitis','Acute haematogenous Osteomyelitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (824,'Chronic Osteomyelitis','Chronic Osteomyelitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (825,'Pandiaphyseal Osteomyelitis','Pandiaphyseal Osteomyelitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (826,'Septic arthritis','Septic arthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (827,'Osteoporosis','Osteoporosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (828,'Osteosarcoma','Osteosarcoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (829,'Paget’s disease','Paget’s disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (830,'Painful arc syndrome ','Painful arc syndrome ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (831,'Traumatic Paraplegia','Traumatic Paraplegia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (832,'Pott’s Paraplegia','Pott’s Paraplegia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (833,'Chondromalacia Patella','Chondromalacia Patella',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (834,'Patella tendon avulsion','Patella tendon avulsion',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (835,'Pelvic ring disruption','Pelvic ring disruption',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (836,'Per-arthritis of shoulder','Per-arthritis of shoulder',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (837,'Supra spinatus tendinitis','Supra spinatus tendinitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (838,'Peripheral nerver injury','Peripheral nerver injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (839,'Perthe’s disease of hip','Perthe’s disease of hip',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (840,'Polyarthritis','Polyarthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (841,'Polyostotic fibrous dysplasia','Polyostotic fibrous dysplasia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (842,'Polytrauma','Polytrauma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (843,'Popliteal nerve injury','Popliteal nerve injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (844,'Post-traumatioc ossification','Post-traumatioc ossification',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (845,'Pressure sores','Pressure sores',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (846,'Pseudarthrosis if tibia','Pseudarthrosis if tibia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (847,'Psoriatic arthropathy','Psoriatic arthropathy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (848,'Pubic symphysis disruption','Pubic symphysis disruption',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (849,'Pulled elbow','Pulled elbow',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (850,'Psoas abscess','Psoas abscess',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (851,'Pyogenic arthritis ','Pyogenic arthritis ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (852,'Pyogenic arthritis of hip','Pyogenic arthritis of hip',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (853,'Pyogenic arthritis of knee','Pyogenic arthritis of knee',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (854,'Quadriceps Fibrosis','Quadriceps Fibrosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (855,'Quadriceps Rupture','Quadriceps Rupture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (856,'Quadriplegia-Cervical spine injury','Quadriplegia-Cervical spine injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (857,'Quadriplegia in pott’s Cervical spine','Quadriplegia in pott’s Cervical spine',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (858,'Proximal Radio ulnar joint Dislocation','Proximal Radio ulnar joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (859,'Distal Radio ulnar joint Dislocation','Distal Radio ulnar joint Dislocation',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (860,'Radial synotosis','Radial synotosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (861,'Radial Amelia ','Radial Amelia ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (862,'Subluxation of Radial head','Subluxation of Radial head',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (863,'Reiter’s Disease','Reiter’s Disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (864,'Renal Osteodystrophy','Renal Osteodystrophy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (865,'Reticulum cell Sarcoma','Reticulum cell Sarcoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (866,'Rickets','Rickets',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (867,'Rocker bottom foot','Rocker bottom foot',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (868,'Rotator cuff injury','Rotator cuff injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (869,'Rotator cuff Tear','Rotator cuff Tear',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (870,'Tendo Achilles tendon Rupture','Tendo Achilles tendon Rupture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (871,'Supraspinatus tendon Rupture','Supraspinatus tendon Rupture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (872,'Biceps tendon Rupture','Biceps tendon Rupture',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (873,'Anterior talo-fibular ligament strain','Anterior talo-fibular ligament strain',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (874,'Deltoid ligament strain of Ankle','Deltoid ligament strain of Ankle',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (875,'Medial Collateral ligament strain knee','Medial Collateral ligament strain knee',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (876,'Lateral Collateral ligament strain knee','Lateral Collateral ligament strain knee',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (877,'Medial Collateral ligament strain Elbow','Medial Collateral ligament strain Elbow',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (878,'Lateral Collateral ligament strain Elbow','Lateral Collateral ligament strain Elbow',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (879,'Ewing’s Sarcoma','Ewing’s Sarcoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (880,'Osteosarcoma','Osteosarcoma',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (881,'Saturday night palsy','Saturday night palsy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (882,'Scalene syndrome','Scalene syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (883,'Scheurmann’s disease','Scheurmann’s disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (884,'Sciatica','Sciatica',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (885,'Idiopathic structural Scoliosis','Idiopathic structural Scoliosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (886,'Paralytic Scoliosis','Paralytic Scoliosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (887,'Adolescent Scoliosis','Adolescent Scoliosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (888,'Scurvy ','Scurvy ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (889,'Semimembranous bursitits','Semimembranous bursitits',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (890,'Senile osteoporosis ','Senile osteoporosis ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (891,'Sever’s disease of calcaneum','Sever’s disease of calcaneum',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (892,'Spina bifida','Spina bifida',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (893,'Spinal cord injury','Spinal cord injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (894,'Lumbar canal stenosis','Lumbar canal stenosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (895,'Cervical canal stenosis','Cervical canal stenosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (896,'Spinal canal stenosis','Spinal canal stenosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (897,'Spondylolisthesis L5 over S1','Spondylolisthesis L5 over S1',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (898,'Sprengel’s shoulder','Sprengel’s shoulder',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (899,'Stills disease','Stills disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (900,'Subacromial bursitis','Subacromial bursitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (901,'Suprapatellar bursitis','Suprapatellar bursitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (902,'Infrapatellar bursitis','Infrapatellar bursitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (903,'Prepatellar bursitis','Prepatellar bursitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (904,'Popliteal bursitis','Popliteal bursitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (905,'Sudeck’s atrophy','Sudeck’s atrophy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (906,'Symphysis pubis disruption','Symphysis pubis disruption',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (907,'Synostosis radio-ulnar','Synostosis radio-ulnar',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (908,'Synovial chondromatosis','Synovial chondromatosis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (909,'CongenitalTalipes equino-varus','CongenitalTalipes equino-varus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (910,'Tabas dorsalis ','Tabas dorsalis ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (911,'Tardy ulnar palsy','Tardy ulnar palsy',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (912,'Tarsal Tunnal syndrome','Tarsal Tunnal syndrome',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (913,'Tibio fibular diastasis','Tibio fibular diastasis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (914,'Tibia varum','Tibia varum',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (915,'Hallux valgus deforming','Hallux valgus deforming',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (916,'Torticollis','Torticollis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (917,'Torticollis acquired','Torticollis acquired',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (918,'Torticollis congential','Torticollis congential',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (919,'Trigger finger','Trigger finger',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (920,'Trigger Thumb','Trigger Thumb',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (921,'Unicameral bone cyst','Unicameral bone cyst',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (922,'Urethra Rupture in pelvic injury','Urethra Rupture in pelvic injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (923,'Congenital Vertebral anomalies','Congenital Vertebral anomalies',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (924,'Vertical talus','Vertical talus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (925,'Von Recklinghausen’s disease','Von Recklinghausen’s disease',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (926,'Wrist Drop','Wrist Drop',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (927,'Foot drop ','Foot drop ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (928,'Acetabulum Fracture with central dislocation of hip joint','Acetabulum Fracture with central dislocation of hip joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (929,'Acetabulum Fracture with posterior dislocation of hip joint','Acetabulum Fracture with posterior dislocation of hip joint',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (930,'Achondroplasia','Achondroplasia',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (931,'Diaphysial Aclasis','Diaphysial Aclasis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (932,'Adolescent Coxa vara','Adolescent Coxa vara',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (933,'Amelia ','Amelia ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (934,'Alkaptonuric arthritis','Alkaptonuric arthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (935,'Ankylosing spondylitis','Ankylosing spondylitis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (936,'Tetanus','Tetanus',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (937,'Brachial Artery injury','Brachial Artery injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (938,'Popliteal Artery injury','Popliteal Artery injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (939,'Radial Artery injury','Radial Artery injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (940,'Axillary Artery injury','Axillary Artery injury',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (941,'Psoriatic Arthritis','Psoriatic Arthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (942,'Neuropathic Arthritis','Neuropathic Arthritis',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (943,'Neuropathic joint ','Neuropathic joint ',312)
INSERT INTO Complaint (ComplaintID, ComplaintName, ComplaintDesc, ParentID) VALUES (944,'Arthrogryposis multiplex congenita','Arthrogryposis multiplex congenita',312)
