Delete InvestigationOrgMapping where OrgID=17
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5330,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5331,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5332,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5333,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5334,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5335,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5336,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5337,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5338,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5339,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5340,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5341,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5342,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5343,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5344,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5345,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5346,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5347,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5348,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5349,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5350,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5351,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5352,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5353,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5354,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5355,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5356,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5357,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5358,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5359,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5360,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5361,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5362,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5363,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5364,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5365,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5366,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5367,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5368,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5369,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5370,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5371,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5372,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5373,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5374,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5375,17,502,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5376,17,502,10)
-------------------------------------------------------------------------------------------------------
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5377,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5378,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5379,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5380,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5381,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5382,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5383,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5384,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5385,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5386,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5387,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5388,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5389,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5390,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5391,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5392,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5393,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5394,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5395,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5396,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5397,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5398,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5399,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5400,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5401,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5402,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5403,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5404,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5405,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5406,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5407,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5408,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5409,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5410,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5411,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5412,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5413,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5414,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5415,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5416,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5417,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5418,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5419,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5420,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5421,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5422,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5423,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5424,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5425,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5426,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5427,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5428,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5429,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5430,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5431,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5432,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5433,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5434,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5435,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5436,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5437,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5438,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5439,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5440,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5441,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5442,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5443,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5444,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5445,17,503,10)
--INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5446,17,503,10)
--------------------------------------------------------------------------------------------------------------
--After Header Include
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5330,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5331,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5332,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5333,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5334,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5335,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5336,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5337,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5338,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5339,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5340,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5341,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5342,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5343,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5344,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5345,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5346,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5347,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5348,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5349,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5350,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5351,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5352,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5353,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5354,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5355,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5356,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5357,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5358,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5359,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5360,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5361,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5362,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5363,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5364,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5365,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5366,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5367,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5368,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5369,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5370,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5371,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5372,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5373,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5374,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5375,17,502,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5376,17,502,10)
-----------------------------------------------------------------------------------------------------
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5377,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5378,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5379,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5380,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5381,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5382,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5383,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5384,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5385,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5386,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5387,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5388,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5389,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5390,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5391,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5392,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5393,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5394,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5395,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5396,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5397,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5398,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5399,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5400,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5401,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5402,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5403,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5404,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5405,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5406,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5407,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5408,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5409,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5410,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5411,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5412,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5413,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5414,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5415,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5416,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5417,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5418,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5419,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5420,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5421,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5422,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5423,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5424,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5425,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5426,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5427,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5428,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5429,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5430,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5431,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5432,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5433,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5434,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5435,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5436,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5437,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5438,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5439,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5440,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5441,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5442,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5443,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5444,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5445,17,503,10)
INSERT INTO InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID) VALUES (5446,17,503,10)

----Finish

--Other Investigation
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4720,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2011,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4014,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4724,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4511,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4196,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4197,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3136,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4746,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4173,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4174,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4195,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4757,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2031,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2043,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4783,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3018,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4093,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4019,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4018,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4781,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4911,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4334,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4220,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2045,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4345,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4755,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4925,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4766,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4767,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4143,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4430,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2046,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4298,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4787,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4130,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4467,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4803,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4361,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4419,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4816,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2055,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2026,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4813,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4383,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4819,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4391,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4402,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4789,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4308,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4825,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4826,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4289,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5167,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2012,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3007,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3008,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3035,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3037,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3032,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3033,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3040,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3041,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4732,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3064,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3009,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3057,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4836,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4758,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4735,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4763,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4764,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3080,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3082,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4777,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4778,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4821,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3123,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3122,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4844,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3117,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3119,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4333,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4089,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4092,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4800,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4091,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4016,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4419,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4417,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4415,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5085,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4233,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3090,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4129,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3072,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4854,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4740,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5001,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4739,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4458,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4780,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5029,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4172,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4290,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3066,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4803,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4357,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3069,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4845,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3066,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4454,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3070,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4410,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4135,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4726,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4312,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4304,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4369,17,501,NULL)

----Other investiagtion remaining
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4720,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4723,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5451,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5452,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4404,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4183,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4782,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5093,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4753,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4243,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4967,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5453,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5454,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2013,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4281,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3122,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4289,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5455,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4843,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4765,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3009,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4780,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4725,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3048,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3049,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4735,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4357,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4829,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4748,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4223,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4825,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4838,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4839,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4777,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4778,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3086,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4821,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3123,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4844,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3117,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4097,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4739,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4740,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4772,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5456,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4842,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4840,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4841,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4088,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4750,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4786,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4892,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4891,17,501,NULL)
 
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4775,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4458,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4344,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4801,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4342,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4947,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4466,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4343,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4290,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4826,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4335,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4625,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4334,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2046,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5457,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5045,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4152,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4063,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4060,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4062,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4814,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4999,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4759,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4249,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4796,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4820,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4752,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4804,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4331,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4793,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4784,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5016,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4016,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4037,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4039,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4143,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5458,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4721,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4038,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5459,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4882,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4020,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4452,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4023,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4401,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5460,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4862,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5461,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4145,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4273,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2055,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4394,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3084,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4938,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4129,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4974,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4167,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4817,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4297,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5462,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4228,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3095,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4186,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5463,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4173,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5464,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5465,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4409,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4755,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4789,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4425,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4429,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5466,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4388,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5045,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4380,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4872,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4728,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5467,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4421,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4446,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4355,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4360,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4319,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5468,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5469,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4239,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4220,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4824,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4757,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4734,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4224,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5294,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5470,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4374,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3114,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3116,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4177,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4178,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4333,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4462,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5001,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5471,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4953,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4041,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4465,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4226,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4172,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4192,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4408,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5472,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4831,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4832,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5473,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5474,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5475,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5476,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3089,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5477,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4865,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3038,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4805,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5478,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5479,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5480,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5481,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5482,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4411,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5483,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5484,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2003,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4830,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4853,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4854,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5485,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4423,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4453,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4861,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5032,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4435,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4005,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5486,17,501,NULL)
------------------
--Ultra sound
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4506,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5487,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5488,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4709,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5489,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5490,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5491,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5492,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5493,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5494,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5495,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5496,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5497,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5498,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5499,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5500,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5501,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5502,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5503,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5504,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5505,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5506,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5507,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5508,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5509,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5510,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5511,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5512,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5513,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5514,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5515,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5516,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5517,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5518,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5519,17,506,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5520,17,506,10)

---Xray
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,Display)values(4668,17,NULL,NULL,'N')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4517,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5521,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4650,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5522,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5523,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5524,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4654,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5525,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5526,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5527,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5528,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5529,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4531,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4539,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5530,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5531,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4530,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5532,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4640,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5533,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4513,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5534,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5535,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5536,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4653,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5537,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5538,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4514,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5539,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5540,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4525,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5541,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5542,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5271,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4646,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5543,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4658,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5544,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4522,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5545,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5546,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5547,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5548,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4532,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5549,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5550,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5551,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5552,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5553,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5554,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4668,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5555,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5556,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5557,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4501,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5558,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5559,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5560,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5561,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4494,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5562,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5563,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5262,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5564,17,505,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5565,17,505,10)
--Investigations
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2014,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4876,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4763,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2033,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4811,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4810,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3073,17,501,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4742,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4132,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4889,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4004,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4010,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4011,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4017,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4430,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3031,17,501,NULL)

--new one
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4768,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4460,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4856,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4857,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4807,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4776,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4190,17,501,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4773,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5033,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4808,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4190,17,501,NULL)
--fluid analysis
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4396,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4622,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4392,17,501,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4963,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5567,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(1007,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3039,17,501,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4222,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5196,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3130,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5586,17,501,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5043,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5044,17,501,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5046,17,501,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5587,17,501,NULL)