DELETE FROM InvRateMaster WHERE Type='LCON' AND ID IN (1,2,3,4,5,6)
INSERT INTO InvRateMaster(Type,ClientID,ID,rate)VALUES('LCON',NULL,1,20)
INSERT INTO InvRateMaster(Type,ClientID,ID,rate)VALUES('LCON',NULL,2,15)
INSERT INTO InvRateMaster(Type,ClientID,ID,rate)VALUES('LCON',NULL,3,10)
INSERT INTO InvRateMaster(Type,ClientID,ID,rate)VALUES('LCON',NULL,4,10)
INSERT INTO InvRateMaster(Type,ClientID,ID,rate)VALUES('LCON',NULL,5,25)
INSERT INTO InvRateMaster(Type,ClientID,ID,rate)VALUES('LCON',NULL,6,15)
INSERT INTO InvRateMaster(Type,ClientID,ID,rate)VALUES('LCON',NULL,7,0)
INSERT INTO InvRateMaster(Type,ClientID,ID,rate)VALUES('LCON',NULL,8,80)
