TRUNCATE TABLE UOM
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(1,'&#176;C','deg Celcius')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(2,'mmHg','mmHg')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(3,'bpm','Beats Per Minite')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(4,'cm','Centimeters')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(5,'kg','Kilograms')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(6,'units','Units')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(7,'ltrs','Liters')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(8,'&#176;F','deg Farenheit')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(9,'ml/hr','ml per hour')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(10,'mm/30 min','mm per minute')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(11,'mm/hr','mm per hour')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(12,'%','percentage')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(13,'gm%','percentage')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(14,'cells/cu.mm','cells per cumm')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(15,'10<sup>6</sup>/cumm','10 power 6 per cumm')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(16,'µm<sup>3</sup>','')---
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(17,'g/dl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(18,'pg/cell','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(19,'mins','minutes')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(20,'secs','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(23,'µg/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(24,'mg/dl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(25,'mg%','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(26,'mg','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(27,'gm','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(28,'units/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(29,'mg/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(30,'µg/dl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(31,'cells/HPF','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(32,'eosinophils/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(33,'ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(34,'mg/day','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(35,'&#181;g/mg','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(36,'&#181;g/day','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(37,'pg/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(38,'&#181;units/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(39,'pg/dl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(40,'&#181;g/24 hrs','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(41,'m/u/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(42,'gm/day','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(43,'mg/g','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(44,'IU/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(45,'/HPF','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(46,'million/cmm','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(47,'mg/24 hr urine','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(48,'mIU/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(49,'cell/mcl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(50,'ml/min','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(51,'IU/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(52,'mg/d','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(53,'breaths/min','breaths/min')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(54,'meg/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(55,'ng/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(56,'U/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(57,'mEq/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(58,'ng/dl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(59,'meq/day','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(60,'Cells/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(61,'g/l','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(62,'ng/dl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(63,'Mg/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(64,'Microg/dl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(65,'mIU/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(66,'mOsm/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(67,'GPl U/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(68,'Mpl U/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(69,'APl U/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(70,'U/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(71,'%','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(72,'Units/gm of HB','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(73,'h','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(74,'mg/dl of Ejaculate','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(75,'mcg/day','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(76,'Microgram/l','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(77,'Micromol/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(78,'Mmol/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(79,'globules/HPF','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(80,'eosinophils/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(81,'microg/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(82,'U/h','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(83,'µ<sup>3</sup>/mm<sup>3</sup>','Micro Power 3')--
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(84,'per mm<sup>3</sup>','')--
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(85,'miU/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(86,'cells/cubic mm','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(87,'mg/mmol','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(88,'EU/ML','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(89,'mcg/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(90,'mcg/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(91,'microIU/ml','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(92,'mcg/dl','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(93,'% Fe in RBC','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(94,'fL','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(95,'Ng/24 h','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(96,'Mcg/24 h','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(97,'cells/mcL','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(98,'U/g of Hb','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(99,'ng/L','')
Insert into UOM (UOMID,UOMCode,UOMDescription)  values(100,'PanBio Units','')






