Truncate table PatternMapping

insert into PatternMapping  (PatternID,InvestigationID) values(1,4820)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4758)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4752)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3007)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3008)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3009)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4783)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4781)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4782)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3014)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3015)
--insert into PatternMapping  (PatternID,InvestigationID) values(5,3016)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3018)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4765)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4753)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3021)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3022)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3024)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3025)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3026)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3027)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,3028)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3029)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3032)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3033)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3034)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3036)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3037)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3038)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3039)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3040)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3041)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4732)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4780)
--insert into PatternMapping  (PatternID,InvestigationID) values(2,3044)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4853)
insert into PatternMapping  (PatternID,InvestigationID) values(2,4854)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3049)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3050)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4804)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4759)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4805)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4796)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4460)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3057)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3058)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,4735)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3061)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3062)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4803)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3064)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4845)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3066)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3067)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3068)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3069)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3070)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3072)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3073)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4757)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4734)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3076)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4777)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3080)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3081)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3082)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4778)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3084)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3085)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3086)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3087)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3090)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3089)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3091)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3092)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4754)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3095)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3096)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3097)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3098)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3099)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3100)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3101)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3102)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3103)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3104)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3105)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3106)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3108)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4726)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4843)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4844)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3114)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3115)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3116)
insert into PatternMapping  (PatternID,InvestigationID) values(2,3117)
insert into PatternMapping  (PatternID,InvestigationID) values(2,4720)
insert into PatternMapping  (PatternID,InvestigationID) values(2,3119)
insert into PatternMapping  (PatternID,InvestigationID) values(2,3120)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4821)
insert into PatternMapping  (PatternID,InvestigationID) values(2,3122)
insert into PatternMapping  (PatternID,InvestigationID) values(2,3123)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,3124)
insert into PatternMapping  (PatternID,InvestigationID) values(4,3126)
insert into PatternMapping  (PatternID,InvestigationID) values(3,3128)
insert into PatternMapping  (PatternID,InvestigationID) values(3,3129)
--insert into PatternMapping  (PatternID,InvestigationID) values(3,3130)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3130)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4816)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3132)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3133)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3134)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3135)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3136)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4813)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4831)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4787)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4876)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2005)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2006)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2007)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2008)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2009)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2010)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2011)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2012)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,2015)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2032)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2033)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4811)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4810)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4290)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2046)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4746)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4825)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2051)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4826)
insert into PatternMapping  (PatternID,InvestigationID) values(10,2020)
insert into PatternMapping  (PatternID,InvestigationID) values(10,2021)
insert into PatternMapping  (PatternID,InvestigationID) values(10,2022)
insert into PatternMapping  (PatternID,InvestigationID) values(7,2031)
insert into PatternMapping  (PatternID,InvestigationID) values(7,4273)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,2045)
insert into PatternMapping  (PatternID,InvestigationID) values(34,2045)
insert into PatternMapping  (PatternID,InvestigationID) values(7,4345)
--insert into PatternMapping  (PatternID,InvestigationID) values(7,2055)
insert into PatternMapping  (PatternID,InvestigationID) values(3,2049)
--insert into PatternMapping  (PatternID,InvestigationID) values(10,2053)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4728)
--insert into PatternMapping  (PatternID,InvestigationID) values(3,2039)
insert into PatternMapping  (PatternID,InvestigationID) values(3,2040)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,2043)
insert into PatternMapping  (PatternID,InvestigationID) values(34,2043)
insert into PatternMapping  (PatternID,InvestigationID) values(9,2028)
insert into PatternMapping  (PatternID,InvestigationID) values(9,2029)
insert into PatternMapping  (PatternID,InvestigationID) values(8,2017)
insert into PatternMapping  (PatternID,InvestigationID) values(8,2018)
insert into PatternMapping  (PatternID,InvestigationID) values(8,2019)
insert into PatternMapping  (PatternID,InvestigationID) values(12,2030)
insert into PatternMapping  (PatternID,InvestigationID) values(11,4872)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,2047)
insert into PatternMapping  (PatternID,InvestigationID) values(9,2025)
insert into PatternMapping  (PatternID,InvestigationID) values(9,2026)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2013)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2058)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4832)
insert into PatternMapping  (PatternID,InvestigationID) values(6,1006)
insert into PatternMapping  (PatternID,InvestigationID) values(6,1007)
insert into PatternMapping  (PatternID,InvestigationID) values(30,1008)
insert into PatternMapping  (PatternID,InvestigationID) values(30,1009)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4797)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4798)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4836)
insert into PatternMapping  (PatternID,InvestigationID) values(1,2014)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4003)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4004)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4005)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4007)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4008)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4009)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4010)
insert into PatternMapping  (PatternID,InvestigationID) values(16,4011)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4012)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4014)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4015)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4016)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4017)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4018)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4019)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4020)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4021)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,4022)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4023)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4024)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4026)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4027)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4028)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4029)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4030)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4031)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4033)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4035)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4036)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4037)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4038)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4039)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4721)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4041)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4042)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4043)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4044)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4046)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4047)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4048)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4049)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4051)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4052)
insert into PatternMapping  (PatternID,InvestigationID) values(15,4768)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4057)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4058)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4060)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4061)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4062)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4063)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4064)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4065)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,4067)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4068)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4069)
--insert into PatternMapping  (PatternID,InvestigationID) values(13,4070)
--insert into PatternMapping  (PatternID,InvestigationID) values(13,4071)
--insert into PatternMapping  (PatternID,InvestigationID) values(13,4072)
insert into PatternMapping  (PatternID,InvestigationID) values(9,4074)
--insert into PatternMapping  (PatternID,InvestigationID) values(8,4075)
insert into PatternMapping  (PatternID,InvestigationID) values(9,4076)
--insert into PatternMapping  (PatternID,InvestigationID) values(3,4080)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4081)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4084)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4085)

--insert into PatternMapping  (PatternID,InvestigationID) values(7,4084)
--insert into PatternMapping  (PatternID,InvestigationID) values(7,4085)

--insert into PatternMapping  (PatternID,InvestigationID) values(6,4087)
--insert into PatternMapping  (PatternID,InvestigationID) values(6,4088)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4089)
--insert into PatternMapping  (PatternID,InvestigationID) values(3,4090)
--insert into PatternMapping  (PatternID,InvestigationID) values(7,4091)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4091)

insert into PatternMapping  (PatternID,InvestigationID) values(3,4092)
--insert into PatternMapping  (PatternID,InvestigationID) values(3,4772)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4100)
--insert into PatternMapping  (PatternID,InvestigationID) values(3,4740)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4104)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4105)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4106)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4107)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4108)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4110)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4112)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4113)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4114)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4115)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4116)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4118)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4119)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4120)
--insert into PatternMapping  (PatternID,InvestigationID) values(17,4097)
insert into PatternMapping  (PatternID,InvestigationID) values(18,4093)
insert into PatternMapping  (PatternID,InvestigationID) values(16,4086)
insert into PatternMapping  (PatternID,InvestigationID) values(9,2024)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3048)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3035)


---Bse pattern mapping
insert into PatternMapping  (PatternID,InvestigationID) values(1,4735)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,4758)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4428)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4144)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,4445)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4401)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4885)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4169)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4175)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4772)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4790)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4322)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4889)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4324)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4177)

--insert into PatternMapping  (PatternID,InvestigationID) values(3,4897)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4192)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4902)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4906)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4907)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4908)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4204)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4909)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4910)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4911)
--insert into PatternMapping  (PatternID,InvestigationID) values(3,4272)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4272)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4352)
insert into PatternMapping  (PatternID,InvestigationID) values(7,4814)

--After Update
insert into PatternMapping  (PatternID,InvestigationID) values(1,4878)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4879)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4881)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4145)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4438)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4197)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4167)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4152)
--insert into PatternMapping  (PatternID,InvestigationID) values(29,4071)------------------
insert into PatternMapping  (PatternID,InvestigationID) values(3,4191)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4173)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4174)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4890)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4891)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4892)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4323)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4897)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4898)

insert into PatternMapping  (PatternID,InvestigationID) values(30,4363)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4097)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4185)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4186)

--insert into PatternMapping  (PatternID,InvestigationID) values(1,4091)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4071)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4841)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4840)

--insert into PatternMapping  (PatternID,InvestigationID) values(28,4300)
--insert into PatternMapping  (PatternID,InvestigationID) values(22,4080)
--insert into PatternMapping  (PatternID,InvestigationID) values(28,4299)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4208)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4291)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4913)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4880)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4425)
--After 101
insert into PatternMapping  (PatternID,InvestigationID) values(3,4412)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4917)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4220)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4624)

insert into PatternMapping  (PatternID,InvestigationID) values(22,4922)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4923)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4920)


insert into PatternMapping  (PatternID,InvestigationID) values(1,4229)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4925)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4230)
--insert into PatternMapping  (PatternID,InvestigationID) values(23,4232)
insert into PatternMapping  (PatternID,InvestigationID) values(23,4392)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4927)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4241)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4246)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4247)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4930)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4461)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4934)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4935)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4936)
--insert into PatternMapping  (PatternID,InvestigationID) values(22,4156)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4464)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4937)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4938)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4342)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4284)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4289)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4775)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4130)

--After 200
insert into PatternMapping  (PatternID,InvestigationID) values(29,4334)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,4335)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4282)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,4067)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4344)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4343)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4349)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4339)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4950)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4360)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4951)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4952)
insert into PatternMapping  (PatternID,InvestigationID) values(3,2055)
insert into PatternMapping  (PatternID,InvestigationID) values(7,4361)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4953)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4956)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4958)
insert into PatternMapping  (PatternID,InvestigationID) values(28,4300)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4299)
--insert into PatternMapping  (PatternID,InvestigationID) values(21,4464)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4960)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4389)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4962)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4963)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4965)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4819)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4967)
--insert into PatternMapping  (PatternID,InvestigationID) values(22,4156)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4968)
insert into PatternMapping  (PatternID,InvestigationID) values(22,4784)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4402)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4972)
--insert into PatternMapping  (PatternID,InvestigationID) values(21,4299)
--insert into PatternMapping  (PatternID,InvestigationID) values(22,4156)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4974)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4975)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4977)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4978)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4408)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4298)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4982)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4725)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4984)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4750)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4223)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4985)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4986)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4233)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4239)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4249)
insert into PatternMapping  (PatternID,InvestigationID) values(7,4254)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4388)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4991)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4318)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,4992)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4992)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4335)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4993)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4467)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4357)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4410)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4394)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4995)
--insert into PatternMapping  (PatternID,InvestigationID) values(28,4300)
insert into PatternMapping  (PatternID,InvestigationID) values(22,4730)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4997)

insert into PatternMapping  (PatternID,InvestigationID) values(3,4998)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4999)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5000)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5001)
insert into PatternMapping  (PatternID,InvestigationID) values(22,4415)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4417)
--insert into PatternMapping  (PatternID,InvestigationID) values(28,4300)
--insert into PatternMapping  (PatternID,InvestigationID) values(21,4299)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5002)

insert into PatternMapping  (PatternID,InvestigationID) values(27,5003)
insert into PatternMapping  (PatternID,InvestigationID) values(27,5004)
--insert into PatternMapping  (PatternID,InvestigationID) values(27,5005)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4419)
--insert into PatternMapping  (PatternID,InvestigationID) values(13,4368)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5006)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4312)
--insert into PatternMapping  (PatternID,InvestigationID) values(22,4156)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5009)
--insert into PatternMapping  (PatternID,InvestigationID) values(22,4080)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5010)
insert into PatternMapping  (PatternID,InvestigationID) values(21,4423)

insert into PatternMapping  (PatternID,InvestigationID) values(30,5012)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5013)

insert into PatternMapping  (PatternID,InvestigationID) values(21,4424)
insert into PatternMapping  (PatternID,InvestigationID) values(28,5015)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5016)

insert into PatternMapping  (PatternID,InvestigationID) values(21,4435)

insert into PatternMapping  (PatternID,InvestigationID) values(21,5021)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5023)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5024)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4625)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4445)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5036)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5037)

--insert into PatternMapping  (PatternID,InvestigationID) values(14,4252)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4252)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4943)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4944)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4945)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4946)

--insert into PatternMapping  (PatternID,InvestigationID) values(13,5047)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5047)
--insert into PatternMapping  (PatternID,InvestigationID) values(13,5048)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5048)

insert into PatternMapping  (PatternID,InvestigationID) values(29,5049)
insert into PatternMapping  (PatternID,InvestigationID) values(29,5050)
insert into PatternMapping  (PatternID,InvestigationID) values(29,5051)
insert into PatternMapping  (PatternID,InvestigationID) values(29,5052)
insert into PatternMapping  (PatternID,InvestigationID) values(29,5053)
insert into PatternMapping  (PatternID,InvestigationID) values(29,5054)

insert into PatternMapping  (PatternID,InvestigationID) values(1,5055)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5056)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5057)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5058)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5059)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5060)

--insert into PatternMapping  (PatternID,InvestigationID) values(13,5061)
--insert into PatternMapping  (PatternID,InvestigationID) values(13,5062)

insert into PatternMapping  (PatternID,InvestigationID) values(23,5043)
insert into PatternMapping  (PatternID,InvestigationID) values(24,5044)
insert into PatternMapping  (PatternID,InvestigationID) values(25,5045)
insert into PatternMapping  (PatternID,InvestigationID) values(26,5046)
insert into PatternMapping  (PatternID,InvestigationID) values(1,3031)

insert into PatternMapping  (PatternID,InvestigationID) values(1,4801)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,5062)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,5063)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5064)
--insert into PatternMapping  (PatternID,InvestigationID) values(1,5065)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5066)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5067)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5068)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5069)

insert into PatternMapping  (PatternID,InvestigationID) values(13,4740)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4739)

insert into PatternMapping  (PatternID,InvestigationID) values(30,5072)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4766)

--After bug
insert into PatternMapping  (PatternID,InvestigationID) values(1,4426)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4882)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4172)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4723)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4887)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4733)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4904)

--After doubt
insert into PatternMapping  (PatternID,InvestigationID) values(30,4087)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4088)

--insert into PatternMapping  (PatternID,InvestigationID) values(30,5074)
--insert into PatternMapping  (PatternID,InvestigationID) values(30,5075)

--insert into PatternMapping  (PatternID,InvestigationID) values(30,5076)
--insert into PatternMapping  (PatternID,InvestigationID) values(30,5077)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4829)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5017)
insert into PatternMapping  (PatternID,InvestigationID) values(7,5018)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4430)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5022)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5025)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5026)
--insert into PatternMapping  (PatternID,InvestigationID) values(13,5027)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5027)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4441)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5032)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5033)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4452)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5038)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4458)

insert into PatternMapping  (PatternID,InvestigationID) values(30,4193)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4194)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5080)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4313)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5028)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4449)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4453)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4196)
--Remain
insert into PatternMapping  (PatternID,InvestigationID) values(1,4903)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5401)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4921)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4800)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4947)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4365)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4966)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4969)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4970)
insert into PatternMapping  (PatternID,InvestigationID) values(22,4996)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4427)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5081)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5082)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5083)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5029)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5031)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4442)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5034)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4333)

--viral makers
insert into PatternMapping  (PatternID,InvestigationID) values(29,4132)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4742)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4135)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4129)

insert into PatternMapping  (PatternID,InvestigationID) values(29,4179)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4178)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4799)
insert into PatternMapping  (PatternID,InvestigationID) values(29,4133)
insert into PatternMapping  (PatternID,InvestigationID) values(31,5085)

------
insert into PatternMapping  (PatternID,InvestigationID) values(21,5041)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4622)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4055)

--Biopsy
insert into PatternMapping  (PatternID,InvestigationID) values(20,5092)
insert into PatternMapping  (PatternID,InvestigationID) values(20,5093)

--New investigation for pattern mapping dont del
insert into PatternMapping  (PatternID,InvestigationID) values(23,5157)
insert into PatternMapping  (PatternID,InvestigationID) values(28,5158)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5159)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5160)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5161)
insert into PatternMapping  (PatternID,InvestigationID) values(23,5162)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5163)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5164)
insert into PatternMapping  (PatternID,InvestigationID) values(23,5165)
--insert into PatternMapping  (PatternID,InvestigationID) values(23,5166)
insert into PatternMapping  (PatternID,InvestigationID) values(23,5167)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5171)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5172)
																 
insert into PatternMapping  (PatternID,InvestigationID) values(28,5173)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5174)
insert into PatternMapping  (PatternID,InvestigationID) values(28,5175)
																 
insert into PatternMapping  (PatternID,InvestigationID) values(22,5180)
insert into PatternMapping  (PatternID,InvestigationID) values(28,5181)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5182)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5183)
insert into PatternMapping  (PatternID,InvestigationID) values(28,5169)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5184)
															   

--insert into PatternMapping  (PatternID,InvestigationID) values(5178,
--insert into PatternMapping  (PatternID,InvestigationID) values(5179,

insert into PatternMapping  (PatternID,InvestigationID) values(1,5185)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5186)

--Bugtracking 5
insert into PatternMapping  (PatternID,InvestigationID) values(1,4855)


--newly added after readiness
insert into PatternMapping  (PatternID,InvestigationID) values(3,5196)
--culture for ear
insert into PatternMapping  (PatternID,InvestigationID) values(21,5193)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5194)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5195)
--hba1c
insert into PatternMapping  (PatternID,InvestigationID) values(1,4789)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4830)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4859)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4980)
--Metabolic work up
insert into PatternMapping  (PatternID,InvestigationID) values(1,4336)
--bose live
insert into PatternMapping  (PatternID,InvestigationID) values(3,5263)
--bose live
insert into PatternMapping  (PatternID,InvestigationID) values(3,4450)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4863)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5187)
--bose live
insert into PatternMapping  (PatternID,InvestigationID) values(3,5188)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5189)

--Scan
insert into PatternMapping  (PatternID,InvestigationID) values(32,5264)

insert into PatternMapping  (PatternID,InvestigationID) values(32,5265)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5266)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5267)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5268)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5269)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5270)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5271)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5272)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5273)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5274)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5275)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5276)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5277)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5278)
--insert into PatternMapping  (PatternID,InvestigationID) values(32,5279)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5280)
--insert into PatternMapping  (PatternID,InvestigationID) values(32,5281)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5282)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5283)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5284)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5285)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5286)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5287)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5288)

--Bug tracker 6
insert into PatternMapping  (PatternID,InvestigationID) values(28,5289)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5007)

--Mrg
insert into PatternMapping  (PatternID,InvestigationID) values(1,5290)

insert into PatternMapping  (PatternID,InvestigationID) values(22,5291)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5292)


--ph-smear
insert into PatternMapping  (PatternID,InvestigationID) values(33,4391)
--BugTracker 7
insert into PatternMapping  (PatternID,InvestigationID) values(22,5299)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5300)

insert into PatternMapping  (PatternID,InvestigationID) values(22,5302)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5303)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5304)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5305)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5306)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5307)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5308)
insert into PatternMapping  (PatternID,InvestigationID) values(28,5309)
insert into PatternMapping  (PatternID,InvestigationID) values(22,4416)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5310)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5311)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5312)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5313)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5314)
insert into PatternMapping  (PatternID,InvestigationID) values(22,5315)
insert into PatternMapping  (PatternID,InvestigationID) values(21,5316)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5192)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4432)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4368)

-----MRI AN CT for aarthi
insert into PatternMapping  (PatternID,InvestigationID) values(32,5330)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5331)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5332)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5333)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5334)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5335)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5336)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5337)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5338)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5339)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5340)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5341)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5342)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5343)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5344)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5345)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5346)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5347)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5348)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5349)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5350)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5351)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5352)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5353)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5354)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5355)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5356)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5357)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5358)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5359)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5360)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5361)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5362)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5363)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5364)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5365)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5366)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5367)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5368)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5369)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5370)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5371)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5372)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5373)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5374)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5375)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5376)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5377)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5378)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5379)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5380)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5381)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5382)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5383)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5384)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5385)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5386)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5387)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5388)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5389)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5390)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5391)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5392)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5393)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5394)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5395)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5396)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5397)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5398)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5399)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5400)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5402)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5403)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5404)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5405)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5406)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5407)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5408)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5409)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5410)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5411)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5412)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5413)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5414)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5415)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5416)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5417)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5418)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5419)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5420)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5421)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5422)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5423)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5424)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5425)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5426)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5427)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5428)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5429)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5430)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5431)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5432)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5433)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5434)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5435)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5436)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5437)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5438)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5439)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5440)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5441)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5442)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5443)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5444)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5445)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5446)

-----Xray and Ultra Sound
insert into PatternMapping  (PatternID,InvestigationID) values(32,4506)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5487)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5488)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4709)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5489)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5490)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5491)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5492)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5493)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5494)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5495)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5496)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5497)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5498)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5499)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5500)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5501)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5502)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5503)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5504)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5505)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5506)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5507)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5508)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5509)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5510)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5511)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5512)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5513)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5514)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5515)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5516)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5517)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5518)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5519)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5520)

---Xray
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,Heay)values(4668,17,NULL,NULL,'N')
insert into PatternMapping  (PatternID,InvestigationID) values(32,4517)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5521)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4650)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5522)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5523)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5524)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4654)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5525)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5526)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5527)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5528)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5529)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4531)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4539)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5530)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5531)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4530)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5532)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4640)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5533)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4513)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5534)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5535)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5536)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4653)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5537)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5538)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4514)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5539)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5540)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4525)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5541)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5542)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4646)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5543)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4658)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5544)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4522)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5545)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5546)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5547)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5548)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4532)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5549)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5550)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5551)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5552)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5553)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5554)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4668)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5555)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5556)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5557)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4501)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5558)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5559)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5560)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5561)
insert into PatternMapping  (PatternID,InvestigationID) values(32,4494)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5562)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5563)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5262)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5564)
insert into PatternMapping  (PatternID,InvestigationID) values(32,5565)

--Bose
insert into PatternMapping  (PatternID,InvestigationID) values(29,5567)
insert into PatternMapping  (PatternID,InvestigationID) values(29,5568)
insert into PatternMapping  (PatternID,InvestigationID) values(29,5569)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5570)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5571)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4861)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5572)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5573)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5574)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4767)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5575)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4226)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4358)



--New patternMapping
insert into PatternMapping  (PatternID,InvestigationID) values(1,2003)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4143)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4183)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4195)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4224)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4228)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4243)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4281)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4297)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4319)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4331)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4355)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4369)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4374)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4304)
insert into PatternMapping  (PatternID,InvestigationID) values(20,4308)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4404)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4411)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4421)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4429)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4446)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4454)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4724)
insert into PatternMapping  (PatternID,InvestigationID) values(13,4462)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4465)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4466)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4748)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4755)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4763)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4764)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4786)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4817)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4824)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4793)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5294)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5451)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5452)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5453)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5454)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5456)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5457)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5458)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5459)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5460)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5462)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5463)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5464)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5465)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5466)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5467)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5468)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5469)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5470)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5471)
insert into PatternMapping  (PatternID,InvestigationID) values(27,5472)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5473)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5474)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5475)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5476)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5477)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5478)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5479)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5480)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5481)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5482)
insert into PatternMapping  (PatternID,InvestigationID) values(1,5483)
insert into PatternMapping  (PatternID,InvestigationID) values(30,5485)
insert into PatternMapping  (PatternID,InvestigationID) values(3,5486)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4838)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4839)
insert into PatternMapping  (PatternID,InvestigationID) values(30,4842)
insert into PatternMapping  (PatternID,InvestigationID) values(1,4862)
insert into PatternMapping  (PatternID,InvestigationID) values(3,4865)

--DDC Pattern Mapping Starts
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4142)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (22,4147)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4153)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4154)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4157)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4160)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (22,4162)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4163)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4166)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4168)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4170)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4176)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4180)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4181)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4182)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4184)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4187)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4188)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4189)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4190)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4198)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4199)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (13,4200)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4207)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4211)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4212)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (25,4213)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4215)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4216)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4221)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4222)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4227)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4234)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4235)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4236)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4237)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4238)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4242)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4244)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (13,4245)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4258)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4259)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4260)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4261)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4262)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4263)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4264)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4266)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4267)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4268)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4275)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4280)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4283)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4285)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4288)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4293)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (22,4301)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4302)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (22,4305)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4306)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4309)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4311)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4314)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4315)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4316)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4317)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4320)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4325)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4326)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4327)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4328)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4330)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4332)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4338)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4346)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4347)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4348)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4350)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4354)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4356)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4362)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4364)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (22,4366)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (22,4367)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4370)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4371)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4372)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (13,4373)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4375)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4376)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4377)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (21,4378)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4379)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4384)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4385)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4386)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4387)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4390)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4393)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4398)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4399)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4400)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4403)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4405)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4406)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4414)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4418)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4420)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4422)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4434)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4437)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4439)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4440)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4443)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4444)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4447)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4448)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4451)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4456)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4457)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4459)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (28,4463)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4553)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4554)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4555)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4556)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4557)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4558)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4559)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4560)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4561)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4562)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4563)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4564)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4565)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4566)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4567)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4572)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4573)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4574)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4576)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4577)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4583)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4584)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4585)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4587)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4588)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4589)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4590)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4591)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4592)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4593)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4594)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4595)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4581)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4582)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4568)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4598)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4599)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4586)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4603)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4604)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4605)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4606)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4607)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4608)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4609)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4610)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4611)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4722)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4727)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (22,4729)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4731)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4736)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4737)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4738)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4741)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4743)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4744)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4745)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (13,4747)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4751)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4756)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4760)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4761)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4762)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (13,4769)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4770)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4771)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4773)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4774)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4776)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4779)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4791)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4792)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4794)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4795)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4802)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4807)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4808)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4809)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4815)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4818)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4822)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4823)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (13,4828)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4837)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4846)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4847)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4848)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4849)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (13,4850)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4851)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4852)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4856)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4857)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4858)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,4860)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4864)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4866)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4867)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (13,4868)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,4869)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4870)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4874)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4875)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4877)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,5086)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (29,5087)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (22,5295)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,5296)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,5301)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,5449)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (30,5566)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4146)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,4151)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,5576)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4214)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (3,4165)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4550)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (20,4579)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (31,4749)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,5577)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,5578)
INSERT INTO PatternMapping (PatternID,InvestigationID) VALUES (1,5579)


