delete drugbrand where orgid=14
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'pencillin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Ampicillin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Ampicillin+Sulbactum',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Amoxycillin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Oxacilin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Amoxycillin + Clavulanic acid',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Piperacillin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Polymyxin-B',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Erythromycin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Azithromycin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Roxythromycin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Aztreonam',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Lincomycin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Linezolid',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Clindamycin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Teicoplanin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Vancomycin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Imipenem',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Amikacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Gentamicin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Netilmicin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Tobramycin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Chloramphenicol',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Co-trimoxazole',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Tetracycline',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Co-trimoxazole',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'cephalothin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cephalexin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefazolin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefuroxime',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefepime',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefoperazone',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefdinir',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefixime',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefatazidime + Clavulanic acid',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefoperazone + Sulbactum(Magnex)',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefpirome',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Ceftriaxone',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Ceftizoxime',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Ceftazidime',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefotaxime',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Ciprofloxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Ofloxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Lomefloxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Sparfloxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Pefloxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Moxifloxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Levofloxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Gatifloxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Norflaxacin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Nalidixic acid',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Nitrofurantoin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Ticarcillin + Clavulanic acid',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Piperacillin + Tazobactum',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Doxycycline',Null,NULL,1,'Y',14)



INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Meropenam',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Cefotaxime',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Rifampicin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Nystatin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Amphotericin',Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Flucanozole' ,Null,NULL,1,'Y',14)
INSERT INTO DrugBrand (GenericID, BrandName, Strength, AvailableDose, FMID, IsApproved, OrgID)  Values (0,'Itracanozole',Null,NULL,1,'Y',14)
