DELETE InvestigationOrgMapping WHERE OrgID = 14
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4142,14,209,11,'9.0 – 37.6 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4175,14,209,11,'0.0 – 5.0 RU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4426,14,209,11,'Male 10 – 25 mg/24 h; Female 06 – 14 mg/24 h')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4720,14,209,11,'Females - Follicular phase 0.0 – 1.13, Mid Follicular phase 0.40 – 1.02, Luteal phase 1.26  – 4.28, Oral contraceptives 0.14 – 1.11, Postmenopausal 0.23 – 1.36, Infants 0 – 1 years: 0.06 – 1.86, Children 1 – 3 years: 0.02 – 0.19, 4 – 6 years: 0.01')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4444,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4144,14,201,4,'Male 85 – 125, Female 75 – 150')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4143,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4721,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4145,14,201,4,'0.00 - 0.10 gm/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4146,14,209,11,'9.0 – 37.6 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4486,14,208,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4147,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4425,14,209,11,'2.0 – 6.1  Mg/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4506,14,208,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4148,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4149,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2011,14,206,1,'40 - 440 cells/cumm')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4722,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4723,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4172,14,209,11,'8 – 52 U/l')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4724,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4725,14,201,4,'Total - 0.0 – 6.0 U/l; Prostatic fraction - 0.0 – 2.0  U/l')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4150,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4726,14,209,11,'0 – 46 pg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4727,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4728,14,206,1,'25 -35 seconds')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4151,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4152,14,201,4,'< 30 U/L - Normal; 30 – 40 U/L - Suspect; 40 – 60 U/L - Strong Suspect; > 60 U/L -Positive; For CSF - <10 Negative; >10 Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4195,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4154,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4153,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4157,14,210,3)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4158,14,210,3)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4159,14,210,3)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4161,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4160,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4729,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4730,14,210,3,'3.5 – 5.0 gm/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4162,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4731,14,201,4,'3.5 – 5.0 g/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4163,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4732,14,201,4,'117 – 390 U/L')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4164,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4165,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4733,14,209,11,'93 - 224 Mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4734,14,209,11,'0.5 – 5.5 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4166,14,201,4,'Male 0 – 42 U/L; Female 0 – 37 U/L; Child 0 – 37 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3041,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4474,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4167,14,201,4,'16 – 53 µmol/l')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4168,14,203,2,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4587,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4735,14,201,4,'0.0—85 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4736,14,209,11,'< 1.0 Negative; 1.0 – 1.2 Equivocal; > 1.2 Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4737,14,209,11,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4738,14,209,11,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4170,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4169,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4739,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4740,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4171,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4173,14,209,11,'0.0 – 15.0 PL IgG U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4174,14,209,11,'0.0 – 15.0 PL IgG U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4176,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4178,14,209,11,'Non Reactive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4177,14,209,11,'Non Reactive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4741,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4742,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4743,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4744,14,209,11,'Non Reactive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4180,14,209,11,'0 - 10 U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4181,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4745,14,209,11,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4182,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4183,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4185,14,209,11,'0.0 – 15.0 GPI U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4186,14,209,11,'0.0 -15.0 MPI U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4187,14,209,11,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4188,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4189,14,209,11,'Less than 16 RU/ml -Negative; 16  - 22: Low Positive; More than 22:Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4190,14,209,11,'0.0 – 60.0 U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4746,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4191,14,209,11,'0 – 150 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4192,14,209,11,'0 – 150 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4193,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4194,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4184,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4196,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4197,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4360,14,206,1,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4198,14,203,2,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4748,14,203,2,'0 – 200 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4199,14,201,4,'Male 0 – 40 U/L; Female 0 – 31 U/L; Child 0 – 37 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3040,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4487,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4200,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4219,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4206,14,206,1,'Bleeding Time - Upto 8 Minutes; Clotting Time - Upto 10 Minutes')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4457,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4459,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4458,14,209,11,'174 – 878 pg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4609,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4610,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4201,14,207,9)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4202,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4547,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4489,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4490,14,208,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4488,14,208,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4749,14,208,10)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4203,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4204,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4750,14,201,4,'Male & Non Pregnant Female: 0.0 – 5.3; Pregnant women - Gestational week 1 - 2: 16 – 156; 2 – 3: 101 – 4870; 3 – 4: 1110 – 31500; 4 – 5: 2560 – 82300; 5 – 6: 23100 – 151000; 6 – 7: 27300 – 233000; 7 – 11: 20900 – 291000; 11 – 16: 6140 – 103000; 16 – 21: 4720 – 80100; 21 – 39: 2700 – 78100')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4751,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4752,14,209,11,'22 – 26 mmol/L')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4205,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4553,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4579,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3031,14,207,9,'Total Bilirubin: 0.2 – 1.2 mg/dl; Direct Bilirubin: 0.0 – 0.3 mg/dl; Indirect Bilirubin -0.2 – 0.9 mg/dl')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3032,14,207,9,'Total Bilirubin: 0.2 – 1.2 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3033,14,207,9,'Direct Bilirubin: 0.0 – 0.3 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3034,14,207,9,'Indirect Bilirubin -0.2 – 0.9 mg/dl')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4621,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4554,14,202,5)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4208,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4207,14,210,3)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4209,14,210,3)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4210,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4753,14,201,4,'5-20mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4211,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4212,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4213,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4214,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4217,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4218,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4220,14,206,1,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4754,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4221,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4223,14,201,4,'0.0 – 6.0 mg/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4222,14,201,4,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4755,14,201,4,'0 – 21.0 U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4225,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4224,14,209,11,'0 – 40 U/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4226,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4756,14,209,11,'8.5 – 10.5 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4227,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4228,14,203,2,'Theraoeytuc range for Seizure disorder 4 – 10; Psychiatric disorder 8 - 14 µg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4757,14,203,2,'0.0 – 4.9 Ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4229,14,209,11,'Absolute CD4 Count - 550 – 1050 Cells/cumm; CD% - 37 – 58%')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4230,14,209,11,'Absolute CD8 Count - 200 – 700 Cells/cumm; CD8% -14 – 32%')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4231,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4233,14,207,9,'15 – 60 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4235,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4234,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4237,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4238,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4236,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4555,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4758,14,207,9,'96 - 106 mmol/l')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4759,14,201,4,'140 – 200 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4239,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4240,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4241,14,204,6,'Upto 4 Hours')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4243,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4242,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4244,14,211,12,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4245,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4491,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4492,14,208,10)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4246,14,208,10,'90 – 180 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4247,14,201,4,'10 – 40 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4248,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4249,14,210,3,'Men- 70 – 140 mcg/dl; Women: 80 – 155 mcg/dl; Pregnant women 118 – 302 mcg/dl; Children (6 – 12Yrs) 80 – 190 mcg/dl; Infants 20-70 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4250,14,201,4,'By ISE method - 1.12 – 1.32 Mmol/l; By Calculation - 4.4 – 4.9  mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4251,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4760,14,206,1,'5.0 – 23.0 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4761,14,209,11,'3.0 – 16.0 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4762,14,209,11,'Cortisol (8 am) - 5.0 – 23.0 µg/dl; Cortisol (4 pm) - 3.0 – 16.0 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4469,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4763,14,205,8,'24 – 194 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4764,14,201,4,'0 – 24 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4765,14,201,4,'Male 0.7 – 1.4 mg/dl; Female 0.6 – 1.2 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4252,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4253,14,202,5,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4255,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4256,14,202,5)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4257,14,202,5)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4258,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4259,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4260,14,203,2,'Renal Transplant: 1 month : 1.5 ug/ml; 2 months: 1.3 ug/ml; 3 months: 1.1ug/ml; 4-6 months: 0.9ug/ml; > 6 months: 0.7 ug/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4262,14,209,11,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4263,14,209,11,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4261,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4766,14,209,11,'Less than 10 EU/ml - Negative; 10 – 12 EU/ml -Equivocal; more than 12 EU/ml - Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4767,14,209,11,'Less than 0.9 – Negative; 0.9 – 1.1-Low Positive; More than 1.1 -Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4274,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4264,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4768,14,203,2,'Neutophils 40-70%; Lymphocytes 22-44%; Eosinophils 00-06%, Basophils; Monocytes 00-05%; Bands 00-03%')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4769,14,206,1,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4770,14,203,2,'0 – 300 ng/ml')
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4265,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4266,14,209,11,'< 9 Panbio Units - Negative; 9 – 11Panbio Units - Equivocal; > 11 Panbio Units - Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4268,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4267,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4771,14,211,12,'35 – 430 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4269,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4468,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4272,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4273,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4772,14,202,5)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4470,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4277,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4275,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4276,14,209,11)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4279,14,208,10)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4278,14,201,4)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4409,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4589,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4590,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4281,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2013,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4773,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4282,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4556,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4557,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4283,14,207,9,'1 ½ -4 hours')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4612,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4613,14,202,5)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4558,14,202,5)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4284,14,207,9,'50-150%')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4285,14,206,1,'50-120 %; Interpretation reference :< 1 % - Severe deficiency; 1-5% – Moderate deficiency; 5-50 % – mild deficiency')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4286,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4287,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4288,14,206,1,'Normal (Upto 24 Hours)')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4559,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4472,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4289,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4774,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4290,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4560,14,206,1)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4232,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4548,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4549,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4550,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4551,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4291,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4292,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4775,14,204,6)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4293,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4294,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4295,14,202,5)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4296,14,202,5)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4297,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4298,14,201,4,'Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4776,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4777,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4778,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4299,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4300,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4301,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4779,14,210,3,'4.6 – 13.5 U/gHB')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4302,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4561,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4304,14,207,9)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4307,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4780,14,201,4,'Male 11 – 50;Female 7 – 32;Child 11 – 35 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4305,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4471,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4306,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4781,14,201,4,'70-110 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4782,14,201,4,'70-140 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4783,14,201,4,'70-140 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4784,14,201,4)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4785,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4786,14,202,5,'0 - 7 ng/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4308,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4319,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4309,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4310,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4311,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4312,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4313,14,210,3)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4787,14,203,2,'11.5-15.5 g/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4320,14,206,1)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4788,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4789,14,201,4,'Non Diabetic < 6.0; Diabetic with good control 6.0 – 8.0 %')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4790,14,201,4,'Non Reactive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4322,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4791,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4323,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4569,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4570,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4792,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4793,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4314,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4315,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4316,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4317,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4794,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4795,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4318,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4796,14,201,4,'29 – 60 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4324,14,201,4)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4321,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4562,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4326,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4325,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4797,14,211,12,'Less than 0.9-Negative; 0.9 – 1.1-Low Positive; More than 1.1 AI Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4798,14,209,11,'Less than 0.9-Negative; 0.9 – 1.1-Low Positive; More than 1.1 AI Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4329,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4799,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4800,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4331,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4333,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4330,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4332,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4334,14,211,12)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4473,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4335,14,205,8)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4336,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4611,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4564,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4327,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4328,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4337,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4563,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4339,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4338,14,209,11)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4340,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4341,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4801,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4342,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4343,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4344,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4345,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4346,14,202,5,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4347,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4349,14,209,11,'Normal Range 0 – 1 year 12.5 – 116.0; 17 – 20 year 181.2 – 816.2 1 – 2 year 16.4 – 137.2; 20 – 25 year; 179.9 – 777.6; 2 – 3 year 18.4 – 149.4; 25 – 30 year; 155.3 – 667.1 3 – 4 year 23.7 – 197.1; 30 – 35 year 122.9 – 570.1; 4 – 5 year 30.1 – 252.2; 35 – 40 year 98.0 – 499.1; 5 – 6 year 38.4 – 313.8 40 – 45 year 83.7 – 454.7; 6 – 7 year	48.5 – 380.5; 45 – 50 year 75.6 – 430.1; 7 – 8 year 60.6 – 450.2; 50 – 55 year 8.6 – 416.5; 8 – 9 year 69.6 – 488.6; 55 – 60 Year 61.0 – 404.2; 9 – 10 Year 78.1 – 517.0; 60 – 65 year 54.0 – 384.7; 10 – 11 Year 91.3 – 575.4; 65 – 70 year 45.8 – 352.7; 11 – 12 Year 105.0 – 629.3; 70 – 75 year 39.7 – 331.5; 12 – 13 year 118.4 – 677.5; 75 – 80 year 32.9 – 299.2; 13 – 14 year 131.2 – 718.9; 80 – 85 year; 32.5 – 251.8; 14 – 16 year; 148.4 – 767.2; 85 – 95	year 17.6 – 219.7; 16 – 17 year 166.5 – 805.4;')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4350,14,209,11,'By ISE method - 1.12 – 1.32 Mmol/l; By Calculation - 4.4 – 4.9  mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4802,14,201,4,'Male 70 – 180; Female 60 – 180 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4466,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4351,14,201,4)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4352,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4566,14,204,6)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4565,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4571,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4581,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4582,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4588,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4600,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4602,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4601,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4576,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4577,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4607,14,207,9)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4803,14,207,9,'5 – 20 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4353,14,201,4,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4354,14,203,2)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4567,14,209,11)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4804,14,207,9,'00 – 480 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4805,14,201,4,'Desirable  < 130 mg/dl; Borderline risk 130 –160 mg/dl; High risk > 160 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4355,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4356,14,NULL,NULL,'0 – 50 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4493,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4806,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4807,14,NULL,NULL,'Follicular phase  1.1 – 11.6 mIU/ml; Midcycle 17 – 77 mIU/ml; Luteal phase 0.0 – 14.7 mIU/ml; Perimenstrual 0.0 – 12.0 mIU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4808,14,NULL,NULL,'0 — 190 U/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4467,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4357,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4591,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4358,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4359,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4592,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2033,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4809,14,NULL,NULL,'1.8 – 2.9 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4361,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4216,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4215,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4365,14,NULL,NULL,'Less than 0.24 g/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4810,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4811,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4362,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4812,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4363,14,NULL,NULL,'< 0.9 Negative; 0.9 – 1.1 Equivocal; > 1.1 A.I Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4364,14,NULL,NULL,'< 0.9 Negative; 0.9 – 1.1 Equivocal; > 1.1 A.I Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4568,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4475,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4596,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4597,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4595,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4594,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4593,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4366,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4367,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4368,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4369,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4370,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4813,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4814,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4815,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4371,14,NULL,NULL,'< 0.9 Negative; 0.9 – 1.1 Equivocal; > 1.1 A.I Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4372,14,NULL,NULL,'< 0.9 Negative; 0.9 – 1.1 Equivocal; > 1.1 A.I Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4373,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4375,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4374,14,NULL,NULL,'0.0 – 1.0 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4376,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4377,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4816,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4254,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4378,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4476,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4379,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4380,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4477,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4381,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4382,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4572,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4383,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4384,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4385,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4388,14,NULL,NULL,'10 – 69 pg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4389,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4390,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2014,14,NULL,NULL,'34.9 % - 46.9 %')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4496,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4495,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4391,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4392,14,206,1)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4497,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4393,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4394,14,NULL,NULL,'Non Toxic Patient 10 – 20 µg/ml; Toxic Patient > 20')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4395,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4817,14,NULL,NULL,'2.5 – 4.8 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4386,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4387,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4818,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4819,14,NULL,NULL,'1.5 - 4.0 Lakhs /cumm')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2029,14,NULL,NULL,'Normal')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4614,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4615,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4616,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4617,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4396,14,NULL,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4397,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4598,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4398,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4820,14,NULL,NULL,'3.5 – 5.0 mmol/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4400,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4821,14,NULL,NULL,'1.9 – 25.0 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4399,14,NULL,NULL,'< 0.5 ng/ml Low risk; 0.5 – 2.0 Moderate risk; 2 – 10 High risk >10 Severe sepsis/Septic shock')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4822,14,NULL,NULL,'MALE - 0.27 – 0.90 ng/ml; Female - Follicular phase  0.0 – 1.13; Mid Follicular phase  0.0 – 0.98;  (5 -11days) Midcycle 0.48 – 1.72; Luteal phase 0.95 – 21.0; Postmenopausal 0 – 1.0; Oral contraceptives 0.34 – 0.92')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4823,14,NULL,NULL,'Normal : 0 – 10 ng/ml; Prostatitis & BPH: 10 – 40 ng/ml; Malignancy > 40.0 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4824,14,NULL,NULL,'0.0 – 0.42 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4573,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4825,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4401,14,NULL,NULL,'0.0 – 0.3')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4826,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4827,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4574,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4402,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4828,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4829,14,NULL,NULL,'0.0 – 15.0 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4403,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4830,14,NULL,NULL,'4.4-5.9 Millions/cu.mm')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2012,14,NULL,NULL,'0.2 - 2.0 %')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4404,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2040,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4405,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4406,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4831,14,NULL,NULL,'Less than 8.0 – Negative; 8.0-11.0 -Low Positive; More than 11 RU/ml - Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4832,14,NULL,NULL,'Less than 0.9 – Negative; 0.9 – 1.1-Low Positive; More than 1.1 -Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4407,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4479,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4599,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4480,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4575,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4280,14,NULL,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4833,14,NULL,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4834,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4408,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4410,14,NULL,NULL,'280 – 300 mosm/kg')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4481,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4835,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4411,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4412,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4603,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4605,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4604,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4578,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4836,14,NULL,NULL,'136 – 146 mmol/L')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4498,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4413,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4414,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4837,14,NULL,NULL,'1.010 -1.025')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4417,14,NULL,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4416,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4415,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4606,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4418,14,NULL,NULL,'Present in Normal Amount')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4419,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4499,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4420,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4482,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4838,14,NULL,NULL,'0.80 – 2.00 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4839,14,NULL,NULL,'5.0  – 11.8 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4840,14,NULL,NULL,'Less than 300.0 U/ml -Negative; 300 – 600 U/ml - Low Positive; More than 600.0 U/ml – Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4841,14,NULL,NULL,'Less than 400.0 U/ml -Negative; 400 – 900 U/ml - Low Positive; More than 900.0 U/ml – Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4842,14,NULL,NULL,'Less than 1.0 AI -Negative; 1.0-1.2 AI - Low Positive; More than1.2 AI – Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4421,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4843,14,NULL,NULL,'Female: Ovulating - 15.0 – 80.0; Post menopausal 15.0 – 62.0 ng/dl; Male - 262 – 1593 ng/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4844,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4422,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4423,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3086,14,NULL,NULL,'0.0 – 55.0 IU/ml; Thyroidectomy pts  0.0 – 0.9 IU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4608,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4845,14,NULL,NULL,'250 – 400 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4846,14,NULL,NULL,'6.0 – 8.0 gm/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4500,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4717,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4847,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4848,14,NULL,NULL,'Less than 8.0 IU/ml – Negative; 8.0 – 11.0 -Low Positive; More than 11 – Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4849,14,NULL,NULL,'Less than 0.9 – Negative; 0.9 – 1.1 -Low Positive; More than 1.1 – Positive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4850,14,NULL,NULL,'Non-Reactive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4851,14,NULL,NULL,'Non-Reactive')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4424,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4483,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4618,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4852,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4619,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4484,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3057,14,NULL,NULL,'67 – 157 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4853,14,NULL,NULL,'0 – 1.0 ng/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4854,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4855,14,NULL,NULL,'0.30 – 5.50 µIU/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4580,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4451,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4501,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4504,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4502,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4503,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4856,14,NULL,NULL,'10 – 45 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4857,14,NULL,NULL,'Male 3.4 – 7.0;Female 2.4 – 5.7;Child 2.6 – 6.0 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4014,14,NULL,NULL,'Absent')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4427,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4858,14,NULL,NULL,'100 – 300 mg/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4485,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4428,14,NULL,NULL,'5 - 35 mg/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4429,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4859,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4435,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4437,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4430,14,NULL,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4431,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4432,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4860,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4434,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4436,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4438,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4439,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4440,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4441,14,NULL,NULL,'Less than 0.1g/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3106,14,NULL,NULL,'0.0 – 5.5 µmol/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4861,14,NULL,NULL,'0.0 – 20.0 mg/l')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4442,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4443,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(3027,14,NULL,NULL,'50 – 1200  mosm/kg')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4445,14,NULL,NULL,'0 – 50 mg/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4446,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4004,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4447,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4448,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4862,14,NULL,NULL,'40 – 80 mmol/l')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4449,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4863,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4450,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4864,14,NULL,NULL,'Absent')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4865,14,NULL,NULL,'Absent')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4866,14,NULL,NULL,'Sodium (spot urine) - 80 – 180 mmol/l; Sodium (24h urine) - 42 – 220 mmol/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4452,14,NULL,NULL,'26 – 43 gm/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4024,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4867,14,NULL,NULL,'0.0 – 13.6 mg/day')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4453,14,NULL,NULL,'Present')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4583,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4584,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4585,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4454,14,NULL,NULL,'50 – 100 µg/ml')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4868,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4869,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4586,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4456,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4455,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4461,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4462,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4463,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4620,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4093,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4464,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4508,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4509,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4510,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4511,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4512,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4513,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4514,14,NULL,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4515,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4516,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4517,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4518,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4519,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4520,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4521,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4522,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4523,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4524,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4525,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4526,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4527,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4528,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4529,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4530,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4531,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4532,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4533,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4534,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4535,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4536,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4537,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4538,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4539,14,NULL,NULL)
--Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4540,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4541,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4542,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4543,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4544,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4545,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4546,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4465,14,NULL,NULL,'60-120 µg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4348,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2043,14,NULL,NULL,'Upto 8 Minutes')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(2045,14,NULL,NULL,'Upto 10 Minutes')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4179,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4870,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4505,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4507,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4460,14,NULL,NULL,'10 – 40 mg/dl')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4871,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4494,14,NULL,NULL)
--newly added
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4872,14,NULL,NULL,'11- 16 seconds')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4873,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4874,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4875,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4876,14,NULL,NULL,'4000-11000 Cells/Cumm')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4877,14,NULL,NULL,'16 - 22 seconds')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5086,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5087,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5088,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4747,14,NULL,NULL,'Negative')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5293,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5294,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5295,14,NULL,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4891,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4892,14,NULL,NULL,'Negative')

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5296,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5297,14,NULL,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5301,14,NULL,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5449,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5450,14,NULL,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5566,14,NULL,NULL)

-----------for body fluid analysis
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5043,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5044,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5045,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5046,14,NULL,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4911,14,NULL,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3058,14,NULL,NULL)
------- Urine Analysis
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4017,14,NULL,NULL,'Absent')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4018,14,NULL,NULL,'Nil')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID,ReferenceRange)values(4019,14,NULL,NULL,'Negative')
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4023,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4010,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4011,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4007,14,NULL,NULL)
----------stool analysis
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3132,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3130,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5196,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3135,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3133,14,NULL,NULL)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(3134,14,NULL,NULL)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(2031,14,Null,Null)
--newly added
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5031,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5466,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5577,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5578,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5579,14,Null,Null)
--
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5003,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5004,14,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(1006,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4944,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4946,14,Null,Null)

Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(1007,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4945,14,Null,Null)
Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(4943,14,Null,Null)


Insert into InvestigationOrgMapping (InvestigationID,OrgID,DeptID,HeaderID)values(5580,14,209,11)


