Truncate Table InvSampleMaster
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(1,'Blood')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(2,'Plasma')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(3,'Serum')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(4,'Urine')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(5,'Sputum')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(6,'Stool / Motion')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(7,'Semen')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(8,'Endotracheal aspirate')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(9,'Neckline tip')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(10,'Cerebrospinal fluid')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(11,'Pleural fluid')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(12,'Pericardial fluid')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(13,'Ascitic fluid')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(14,'Synovial joint fluid')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(15,'PD fluid')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(16,'Throat swab')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(17,'Ear swab')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(18,'Nasal swab')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(19,'Genital swab')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(20,'Pus')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(21,'Abscess fluid')
--Insert Into InvSampleMaster(SampleCode,SampleDesc) values(22,'Ascitic fluid')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(23,'24-H Urine')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(24,'Amputed Extremities')
--Insert Into InvSampleMaster(SampleCode,SampleDesc) values(25,'Bone Marrow Biopsy')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(26,'Bone Tissue')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(27,'Cervix')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(28,'Endometrium')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(29,'Excised Small & Large Bowel')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(30,'Fistulectomy / Haemorrhoids')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(31,'Gall Bladder')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(32,'Kidney')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(33,'Ovary')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(34,'Liver')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(35,'Lymphnode')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(36,'Mastecttomy')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(37,'Ovarian Cyst')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(38,'Polyp')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(39,'Prostectomy')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(40,'Punch Biopsy')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(41,'Scopy Biopsy')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(42,'Second Opinion With Specimen')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(43,'Second Opinion With Block')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(44,'Skin')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(45,'Slide')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(46,'Spleen')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(47,'Uterus With Both Adnexa+Appendix')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(48,'Uterus With Both Adnexa')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(49,'Uterus With One Adnexa')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(50,'Others')
Insert Into InvSampleMaster(SampleCode,SampleDesc) values(51,'Nail Clipping')

--Bugtracker 7
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(52,'BAL')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(53,'Asthalin solution')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(54,'Aspiration fluid')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(55,'Drainage fluid')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(56,'Dialysis water')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(57,'Conjunctival swab')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(58,'Hair clippings')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(59,'Skin scrappings')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(60,'Milk')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(61,'Mouth swab')
 Insert Into InvSampleMaster(SampleCode,SampleDesc) values(62,'Sequestrum')
 Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(63, 'Saline')
 
 Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(64,'Tracheal swab')
 Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(65,'Vaginal swab')
 Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(66,'Urethral swab')
 Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(67,'Theatre swab')
 --Bose lab after training
 Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(68,'Kidney Stone')
 Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(69,'Gall Bladder Stone')
--
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(70,'Uterus')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(71,'Appendix')
--Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(72,'Endometrium')
--Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(73,'Cervix')
--Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(74,'Liver')
--Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(75,'Skin')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(76,'Nail')
--Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(77,'Gall Bladder')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(78,'Pancreas')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(79,'Myocardium')
--Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(80,'Kidney')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(81,'Lung')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(82,'Heart')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(83,'Bone marrow')
--Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(84,'Lymph node')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(85,'Esophagus')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(86,'Stomach')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(87,'Colon')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(88,'Rectum')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(89,'Ileum')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(90,'Duodenum')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(91,'Breast')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(92,'Prostate')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(93,'Ear')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(94,'Urinary bladder')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(95,'Brain')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(96,'Salivary gland')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(97,'Vocal cord')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(98,'Tongue')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(99,'Scrotum')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(100,'Bone')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(101,'Thyroid')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(102,'Parathyroid')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(103,'Excised tissue')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(104,'Small Intestine')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(105,'Large Intestine')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(106,'Adenexa')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(107,'Adrenal')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(108,'Wound')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(109,'Fasting Urine')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(110,'PP Urine')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(111,'Fasting Blood')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(112,'PP Blood')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(113,'Clotted Blood')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(114,'EDTA Blood')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(115,'Citrated Blood')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(116,'Heparinized Blood')
Insert Into InvSampleMaster(SampleCode,SampleDesc)	values(117,'Early Morning Stool')