/****** Object:  Table [dbo].[SampleAttributes]    Script Date: 06/15/2009 11:27:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SampleAttributes](
	[AttributesID] [int] NOT NULL,
	[AttributesName] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[AttributesID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


