using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.SqlClient;

namespace ReportExportCommand
{
    class ReportCommand
    {
        public static System.Data.SqlClient.SqlCommand pGetExecuteSpForReportExcelCommand(System.DateTime pFromdate, System.DateTime pTodate, int pExcelReportId, string pExcelReportName, string pToExecute, int pOrgID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetExecuteSpForReportExcel";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pFromdate = new System.Data.SqlClient.SqlParameter();
            _pFromdate.ParameterName = "@pFromdate";
            _pFromdate.Size = -1;
            _pFromdate.Value = pFromdate;
            cmd.Parameters.Add(_pFromdate);
            System.Data.SqlClient.SqlParameter _pTodate = new System.Data.SqlClient.SqlParameter();
            _pTodate.ParameterName = "@pTodate";
            _pTodate.Size = -1;
            _pTodate.Value = pTodate;
            cmd.Parameters.Add(_pTodate);
            System.Data.SqlClient.SqlParameter _pExcelReportId = new System.Data.SqlClient.SqlParameter();
            _pExcelReportId.ParameterName = "@pExcelReportId";
            _pExcelReportId.Size = -1;
            _pExcelReportId.Value = pExcelReportId;
            cmd.Parameters.Add(_pExcelReportId);
            System.Data.SqlClient.SqlParameter _pExcelReportName = new System.Data.SqlClient.SqlParameter();
            _pExcelReportName.ParameterName = "@pExcelReportName";
            _pExcelReportName.Size = 255;
            _pExcelReportName.Value = pExcelReportName;
            cmd.Parameters.Add(_pExcelReportName);
            System.Data.SqlClient.SqlParameter _pToExecute = new System.Data.SqlClient.SqlParameter();
            _pToExecute.ParameterName = "@pToExecute";
            _pToExecute.Size = 10;
            _pToExecute.Value = pToExecute;
            cmd.Parameters.Add(_pToExecute);
            System.Data.SqlClient.SqlParameter _pOrgID = new System.Data.SqlClient.SqlParameter();
            _pOrgID.ParameterName = "@pOrgID";
            _pOrgID.Size = -1;
            _pOrgID.Value = pOrgID;
            cmd.Parameters.Add(_pOrgID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }

        public static System.Data.SqlClient.SqlCommand pGetTestStatisticsReportCommand(System.DateTime pFromDate, System.DateTime pToDate, int pLocationId, int pRoutine, long pClientId, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetTestStatisticsReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = -1;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = -1;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _pLocationId = new System.Data.SqlClient.SqlParameter();
            _pLocationId.ParameterName = "@pLocationId";
            _pLocationId.Size = -1;
            _pLocationId.Value = pLocationId;
            cmd.Parameters.Add(_pLocationId);
            System.Data.SqlClient.SqlParameter _pRoutine = new System.Data.SqlClient.SqlParameter();
            _pRoutine.ParameterName = "@pRoutine";
            _pRoutine.Size = -1;
            _pRoutine.Value = pRoutine;
            cmd.Parameters.Add(_pRoutine);
            System.Data.SqlClient.SqlParameter _pClientId = new System.Data.SqlClient.SqlParameter();
            _pClientId.ParameterName = "@pClientId";
            _pClientId.Size = -1;
            _pClientId.Value = pClientId;
            cmd.Parameters.Add(_pClientId);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }

        public static System.Data.SqlClient.SqlCommand pGetAuditTrailReportCommand(string pExternalVisitID, int pOrgID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetAuditTrailReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pExternalVisitID = new System.Data.SqlClient.SqlParameter();
            _pExternalVisitID.ParameterName = "@pExternalVisitID";
            _pExternalVisitID.Size = 255;
            _pExternalVisitID.Value = pExternalVisitID;
            cmd.Parameters.Add(_pExternalVisitID);
            System.Data.SqlClient.SqlParameter _pOrgID = new System.Data.SqlClient.SqlParameter();
            _pOrgID.ParameterName = "@pOrgID";
            _pOrgID.Size = -1;
            _pOrgID.Value = pOrgID;
            cmd.Parameters.Add(_pOrgID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }

        public static System.Data.SqlClient.SqlCommand pGetListOfLabUsersCommand(long OrgID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetListOfLabUsers";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _OrgID = new System.Data.SqlClient.SqlParameter();
            _OrgID.ParameterName = "@OrgID";
            _OrgID.Size = -1;
            _OrgID.Value = OrgID;
            cmd.Parameters.Add(_OrgID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }

        public static System.Data.SqlClient.SqlCommand pGetPendingListCommand(int OrgID, long RoleID, long pTestID, string pTestType, System.Data.DataTable LoginDetail, string IsTrustedDetails, long DeviceID, long pProtocalID, System.DateTime pFromDate, System.DateTime pToDate, string pStatus, int pLocationID, int pDepartmentID,string PGroupLevel, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetPendingList";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _OrgID = new System.Data.SqlClient.SqlParameter();
            _OrgID.ParameterName = "@OrgID";
            _OrgID.Size = -1;
            _OrgID.Value = OrgID;
            cmd.Parameters.Add(_OrgID);
            System.Data.SqlClient.SqlParameter _RoleID = new System.Data.SqlClient.SqlParameter();
            _RoleID.ParameterName = "@RoleID";
            _RoleID.Size = -1;
            _RoleID.Value = RoleID;
            cmd.Parameters.Add(_RoleID);
            System.Data.SqlClient.SqlParameter _pTestID = new System.Data.SqlClient.SqlParameter();
            _pTestID.ParameterName = "@pTestID";
            _pTestID.Size = -1;
            _pTestID.Value = pTestID;
            cmd.Parameters.Add(_pTestID);
            System.Data.SqlClient.SqlParameter _pTestType = new System.Data.SqlClient.SqlParameter();
            _pTestType.ParameterName = "@pTestType";
            _pTestType.Size = 25;
            _pTestType.Value = pTestType;
            cmd.Parameters.Add(_pTestType);
            System.Data.SqlClient.SqlParameter _LoginDetail = new System.Data.SqlClient.SqlParameter();
            _LoginDetail.ParameterName = "@LoginDetail";
            _LoginDetail.Size = -1;
            _LoginDetail.Value = LoginDetail;
            cmd.Parameters.Add(_LoginDetail);
            System.Data.SqlClient.SqlParameter _IsTrustedDetails = new System.Data.SqlClient.SqlParameter();
            _IsTrustedDetails.ParameterName = "@IsTrustedDetails";
            _IsTrustedDetails.Size = 3;
            _IsTrustedDetails.Value = IsTrustedDetails;
            cmd.Parameters.Add(_IsTrustedDetails);
            System.Data.SqlClient.SqlParameter _DeviceID = new System.Data.SqlClient.SqlParameter();
            _DeviceID.ParameterName = "@DeviceID";
            _DeviceID.Size = -1;
            _DeviceID.Value = DeviceID;
            cmd.Parameters.Add(_DeviceID);
            System.Data.SqlClient.SqlParameter _pProtocalID = new System.Data.SqlClient.SqlParameter();
            _pProtocalID.ParameterName = "@pProtocalID";
            _pProtocalID.Size = -1;
            _pProtocalID.Value = pProtocalID;
            cmd.Parameters.Add(_pProtocalID);
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = -1;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = -1;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _pStatus = new System.Data.SqlClient.SqlParameter();
            _pStatus.ParameterName = "@pStatus";
            _pStatus.Size = -1;
            _pStatus.Value = pStatus;
            cmd.Parameters.Add(_pStatus);
            System.Data.SqlClient.SqlParameter _pLocationID = new System.Data.SqlClient.SqlParameter();
            _pLocationID.ParameterName = "@pLocationID";
            _pLocationID.Size = -1;
            _pLocationID.Value = pLocationID;
            cmd.Parameters.Add(_pLocationID);
            System.Data.SqlClient.SqlParameter _pDepartmentID = new System.Data.SqlClient.SqlParameter();
            _pDepartmentID.ParameterName = "@pDepartmentID";
            _pDepartmentID.Size = -1;
            _pDepartmentID.Value = pDepartmentID;
            cmd.Parameters.Add(_pDepartmentID);
			  System.Data.SqlClient.SqlParameter _PGroupLevel = new System.Data.SqlClient.SqlParameter();
            _PGroupLevel.ParameterName = "@pGroupLevel";
            _PGroupLevel.Size = 1;
            _PGroupLevel.Value = PGroupLevel;
            cmd.Parameters.Add(_PGroupLevel);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }


        public static System.Data.SqlClient.SqlCommand pGetPatientStatusDetailsCommand(System.DateTime pFromDate, System.DateTime pToDate, long pUserId, int pLocationId, string pLabNumber, string pStatus, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetPatientStatusDetails";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = -1;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = -1;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _pUserId = new System.Data.SqlClient.SqlParameter();
            _pUserId.ParameterName = "@pUserId";
            _pUserId.Size = -1;
            _pUserId.Value = pUserId;
            cmd.Parameters.Add(_pUserId);
            System.Data.SqlClient.SqlParameter _pLocationId = new System.Data.SqlClient.SqlParameter();
            _pLocationId.ParameterName = "@pLocationId";
            _pLocationId.Size = -1;
            _pLocationId.Value = pLocationId;
            cmd.Parameters.Add(_pLocationId);
            System.Data.SqlClient.SqlParameter _pLabNumber = new System.Data.SqlClient.SqlParameter();
            _pLabNumber.ParameterName = "@pLabNumber";
            _pLabNumber.Size = 50;
            _pLabNumber.Value = pLabNumber;
            cmd.Parameters.Add(_pLabNumber);
            System.Data.SqlClient.SqlParameter _pStatus = new System.Data.SqlClient.SqlParameter();
            _pStatus.ParameterName = "@pStatus";
            _pStatus.Size = 50;
            _pStatus.Value = pStatus;
            cmd.Parameters.Add(_pStatus);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetPatientTrackingDetailsCommand(long pOrgID, string PName, string pVisitNumber, string pBarcodeNumber, long pVisitID, string pPatentNumber, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetPatientTrackingDetails";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pOrgID = new System.Data.SqlClient.SqlParameter();
            _pOrgID.ParameterName = "@pOrgID";
            _pOrgID.Size = -1;
            _pOrgID.Value = pOrgID;
            cmd.Parameters.Add(_pOrgID);
            System.Data.SqlClient.SqlParameter _PName = new System.Data.SqlClient.SqlParameter();
            _PName.ParameterName = "@PName";
            _PName.Size = 500;
            _PName.Value = PName;
            cmd.Parameters.Add(_PName);
            System.Data.SqlClient.SqlParameter _pVisitNumber = new System.Data.SqlClient.SqlParameter();
            _pVisitNumber.ParameterName = "@pVisitNumber";
            _pVisitNumber.Size = 50;
            _pVisitNumber.Value = pVisitNumber;
            cmd.Parameters.Add(_pVisitNumber);
            System.Data.SqlClient.SqlParameter _pBarcodeNumber = new System.Data.SqlClient.SqlParameter();
            _pBarcodeNumber.ParameterName = "@pBarcodeNumber";
            _pBarcodeNumber.Size = 50;
            _pBarcodeNumber.Value = pBarcodeNumber;
            cmd.Parameters.Add(_pBarcodeNumber);
            System.Data.SqlClient.SqlParameter _pVisitID = new System.Data.SqlClient.SqlParameter();
            _pVisitID.ParameterName = "@pVisitID";
            _pVisitID.Size = -1;
            _pVisitID.Value = pVisitID;
            cmd.Parameters.Add(_pVisitID);
            System.Data.SqlClient.SqlParameter _pPatentNumber = new System.Data.SqlClient.SqlParameter();
            _pPatentNumber.ParameterName = "@pPatentNumber";
            _pPatentNumber.Size = 50;
            _pPatentNumber.Value = pPatentNumber;
            cmd.Parameters.Add(_pPatentNumber);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pSearchBillDetailsCommand(string pBillNo, string pBillFromDate, string pBillToDate, string pPatientName, int pPhysicianID, int pOrgID, string pPatientNumber, string ClientID, string pVisitNumber, int pageSize, int startRowIndex, out int totalRows, int LocationID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pSearchBillDetails";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pBillNo = new System.Data.SqlClient.SqlParameter();
            _pBillNo.ParameterName = "@pBillNo";
            _pBillNo.Size = 30;
            _pBillNo.Value = pBillNo;
            cmd.Parameters.Add(_pBillNo);
            System.Data.SqlClient.SqlParameter _pBillFromDate = new System.Data.SqlClient.SqlParameter();
            _pBillFromDate.ParameterName = "@pBillFromDate";
            _pBillFromDate.Size = 20;
            _pBillFromDate.Value = pBillFromDate;
            cmd.Parameters.Add(_pBillFromDate);
            System.Data.SqlClient.SqlParameter _pBillToDate = new System.Data.SqlClient.SqlParameter();
            _pBillToDate.ParameterName = "@pBillToDate";
            _pBillToDate.Size = 20;
            _pBillToDate.Value = pBillToDate;
            cmd.Parameters.Add(_pBillToDate);
            System.Data.SqlClient.SqlParameter _pPatientName = new System.Data.SqlClient.SqlParameter();
            _pPatientName.ParameterName = "@pPatientName";
            _pPatientName.Size = 50;
            _pPatientName.Value = pPatientName;
            cmd.Parameters.Add(_pPatientName);
            System.Data.SqlClient.SqlParameter _pPhysicianID = new System.Data.SqlClient.SqlParameter();
            _pPhysicianID.ParameterName = "@pPhysicianID";
            _pPhysicianID.Size = -1;
            _pPhysicianID.Value = pPhysicianID;
            cmd.Parameters.Add(_pPhysicianID);
            System.Data.SqlClient.SqlParameter _pOrgID = new System.Data.SqlClient.SqlParameter();
            _pOrgID.ParameterName = "@pOrgID";
            _pOrgID.Size = -1;
            _pOrgID.Value = pOrgID;
            cmd.Parameters.Add(_pOrgID);
            System.Data.SqlClient.SqlParameter _pPatientNumber = new System.Data.SqlClient.SqlParameter();
            _pPatientNumber.ParameterName = "@pPatientNumber";
            _pPatientNumber.Size = 20;
            _pPatientNumber.Value = pPatientNumber;
            cmd.Parameters.Add(_pPatientNumber);
            System.Data.SqlClient.SqlParameter _ClientID = new System.Data.SqlClient.SqlParameter();
            _ClientID.ParameterName = "@ClientID";
            _ClientID.Size = 20;
            _ClientID.Value = ClientID;
            cmd.Parameters.Add(_ClientID);
            System.Data.SqlClient.SqlParameter _pVisitNumber = new System.Data.SqlClient.SqlParameter();
            _pVisitNumber.ParameterName = "@pVisitNumber";
            _pVisitNumber.Size = 55;
            _pVisitNumber.Value = pVisitNumber;
            cmd.Parameters.Add(_pVisitNumber);
            System.Data.SqlClient.SqlParameter _pageSize = new System.Data.SqlClient.SqlParameter();
            _pageSize.ParameterName = "@pageSize";
            _pageSize.Size = -1;
            _pageSize.Value = pageSize;
            cmd.Parameters.Add(_pageSize);
            System.Data.SqlClient.SqlParameter _startRowIndex = new System.Data.SqlClient.SqlParameter();
            _startRowIndex.ParameterName = "@startRowIndex";
            _startRowIndex.Size = -1;
            _startRowIndex.Value = startRowIndex;
            cmd.Parameters.Add(_startRowIndex);
            totalRows = -1;
            System.Data.SqlClient.SqlParameter _totalRows = new System.Data.SqlClient.SqlParameter();
            _totalRows.ParameterName = "@totalRows";
            _totalRows.Size = -1;
            _totalRows.Value = totalRows;
            cmd.Parameters.Add(_totalRows);
            _totalRows.Direction = ParameterDirection.Output;
            System.Data.SqlClient.SqlParameter _LocationID = new System.Data.SqlClient.SqlParameter();
            _LocationID.ParameterName = "@LocationID";
            _LocationID.Size = -1;
            _LocationID.Value = LocationID;
            cmd.Parameters.Add(_LocationID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            totalRows = ((int)(_totalRows.Value));
            return cmd;
        }

        public static System.Data.SqlClient.SqlCommand PgetTATAnalysisreportCommand(System.DateTime pstart, System.DateTime pEnd, int Proutine, int Plocationid, long Pclientid, string Fromstatus, string Tostatus, System.Data.DataTable Contextinfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "PgetTATAnalysisreport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pstart = new System.Data.SqlClient.SqlParameter();
            _pstart.ParameterName = "@pstart";
            _pstart.Size = -1;
            _pstart.Value = pstart;
            cmd.Parameters.Add(_pstart);
            System.Data.SqlClient.SqlParameter _pEnd = new System.Data.SqlClient.SqlParameter();
            _pEnd.ParameterName = "@pEnd";
            _pEnd.Size = -1;
            _pEnd.Value = pEnd;
            cmd.Parameters.Add(_pEnd);
            System.Data.SqlClient.SqlParameter _Proutine = new System.Data.SqlClient.SqlParameter();
            _Proutine.ParameterName = "@Proutine";
            _Proutine.Size = -1;
            _Proutine.Value = Proutine;
            cmd.Parameters.Add(_Proutine);
            System.Data.SqlClient.SqlParameter _Plocationid = new System.Data.SqlClient.SqlParameter();
            _Plocationid.ParameterName = "@Plocationid";
            _Plocationid.Size = -1;
            _Plocationid.Value = Plocationid;
            cmd.Parameters.Add(_Plocationid);
            System.Data.SqlClient.SqlParameter _Pclientid = new System.Data.SqlClient.SqlParameter();
            _Pclientid.ParameterName = "@Pclientid";
            _Pclientid.Size = -1;
            _Pclientid.Value = Pclientid;
            cmd.Parameters.Add(_Pclientid);
            System.Data.SqlClient.SqlParameter _Fromstatus = new System.Data.SqlClient.SqlParameter();
            _Fromstatus.ParameterName = "@Fromstatus";
            _Fromstatus.Size = 50;
            _Fromstatus.Value = Fromstatus;
            cmd.Parameters.Add(_Fromstatus);
            System.Data.SqlClient.SqlParameter _Tostatus = new System.Data.SqlClient.SqlParameter();
            _Tostatus.ParameterName = "@Tostatus";
            _Tostatus.Size = 50;
            _Tostatus.Value = Tostatus;
            cmd.Parameters.Add(_Tostatus);
            System.Data.SqlClient.SqlParameter _Contextinfo = new System.Data.SqlClient.SqlParameter();
            _Contextinfo.ParameterName = "@Contextinfo";
            _Contextinfo.Size = -1;
            _Contextinfo.Value = Contextinfo;
            cmd.Parameters.Add(_Contextinfo);
            return cmd;
        }

        public static System.Data.SqlClient.SqlCommand pGetdropdownValuesforTATReportCommand(int pOrgid, System.Data.DataTable Contextinfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetdropdownValuesforTATReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pOrgid = new System.Data.SqlClient.SqlParameter();
            _pOrgid.ParameterName = "@pOrgid";
            _pOrgid.Size = -1;
            _pOrgid.Value = pOrgid;
            cmd.Parameters.Add(_pOrgid);
            System.Data.SqlClient.SqlParameter _Contextinfo = new System.Data.SqlClient.SqlParameter();
            _Contextinfo.ParameterName = "@Contextinfo";
            _Contextinfo.Size = -1;
            _Contextinfo.Value = Contextinfo;
            cmd.Parameters.Add(_Contextinfo);
            return cmd;
        }

        public static System.Data.SqlClient.SqlCommand pGetEpisodeReportCommand(int trustedOrgID, int locationID, System.DateTime PFromdate, System.DateTime PTodate, string PEpisodeNo, string PPatientName, string PTestName, string PClientName, int POrgid, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetEpisodeReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _trustedOrgID = new System.Data.SqlClient.SqlParameter();
            _trustedOrgID.ParameterName = "@trustedOrgID";
            _trustedOrgID.Size = -1;
            _trustedOrgID.Value = trustedOrgID;
            cmd.Parameters.Add(_trustedOrgID);
            System.Data.SqlClient.SqlParameter _locationID = new System.Data.SqlClient.SqlParameter();
            _locationID.ParameterName = "@locationID";
            _locationID.Size = -1;
            _locationID.Value = locationID;
            cmd.Parameters.Add(_locationID);
            System.Data.SqlClient.SqlParameter _PFromdate = new System.Data.SqlClient.SqlParameter();
            _PFromdate.ParameterName = "@PFromdate";
            _PFromdate.Size = -1;
            _PFromdate.Value = PFromdate;
            cmd.Parameters.Add(_PFromdate);
            System.Data.SqlClient.SqlParameter _PTodate = new System.Data.SqlClient.SqlParameter();
            _PTodate.ParameterName = "@PTodate";
            _PTodate.Size = -1;
            _PTodate.Value = PTodate;
            cmd.Parameters.Add(_PTodate);
            System.Data.SqlClient.SqlParameter _PEpisodeNo = new System.Data.SqlClient.SqlParameter();
            _PEpisodeNo.ParameterName = "@PEpisodeNo";
            _PEpisodeNo.Size = 255;
            _PEpisodeNo.Value = PEpisodeNo;
            cmd.Parameters.Add(_PEpisodeNo);
            System.Data.SqlClient.SqlParameter _PPatientName = new System.Data.SqlClient.SqlParameter();
            _PPatientName.ParameterName = "@PPatientName";
            _PPatientName.Size = 255;
            _PPatientName.Value = PPatientName;
            cmd.Parameters.Add(_PPatientName);
            System.Data.SqlClient.SqlParameter _PTestName = new System.Data.SqlClient.SqlParameter();
            _PTestName.ParameterName = "@PTestName";
            _PTestName.Size = 250;
            _PTestName.Value = PTestName;
            cmd.Parameters.Add(_PTestName);
            System.Data.SqlClient.SqlParameter _PClientName = new System.Data.SqlClient.SqlParameter();
            _PClientName.ParameterName = "@PClientName";
            _PClientName.Size = 250;
            _PClientName.Value = PClientName;
            cmd.Parameters.Add(_PClientName);
            System.Data.SqlClient.SqlParameter _POrgid = new System.Data.SqlClient.SqlParameter();
            _POrgid.ParameterName = "@POrgid";
            _POrgid.Size = -1;
            _POrgid.Value = POrgid;
            cmd.Parameters.Add(_POrgid);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pgetAntibioticsstatsReportCommand(int OrgID, System.DateTime FromDate, System.DateTime ToDate, long pClientID)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pgetAntibioticsstatsReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _OrgID = new System.Data.SqlClient.SqlParameter();
            _OrgID.ParameterName = "@OrgID";
            _OrgID.Size = -1;
            _OrgID.Value = OrgID;
            cmd.Parameters.Add(_OrgID);
            System.Data.SqlClient.SqlParameter _FromDate = new System.Data.SqlClient.SqlParameter();
            _FromDate.ParameterName = "@FromDate";
            _FromDate.Size = -1;
            _FromDate.Value = FromDate;
            cmd.Parameters.Add(_FromDate);
            System.Data.SqlClient.SqlParameter _ToDate = new System.Data.SqlClient.SqlParameter();
            _ToDate.ParameterName = "@ToDate";
            _ToDate.Size = -1;
            _ToDate.Value = ToDate;
            cmd.Parameters.Add(_ToDate);
            System.Data.SqlClient.SqlParameter _pClientID = new System.Data.SqlClient.SqlParameter();
            _pClientID.ParameterName = "@pClientID";
            _pClientID.Size = -1;
            _pClientID.Value = pClientID;
            cmd.Parameters.Add(_pClientID);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetHourlyBasedStatisticsReportnewCommand(int pOrgID, System.DateTime pFromDate, System.DateTime pToDate, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetHourlyBasedStatisticsReportnew";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pOrgID = new System.Data.SqlClient.SqlParameter();
            _pOrgID.ParameterName = "@pOrgID";
            _pOrgID.Size = -1;
            _pOrgID.Value = pOrgID;
            cmd.Parameters.Add(_pOrgID);
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = -1;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = -1;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetInvestigationsValueReportCommand(string pFromDate, string pToDate, long pClientID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetInvestigationsValueReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = 100;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = 100;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _pClientID = new System.Data.SqlClient.SqlParameter();
            _pClientID.ParameterName = "@pClientID";
            _pClientID.Size = -1;
            _pClientID.Value = pClientID;
            cmd.Parameters.Add(_pClientID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetCancelledBillReportCommand(string pSearchType, string pBillFromDate, string pBillToDate, long pClientID, long pCountryID, int pOrgID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetCancelledBillReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pSearchType = new System.Data.SqlClient.SqlParameter();
            _pSearchType.ParameterName = "@pSearchType";
            _pSearchType.Size = 30;
            _pSearchType.Value = pSearchType;
            cmd.Parameters.Add(_pSearchType);
            System.Data.SqlClient.SqlParameter _pBillFromDate = new System.Data.SqlClient.SqlParameter();
            _pBillFromDate.ParameterName = "@pBillFromDate";
            _pBillFromDate.Size = 25;
            _pBillFromDate.Value = pBillFromDate;
            cmd.Parameters.Add(_pBillFromDate);
            System.Data.SqlClient.SqlParameter _pBillToDate = new System.Data.SqlClient.SqlParameter();
            _pBillToDate.ParameterName = "@pBillToDate";
            _pBillToDate.Size = 25;
            _pBillToDate.Value = pBillToDate;
            cmd.Parameters.Add(_pBillToDate);
            System.Data.SqlClient.SqlParameter _pClientID = new System.Data.SqlClient.SqlParameter();
            _pClientID.ParameterName = "@pClientID";
            _pClientID.Size = -1;
            _pClientID.Value = pClientID;
            cmd.Parameters.Add(_pClientID);
            System.Data.SqlClient.SqlParameter _pCountryID = new System.Data.SqlClient.SqlParameter();
            _pCountryID.ParameterName = "@pCountryID";
            _pCountryID.Size = -1;
            _pCountryID.Value = pCountryID;
            cmd.Parameters.Add(_pCountryID);
            System.Data.SqlClient.SqlParameter _pOrgID = new System.Data.SqlClient.SqlParameter();
            _pOrgID.ParameterName = "@pOrgID";
            _pOrgID.Size = -1;
            _pOrgID.Value = pOrgID;
            cmd.Parameters.Add(_pOrgID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetClientMappedCountryNamesCommand(long pOrgId, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetClientMappedCountryNames";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pOrgId = new System.Data.SqlClient.SqlParameter();
            _pOrgId.ParameterName = "@pOrgId";
            _pOrgId.Size = -1;
            _pOrgId.Value = pOrgId;
            cmd.Parameters.Add(_pOrgId);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetBillsfortheDayClientWiseMonthlyReportCommand(string pSearchType, long pOrgID, long pClientID, long pCountryID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetBillsfortheDayClientWiseMonthlyReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pSearchType = new System.Data.SqlClient.SqlParameter();
            _pSearchType.ParameterName = "@pSearchType";
            _pSearchType.Size = 30;
            _pSearchType.Value = pSearchType;
            cmd.Parameters.Add(_pSearchType);
            System.Data.SqlClient.SqlParameter _pOrgID = new System.Data.SqlClient.SqlParameter();
            _pOrgID.ParameterName = "@pOrgID";
            _pOrgID.Size = -1;
            _pOrgID.Value = pOrgID;
            cmd.Parameters.Add(_pOrgID);
            System.Data.SqlClient.SqlParameter _pClientID = new System.Data.SqlClient.SqlParameter();
            _pClientID.ParameterName = "@pClientID";
            _pClientID.Size = -1;
            _pClientID.Value = pClientID;
            cmd.Parameters.Add(_pClientID);
            System.Data.SqlClient.SqlParameter _pCountryID = new System.Data.SqlClient.SqlParameter();
            _pCountryID.ParameterName = "@pCountryID";
            _pCountryID.Size = -1;
            _pCountryID.Value = pCountryID;
            cmd.Parameters.Add(_pCountryID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetPeriodwiseMeanTATReportCommand(int OrgID, string Type, System.DateTime pFromDate, System.DateTime pToDate, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetPeriodwiseMeanTATReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _OrgID = new System.Data.SqlClient.SqlParameter();
            _OrgID.ParameterName = "@OrgID";
            _OrgID.Size = -1;
            _OrgID.Value = OrgID;
            cmd.Parameters.Add(_OrgID);
            System.Data.SqlClient.SqlParameter _Type = new System.Data.SqlClient.SqlParameter();
            _Type.ParameterName = "@Type";
            _Type.Size = 50;
            _Type.Value = Type;
            cmd.Parameters.Add(_Type);
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = -1;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = -1;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetInvestigationStatusDeptWiseReportCommand(System.DateTime pBillFromDate, System.DateTime pBillToDate, long pClientID, long pCountryID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetInvestigationStatusDeptWiseReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pBillFromDate = new System.Data.SqlClient.SqlParameter();
            _pBillFromDate.ParameterName = "@pBillFromDate";
            _pBillFromDate.Size = -1;
            _pBillFromDate.Value = pBillFromDate;
            cmd.Parameters.Add(_pBillFromDate);
            System.Data.SqlClient.SqlParameter _pBillToDate = new System.Data.SqlClient.SqlParameter();
            _pBillToDate.ParameterName = "@pBillToDate";
            _pBillToDate.Size = -1;
            _pBillToDate.Value = pBillToDate;
            cmd.Parameters.Add(_pBillToDate);
            System.Data.SqlClient.SqlParameter _pClientID = new System.Data.SqlClient.SqlParameter();
            _pClientID.ParameterName = "@pClientID";
            _pClientID.Size = -1;
            _pClientID.Value = pClientID;
            cmd.Parameters.Add(_pClientID);
            System.Data.SqlClient.SqlParameter _pCountryID = new System.Data.SqlClient.SqlParameter();
            _pCountryID.ParameterName = "@pCountryID";
            _pCountryID.Size = -1;
            _pCountryID.Value = pCountryID;
            cmd.Parameters.Add(_pCountryID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetBillsfortheDaytestWiseMonthlyReportCommand(string pSearchType, long pOrgID, long pCountryID, int PProcessingLoc, int PRegisLoc, int Category, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetBillsfortheDaytestWiseMonthlyReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pSearchType = new System.Data.SqlClient.SqlParameter();
            _pSearchType.ParameterName = "@pSearchType";
            _pSearchType.Size = 30;
            _pSearchType.Value = pSearchType;
            cmd.Parameters.Add(_pSearchType);
            System.Data.SqlClient.SqlParameter _pOrgID = new System.Data.SqlClient.SqlParameter();
            _pOrgID.ParameterName = "@pOrgID";
            _pOrgID.Size = -1;
            _pOrgID.Value = pOrgID;
            cmd.Parameters.Add(_pOrgID);
            System.Data.SqlClient.SqlParameter _pCountryID = new System.Data.SqlClient.SqlParameter();
            _pCountryID.ParameterName = "@pCountryID";
            _pCountryID.Size = -1;
            _pCountryID.Value = pCountryID;
            cmd.Parameters.Add(_pCountryID);
            System.Data.SqlClient.SqlParameter _PProcessingLoc = new System.Data.SqlClient.SqlParameter();
            _PProcessingLoc.ParameterName = "@PProcessingLoc";
            _PProcessingLoc.Size = -1;
            _PProcessingLoc.Value = PProcessingLoc;
            cmd.Parameters.Add(_PProcessingLoc);
            System.Data.SqlClient.SqlParameter _PRegisLoc = new System.Data.SqlClient.SqlParameter();
            _PRegisLoc.ParameterName = "@PRegisLoc";
            _PRegisLoc.Size = -1;
            _PRegisLoc.Value = PRegisLoc;
            cmd.Parameters.Add(_PRegisLoc);
            System.Data.SqlClient.SqlParameter _Category = new System.Data.SqlClient.SqlParameter();
            _Category.ParameterName = "@Category";
            _Category.Size = -1;
            _Category.Value = Category;
            cmd.Parameters.Add(_Category);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetWeeklyPreTATReportCommand(int OrgID, string TestType, string SearchType, int Countryid, long Clientid, int Deptid, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetWeeklyPreTATReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _OrgID = new System.Data.SqlClient.SqlParameter();
            _OrgID.ParameterName = "@OrgID";
            _OrgID.Size = -1;
            _OrgID.Value = OrgID;
            cmd.Parameters.Add(_OrgID);
            System.Data.SqlClient.SqlParameter _TestType = new System.Data.SqlClient.SqlParameter();
            _TestType.ParameterName = "@TestType";
            _TestType.Size = 50;
            _TestType.Value = TestType;
            cmd.Parameters.Add(_TestType);
            System.Data.SqlClient.SqlParameter _SearchType = new System.Data.SqlClient.SqlParameter();
            _SearchType.ParameterName = "@SearchType";
            _SearchType.Size = 50;
            _SearchType.Value = SearchType;
            cmd.Parameters.Add(_SearchType);
            System.Data.SqlClient.SqlParameter _Countryid = new System.Data.SqlClient.SqlParameter();
            _Countryid.ParameterName = "@Countryid";
            _Countryid.Size = -1;
            _Countryid.Value = Countryid;
            cmd.Parameters.Add(_Countryid);
            System.Data.SqlClient.SqlParameter _Clientid = new System.Data.SqlClient.SqlParameter();
            _Clientid.ParameterName = "@Clientid";
            _Clientid.Size = -1;
            _Clientid.Value = Clientid;
            cmd.Parameters.Add(_Clientid);
            System.Data.SqlClient.SqlParameter _Deptid = new System.Data.SqlClient.SqlParameter();
            _Deptid.ParameterName = "@Deptid";
            _Deptid.Size = -1;
            _Deptid.Value = Deptid;
            cmd.Parameters.Add(_Deptid);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetPendingsamplesReportCommand(int OrgID, System.DateTime pFromDate, System.DateTime pToDate, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetPendingsamplesReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _OrgID = new System.Data.SqlClient.SqlParameter();
            _OrgID.ParameterName = "@OrgID";
            _OrgID.Size = -1;
            _OrgID.Value = OrgID;
            cmd.Parameters.Add(_OrgID);
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = -1;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = -1;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetBillsfortheDayReportCommand(string pSearchType, string pBillFromDate, string pBillToDate, long pClientID, long pCountryID, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetBillsfortheDayReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pSearchType = new System.Data.SqlClient.SqlParameter();
            _pSearchType.ParameterName = "@pSearchType";
            _pSearchType.Size = 30;
            _pSearchType.Value = pSearchType;
            cmd.Parameters.Add(_pSearchType);
            System.Data.SqlClient.SqlParameter _pBillFromDate = new System.Data.SqlClient.SqlParameter();
            _pBillFromDate.ParameterName = "@pBillFromDate";
            _pBillFromDate.Size = 25;
            _pBillFromDate.Value = pBillFromDate;
            cmd.Parameters.Add(_pBillFromDate);
            System.Data.SqlClient.SqlParameter _pBillToDate = new System.Data.SqlClient.SqlParameter();
            _pBillToDate.ParameterName = "@pBillToDate";
            _pBillToDate.Size = 25;
            _pBillToDate.Value = pBillToDate;
            cmd.Parameters.Add(_pBillToDate);
            System.Data.SqlClient.SqlParameter _pClientID = new System.Data.SqlClient.SqlParameter();
            _pClientID.ParameterName = "@pClientID";
            _pClientID.Size = -1;
            _pClientID.Value = pClientID;
            cmd.Parameters.Add(_pClientID);
            System.Data.SqlClient.SqlParameter _pCountryID = new System.Data.SqlClient.SqlParameter();
            _pCountryID.ParameterName = "@pCountryID";
            _pCountryID.Size = -1;
            _pCountryID.Value = pCountryID;
            cmd.Parameters.Add(_pCountryID);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetWeeklyMeanTATReportCommand(int OrgID, string TestType, string SearchType, int Countryid, long Clientid, int Deptid, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetWeeklyMeanTATReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _OrgID = new System.Data.SqlClient.SqlParameter();
            _OrgID.ParameterName = "@OrgID";
            _OrgID.Size = -1;
            _OrgID.Value = OrgID;
            cmd.Parameters.Add(_OrgID);
            System.Data.SqlClient.SqlParameter _TestType = new System.Data.SqlClient.SqlParameter();
            _TestType.ParameterName = "@TestType";
            _TestType.Size = 50;
            _TestType.Value = TestType;
            cmd.Parameters.Add(_TestType);
            System.Data.SqlClient.SqlParameter _SearchType = new System.Data.SqlClient.SqlParameter();
            _SearchType.ParameterName = "@SearchType";
            _SearchType.Size = 50;
            _SearchType.Value = SearchType;
            cmd.Parameters.Add(_SearchType);
            System.Data.SqlClient.SqlParameter _Countryid = new System.Data.SqlClient.SqlParameter();
            _Countryid.ParameterName = "@Countryid";
            _Countryid.Size = -1;
            _Countryid.Value = Countryid;
            cmd.Parameters.Add(_Countryid);
            System.Data.SqlClient.SqlParameter _Clientid = new System.Data.SqlClient.SqlParameter();
            _Clientid.ParameterName = "@Clientid";
            _Clientid.Size = -1;
            _Clientid.Value = Clientid;
            cmd.Parameters.Add(_Clientid);
            System.Data.SqlClient.SqlParameter _Deptid = new System.Data.SqlClient.SqlParameter();
            _Deptid.ParameterName = "@Deptid";
            _Deptid.Size = -1;
            _Deptid.Value = Deptid;
            cmd.Parameters.Add(_Deptid);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetCountryWiseClientNamesCommand(string prefixText, long pOrgId, long pcountryid, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetCountryWiseClientNames";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _prefixText = new System.Data.SqlClient.SqlParameter();
            _prefixText.ParameterName = "@prefixText";
            _prefixText.Size = 30;
            _prefixText.Value = prefixText;
            cmd.Parameters.Add(_prefixText);
            System.Data.SqlClient.SqlParameter _pOrgId = new System.Data.SqlClient.SqlParameter();
            _pOrgId.ParameterName = "@pOrgId";
            _pOrgId.Size = -1;
            _pOrgId.Value = pOrgId;
            cmd.Parameters.Add(_pOrgId);
            System.Data.SqlClient.SqlParameter _pcountryid = new System.Data.SqlClient.SqlParameter();
            _pcountryid.ParameterName = "@pcountryid";
            _pcountryid.Size = -1;
            _pcountryid.Value = pcountryid;
            cmd.Parameters.Add(_pcountryid);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetRoundNameListCommand(string prefixText, int pOrgId, string pSearchType, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetRoundNameList";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _prefixText = new System.Data.SqlClient.SqlParameter();
            _prefixText.ParameterName = "@prefixText";
            _prefixText.Size = 50;
            _prefixText.Value = prefixText;
            cmd.Parameters.Add(_prefixText);
            System.Data.SqlClient.SqlParameter _pOrgId = new System.Data.SqlClient.SqlParameter();
            _pOrgId.ParameterName = "@pOrgId";
            _pOrgId.Size = -1;
            _pOrgId.Value = pOrgId;
            cmd.Parameters.Add(_pOrgId);
            System.Data.SqlClient.SqlParameter _pSearchType = new System.Data.SqlClient.SqlParameter();
            _pSearchType.ParameterName = "@pSearchType";
            _pSearchType.Size = 10;
            _pSearchType.Value = pSearchType;
            cmd.Parameters.Add(_pSearchType);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetBloodGroupCardCommand(int OrgID, System.DateTime pFromDate, System.DateTime pToDate, int AddressID, long RoundID)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetBloodGroupCard";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _OrgID = new System.Data.SqlClient.SqlParameter();
            _OrgID.ParameterName = "@OrgID";
            _OrgID.Size = -1;
            _OrgID.Value = OrgID;
            cmd.Parameters.Add(_OrgID);
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = -1;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = -1;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _AddressID = new System.Data.SqlClient.SqlParameter();
            _AddressID.ParameterName = "@AddressID";
            _AddressID.Size = -1;
            _AddressID.Value = AddressID;
            cmd.Parameters.Add(_AddressID);
            System.Data.SqlClient.SqlParameter _RoundID = new System.Data.SqlClient.SqlParameter();
            _RoundID.ParameterName = "@RoundID";
            _RoundID.Size = -1;
            _RoundID.Value = RoundID;
            cmd.Parameters.Add(_RoundID);
            return cmd;
        }
        public static System.Data.SqlClient.SqlCommand pGetVisitWiseSearchMISReportCommand(long pOrgId, long pLocationId, long pVisitType, string pVisitStatus, long pPatientId, string pVisitNumber, string pRefNumber, long MobileNo, long pClientId, long pRefPhysicianid, string pFromDate, string pToDate, System.Data.DataTable ContextInfo)
        {
            System.Data.SqlClient.SqlCommand cmd;
            cmd = new System.Data.SqlClient.SqlCommand();
            cmd.CommandText = "pGetVisitWiseSearchMISReport";
            cmd.CommandTimeout = 180;
            cmd.CommandType = CommandType.StoredProcedure;
            System.Data.SqlClient.SqlParameter _pOrgId = new System.Data.SqlClient.SqlParameter();
            _pOrgId.ParameterName = "@pOrgId";
            _pOrgId.Size = -1;
            _pOrgId.Value = pOrgId;
            cmd.Parameters.Add(_pOrgId);
            System.Data.SqlClient.SqlParameter _pLocationId = new System.Data.SqlClient.SqlParameter();
            _pLocationId.ParameterName = "@pLocationId";
            _pLocationId.Size = -1;
            _pLocationId.Value = pLocationId;
            cmd.Parameters.Add(_pLocationId);
            System.Data.SqlClient.SqlParameter _pVisitType = new System.Data.SqlClient.SqlParameter();
            _pVisitType.ParameterName = "@pVisitType";
            _pVisitType.Size = -1;
            _pVisitType.Value = pVisitType;
            cmd.Parameters.Add(_pVisitType);
            System.Data.SqlClient.SqlParameter _pVisitStatus = new System.Data.SqlClient.SqlParameter();
            _pVisitStatus.ParameterName = "@pVisitStatus";
            _pVisitStatus.Size = 8;
            _pVisitStatus.Value = pVisitStatus;
            cmd.Parameters.Add(_pVisitStatus);
            System.Data.SqlClient.SqlParameter _pPatientId = new System.Data.SqlClient.SqlParameter();
            _pPatientId.ParameterName = "@pPatientId";
            _pPatientId.Size = -1;
            _pPatientId.Value = pPatientId;
            cmd.Parameters.Add(_pPatientId);
            System.Data.SqlClient.SqlParameter _pVisitNumber = new System.Data.SqlClient.SqlParameter();
            _pVisitNumber.ParameterName = "@pVisitNumber";
            _pVisitNumber.Size = 15;
            _pVisitNumber.Value = pVisitNumber;
            cmd.Parameters.Add(_pVisitNumber);
            System.Data.SqlClient.SqlParameter _pRefNumber = new System.Data.SqlClient.SqlParameter();
            _pRefNumber.ParameterName = "@pRefNumber";
            _pRefNumber.Size = 15;
            _pRefNumber.Value = pRefNumber;
            cmd.Parameters.Add(_pRefNumber);
            System.Data.SqlClient.SqlParameter _MobileNo = new System.Data.SqlClient.SqlParameter();
            _MobileNo.ParameterName = "@MobileNo";
            _MobileNo.Size = -1;
            _MobileNo.Value = MobileNo;
            cmd.Parameters.Add(_MobileNo);
            System.Data.SqlClient.SqlParameter _pClientId = new System.Data.SqlClient.SqlParameter();
            _pClientId.ParameterName = "@pClientId";
            _pClientId.Size = -1;
            _pClientId.Value = pClientId;
            cmd.Parameters.Add(_pClientId);
            System.Data.SqlClient.SqlParameter _pRefPhysicianid = new System.Data.SqlClient.SqlParameter();
            _pRefPhysicianid.ParameterName = "@pRefPhysicianid";
            _pRefPhysicianid.Size = -1;
            _pRefPhysicianid.Value = pRefPhysicianid;
            cmd.Parameters.Add(_pRefPhysicianid);
            System.Data.SqlClient.SqlParameter _pFromDate = new System.Data.SqlClient.SqlParameter();
            _pFromDate.ParameterName = "@pFromDate";
            _pFromDate.Size = 25;
            _pFromDate.Value = pFromDate;
            cmd.Parameters.Add(_pFromDate);
            System.Data.SqlClient.SqlParameter _pToDate = new System.Data.SqlClient.SqlParameter();
            _pToDate.ParameterName = "@pToDate";
            _pToDate.Size = 25;
            _pToDate.Value = pToDate;
            cmd.Parameters.Add(_pToDate);
            System.Data.SqlClient.SqlParameter _ContextInfo = new System.Data.SqlClient.SqlParameter();
            _ContextInfo.ParameterName = "@ContextInfo";
            _ContextInfo.Size = -1;
            _ContextInfo.Value = ContextInfo;
            cmd.Parameters.Add(_ContextInfo);
            return cmd;
        }
       
    }
}
