//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsappMediaMessage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public long LocationID { get; set; }
        public string LocationName { get; set; }
        public Nullable<long> Pincode { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string IsDefault { get; set; }
        public Nullable<short> StateID { get; set; }
    }
}
