//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsappMediaMessage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int OrgID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrganizationTypeID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
        public string LogoPath { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string IntegrationName { get; set; }
        public string OrgDisplayName { get; set; }
        public Nullable<int> ParentOrgID { get; set; }
        public Nullable<int> RootOrgID { get; set; }
        public string ReferType { get; set; }
        public Nullable<long> ReferTypeID { get; set; }
        public Nullable<long> CentreCode { get; set; }
        public Nullable<int> TimeDifference { get; set; }
        public string TimeZone { get; set; }
        public string Isbaseorg { get; set; }
        public Nullable<long> DefaultOrgID { get; set; }
        public string isdefaultorg { get; set; }
        public Nullable<int> OrgCategoryID { get; set; }
        public string HSNSAC { get; set; }
        public string ReportLanguage { get; set; }
    }
}
